
-- IAS UNIVERIS
TRUNCATE TABLE IAS_UNIVERIS."ACCOUNTS";
TRUNCATE TABLE IAS_UNIVERIS.CLIENTS;
--DB_IAW_ACCP_STAGING.IAS_UNIVERIS.COM_SRF
TRUNCATE TABLE IAS_UNIVERIS.COUNTRY;
TRUNCATE TABLE IAS_UNIVERIS.HOLDINGS;
TRUNCATE TABLE IAS_UNIVERIS.MARKETPRODUCTS;
TRUNCATE TABLE IAS_UNIVERIS.PLANS;
--DB_IAW_ACCP_STAGING.IAS_UNIVERIS.PLN_SRF
TRUNCATE TABLE IAS_UNIVERIS.PROVINCE;
TRUNCATE TABLE IAS_UNIVERIS.REGISTERED_REPRESENTATIVE;
--DB_IAW_ACCP_STAGING.IAS_UNIVERIS.REVENUE_PAYABLE
TRUNCATE TABLE IAS_UNIVERIS.S_COM_PROD;
--DB_IAW_ACCP_STAGING.IAS_UNIVERIS."TRANSACTIONS"

-- FUNDEX
TRUNCATE TABLE FUNDEX."ACCOUNTS";
TRUNCATE TABLE FUNDEX.ADVISORS;
TRUNCATE TABLE FUNDEX.CLIENTS;
--DB_IAW_ACCP_STAGING.FUNDEX.COM_SRF;
TRUNCATE TABLE FUNDEX.COUNTRY;
TRUNCATE TABLE FUNDEX.HOLDINGS;
TRUNCATE TABLE FUNDEX.MARKETPRODUCTS;
TRUNCATE TABLE FUNDEX.PLANS;
--DB_IAW_ACCP_STAGING.FUNDEX.PLN_SRF;
TRUNCATE TABLE FUNDEX.PROVINCE;
TRUNCATE TABLE FUNDEX.REGISTERED_REPRESENTATIVE;
TRUNCATE TABLE FUNDEX.REVENUES;
--DB_IAW_ACCP_STAGING.FUNDEX.REVENUE_PAYABLE;
TRUNCATE TABLE FUNDEX.S_COM_PROD;
--DB_IAW_ACCP_STAGING.FUNDEX."TRANSACTIONS";
TRUNCATE TABLE FUNDEX.WRAP_FEE;
TRUNCATE TABLE FUNDEX.X_DBB_MASTER_REP;

-- INVESTIA
TRUNCATE TABLE INVESTIA."ACCOUNTS";
TRUNCATE TABLE INVESTIA.ADVISORS;
TRUNCATE TABLE INVESTIA.CLIENTS;
--DB_IAW_ACCP_STAGING.INVESTIA.COM_SRF;
TRUNCATE TABLE INVESTIA.COUNTRY;
TRUNCATE TABLE INVESTIA.HOLDINGS;
TRUNCATE TABLE INVESTIA.MARKETPRODUCTS;
TRUNCATE TABLE INVESTIA.PLANS;
--DB_IAW_ACCP_STAGING.INVESTIA.PLN_SRF;
TRUNCATE TABLE INVESTIA.PROVINCE;
TRUNCATE TABLE INVESTIA.REGISTERED_REPRESENTATIVE;
TRUNCATE TABLE INVESTIA.REVENUES;
--DB_IAW_ACCP_STAGING.INVESTIA.REVENUE_PAYABLE;
TRUNCATE TABLE INVESTIA.S_COM_PROD;
--DB_IAW_ACCP_STAGING.INVESTIA."TRANSACTIONS";
TRUNCATE TABLE INVESTIA.WRAP_FEE;
TRUNCATE TABLE INVESTIA.X_DBB_MASTER_REP;


