-- IAS
-- Copy those tables from PROD to ACCP
TRUNCATE TABLE IAS."ACCOUNTS";
TRUNCATE TABLE IAS.CASH_HOLDINGS;
TRUNCATE TABLE IAS.CLIENTS;
TRUNCATE TABLE IAS.CLIENT_ADDRESS;
TRUNCATE TABLE IAS.EXCHANGERATE;
TRUNCATE TABLE IAS.HOLDINGS;
TRUNCATE TABLE IAS.MARKETPRODUCTS;
TRUNCATE TABLE IAS.PLANS;
TRUNCATE TABLE IAS.REGISTERED_REPRESENTATIVE;

-- FUNDATA
TRUNCATE TABLE FUNDATA.FUND;

-- IAS COMMISSION
TRUNCATE TABLE IAS_COMMISSION.REGISTERED_REPRESENTATIVE;
TRUNCATE TABLE IAS_COMMISSION."SHARE";
TRUNCATE TABLE IAS_COMMISSION."SHAREHIST";

-- IAS IAVM
TRUNCATE TABLE IAS_IAVM.EXCHANGE_RATE;
TRUNCATE TABLE IAS_IAVM.HOLIDAYS;

--IAS CERTS
TRUNCATE TABLE IAS_CERTS.REGISTERED_REPRESENTATIVE;




