SELECT 
      PLN.[PLN_SYSID],
      PLN.[IVR_SYSID],
      NULLIF(REPLACE(REPLACE(PLN.[PLN_CD], CHAR(13), ''), CHAR(10), ''),'') AS [PLN_CD],
      NULLIF(REPLACE(REPLACE(PLN_S.[PLN_ST_NAME], CHAR(13), ''), CHAR(10), ''),'') AS [PLN_STATUS],
      NULLIF(REPLACE(REPLACE(PLN.[PLN_ADM_CD], CHAR(13), ''), CHAR(10), ''),'') AS [PLN_ADM_CD],
      PLN.[SETUP_DT],
      PLN.[CLOSE_DT],
      NULLIF(REPLACE(REPLACE(PLN.[PEN_JUR_CD], CHAR(13), ''), CHAR(10), ''),'') AS [PEN_JUR_CD],
      PLN.[FEE_EXMP_IND],
                  NULLIF(REPLACE(REPLACE(DSGN.DSGN_DESC, CHAR(13), ''), CHAR(10), ''),'') AS ADMINISTRATOR_TYPE,
                  CONVERT(DATE, GETDATE()) AS MD_LOADDATE,
                  'INVESTIA-UNIVERIS' AS MD_SRCSYSTEM,
                  IVR.REP_SYSID,
                  NULLIF(REPLACE(REPLACE(R.[REP_CD], CHAR(13), ''), CHAR(10), ''),'') AS REP_CD
  FROM [dbo].[PLN] PLN (nolock)
  LEFT JOIN [dbo].[S_PLN_STATUS] PLN_S (nolock)
  ON PLN.PLN_STATUS=PLN_S.PLN_STATUS
  LEFT JOIN [dbo].[IVR] IVR (nolock)
  ON PLN.IVR_SYSID= IVR.IVR_SYSID
  LEFT JOIN [dbo].[REP] R (nolock)
  ON IVR.REP_SYSID= R.REP_SYSID
  LEFT JOIN [dbo].ADM   (nolock)
  ON PLN.PLN_ADM_CD = ADM.ADM_CD
  LEFT JOIN [dbo].[S_DESIGNATION] DSGN (nolock)
  ON ISNULL(ADM.DESIGNATION_CD,1)=DSGN.DSGN_CD
  ORDER BY PLN.[PLN_SYSID]