SELECT [IVD].[IVD_SYSID], 
       NULLIF(REPLACE(REPLACE(REPLACE([IVD].[CURRENCY_CD], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [CURRENCY_CD], 
       NULLIF(REPLACE(REPLACE(REPLACE([IVD].[SYMBOL], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [SYMBOL], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVD_STATUS].[IVD_ST_DESC_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVD_ST_DESC_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVD_STATUS].[IVD_ST_DESC_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVD_ST_DESC_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVD_LOAD].[IVD_LOAD_DESC_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVD_LOAD_DESC_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVD_LOAD].[IVD_LOAD_DESC_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVD_LOAD_DESC_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([IVT].[IVT_NAME_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVT_NAME_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([IVT].[IVT_NAME_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVT_NAME_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_CD].[IVT_CD_DESC_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVT_CD_DESC_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_CD].[IVT_CD_DESC_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVT_CD_DESC_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_STATUS].[IVT_ST_DESC_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVT_ST_DESC_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_STATUS].[IVT_ST_DESC_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVT_ST_DESC_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_ASSET_CLASS].[ASSET_CLASS_DESC_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [ASSET_CLASS_DESC_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_ASSET_CLASS].[ASSET_CLASS_DESC_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [ASSET_CLASS_DESC_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_ASSET_CATEGORY].[ASSET_CTGY_DESC_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [ASSET_CTGY_DESC_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_ASSET_CATEGORY].[ASSET_CTGY_DESC_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [ASSET_CTGY_DESC_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_TYPE].[IVT_TYPE_DESC_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVT_TYPE_DESC_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_TYPE].[IVT_TYPE_DESC_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [IVT_TYPE_DESC_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_TYPE_CATEGORY].[CTGY_DESC_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [CTGY_DESC_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_TYPE_CATEGORY].[CTGY_DESC_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [CTGY_DESC_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_TYPE_GROUP].[GROUP_DESC_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [GROUP_DESC_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([S_IVT_TYPE_GROUP].[GROUP_DESC_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [GROUP_DESC_FRE], 
       NULLIF(REPLACE(REPLACE(REPLACE([MGT].[MGT_CD], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [MGT_CD], 
       NULLIF(REPLACE(REPLACE(REPLACE([MGT].[MGT_NAME_ENG], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [MGT_NAME_ENG], 
       NULLIF(REPLACE(REPLACE(REPLACE([MGT].[MGT_NAME_FRE], CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS [MGT_NAME_FRE],
	   CONVERT(DATE, GETDATE()) AS MD_LOADDATE,
	  'INVESTIA-UNIVERIS' AS MD_SRCSYSTEM
FROM [dbo].[IVD] (nolock)
     LEFT OUTER JOIN [dbo].[S_IVD_STATUS] (nolock) ON [S_IVD_STATUS].[IVD_STATUS] = [IVD].[IVD_STATUS]
     LEFT OUTER JOIN [dbo].[S_IVD_LOAD] (nolock) ON [S_IVD_LOAD].[IVD_LOAD_CD] = [IVD].[IVD_LOAD_FLAG]
     LEFT OUTER JOIN [dbo].[IVT] (nolock) ON [IVT].[IVT_SYSID] = [IVD].[IVT_SYSID]
     LEFT OUTER JOIN [dbo].[S_IVT_CD] (nolock) ON [S_IVT_CD].[IVT_CD] = [IVT].[IVT_CD]
     LEFT OUTER JOIN [dbo].[S_IVT_STATUS] (nolock) ON [S_IVT_STATUS].[IVT_STATUS] = [IVT].[IVT_STATUS]
     LEFT OUTER JOIN [dbo].[S_ASSET_CLASS] (nolock) ON [S_ASSET_CLASS].[ASSET_CLASS] = [IVT].[ASSET_CLASS]
     LEFT OUTER JOIN [dbo].[S_ASSET_CATEGORY] (nolock) ON [S_ASSET_CATEGORY].[ASSET_CTGY] = [S_ASSET_CLASS].[ASSET_CTGY]
     LEFT OUTER JOIN [dbo].[S_IVT_TYPE] (nolock) ON [S_IVT_TYPE].IVT_TYPE = IVT.IVT_TYPE
     LEFT OUTER JOIN [dbo].[S_IVT_TYPE_CATEGORY] (nolock) ON [S_IVT_TYPE_CATEGORY].IVT_CTGY = [S_IVT_TYPE].IVT_TYPE_CTGY
     LEFT OUTER JOIN [dbo].[S_IVT_TYPE_GROUP] (nolock) ON [S_IVT_TYPE_GROUP].[GROUP_CD] = [S_IVT_TYPE].GROUP_CD
     LEFT OUTER JOIN [dbo].[MGT] (nolock) ON IVT.MGT_SYSID = MGT.MGT_SYSID
     ORDER BY [IVD].[IVD_SYSID],[S_IVT_TYPE].[IVT_TYPE_DESC_ENG]