-- Jihed and Rachid























--DB_IAW_#env#_DM
--Modification in ACCP
-- missing

create or replace TABLE DB_IAW_#env#_DWH.HOLDINGS_BDV.WT_INVESTMENT_CASH_IAS_NBIN (
	HK_LINK VARCHAR(40) COMMENT 'Hash key for the Link',
	HK_HUB_CONTRACT VARCHAR(40) COMMENT 'Hash key for HUB_CONTRACT',
	HK_HUB_INVESTMENT_PRODUCT_TYPE VARCHAR(40) COMMENT 'Hash key for HUB_INVESTMENT_PRODUCT_TYPE',
	HK_HUB_PARTY_ROLE_ADVISOR VARCHAR(40) COMMENT 'Hash key for HUB_PARTY_ROLE_ADVISOR',
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER VARCHAR(40) COMMENT 'Hash key for HUB_PARTY_ROLE_ACCOUNT_HOLDER',
	HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES VARCHAR(40) COMMENT 'Hash key for REF_INVESTMENT_SAVING_PROGRAM_TYPES',
	MD_SEQ VARCHAR(50) COMMENT 'The value of METADATA$FILE_ROW_NUMBER',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Extraction date of the occurrence',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	A_C_SUMM_SD_NET_AMT NUMBER(38,2) COMMENT 'A/C Summ settelment date Net Amt',
	A_C_SUMM_TD_NET_AMT NUMBER(38,2) COMMENT 'A/C Summ trade date Net Amt',
	A_C_SUMM_BALANCE_BUS_DATE DATE COMMENT 'Update business date',
	CONTRACT_ID VARCHAR(18) COMMENT 'Account ID',
	RR_CD VARCHAR(50) COMMENT 'Advisor RR code',
	INVESTMENT_PRODUCT_ID VARCHAR(100) COMMENT 'Product Type ID',
	MASTER_CODE VARCHAR(50) COMMENT 'Master code of the advisor',
	A_C_CLIENT VARCHAR(100) COMMENT 'Client ID',
	ACCOUNT_RAP_CODE VARCHAR(10) COMMENT 'To be defined : Last letter of an account ID',
	ASC_1_RESP_PLAN_TYPES VARCHAR(100) COMMENT 'subtype of the RESP plans',
	RETAIL_PLAN VARCHAR(50) COMMENT 'Retail plan code : RS, LF, ...',
	A_C_CURRENCY VARCHAR(10) COMMENT 'Currency of the account',
	COMMISSIONPCT NUMBER(6,3) COMMENT 'Commission Sharing Percentage',
	ISSUER_COMPANY_NAME VARCHAR(100) COMMENT 'The issuer company name',
	ASC_3_MANAGED_TYPE VARCHAR(10) COMMENT 'To be defined : J, L, ...',
	ADMINISTRATOR_TYPE VARCHAR(100) COMMENT 'Nominee, Client name, ...',
	EXCHANGERATE NUMBER(38,8) COMMENT 'Conversion rate from USD to CAD',
	A_C_ACCOUNT_CLASS VARCHAR(3) COMMENT 'Account class : 038, 040, ...',

	RETAIL_PLAN_RESP VARCHAR(1),
	COMMISSIONPCT_ADVISOR NUMBER(6,3) COMMENT 'Advisor Commission PCT',
	COMMISSIONPCT_FINANCIAL NUMBER(6,3) COMMENT 'Financial Commission PCT'
);

create or replace TABLE DB_IAW_#env#_DM.EXPLORATION.RELATIONSHIP_COMMISSION_SHARE_ACCP (
	MD_START_DT DATE COMMENT 'Start Date of the image/version',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	SHARED_CODE VARCHAR(40) COMMENT 'Unique code of representative',
	MASTER_CODE VARCHAR(40) COMMENT 'Unique code of advisor',
	COMMISSIONPCT NUMBER(6,3) COMMENT 'Commission Sharing Percentage',
	MD_ACTIVE VARCHAR(1) COMMENT 'Active Flag, \"A\" row exists in the source, \"D\" row does not exist in the source'
);

-- modified

CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DM.EXTRACTIONS.USP_COMMISSION_ORGANIC_GROWTH("p_START_DATE" VARCHAR(10))
RETURNS VARCHAR(10000)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
var vSQLTruncateCmd = " TRUNCATE TABLE EXTRACTIONS.WT_COMMISSION_ORGANIC_GROWTH;";
var vSQLSelectCmd = `
INSERT INTO EXTRACTIONS.WT_COMMISSION_ORGANIC_GROWTH SELECT * FROM (
WITH LatestVersionAdvisors AS (
		SELECT distinct 

			team_name
		FROM SHARED.DIM_ADVISOR
		WHERE (
            HK_HUB <> ''0''
            AND new_advisor <> 1



            AND month(md_start_dt) = month(dateadd(months, - 1, to_date(''@START_DATE@'')))

			AND year (md_start_dt) = year(to_date(''@START_DATE@''))
            )
            OR  (md_end_dt is null and HK_HUB <> ''0'')

		)
	,ThisMonthReport AS (
		SELECT A.TEAM_NAME
			,coalesce(sum(DECODE(FT.CASH_FLOW_TYPE, ''IN FLOW'', FT.GROSS_AMOUNT)), 0) InflowGrossAmt
			,coalesce(sum(DECODE(FT.CASH_FLOW_TYPE, ''OUT FLOW'', FT.GROSS_AMOUNT)), 0) OutflowGrossAmt
			,InflowGrossAmt + OutflowGrossAmt AS NetOrganicGrowth
		FROM SHARED.DIM_ADVISOR A
		JOIN TRANSACTIONS.FACT_TRANSACTIONS FT ON FT.SK_DIM_ADVISORS = A.ID
		WHERE month(FT.TRADE_DATE) = month(dateadd(months, - 1, to_date(''@START_DATE@'')))
			AND year(FT.trade_date) = year(to_date(''@START_DATE@''))
			AND A.new_advisor <> 1
			AND ft.departed_advisor_ind <> 1
		GROUP BY A.TEAM_NAME
		)
	,LastMonthReport AS (
		SELECT

            A.TEAM_NAME
			,coalesce(sum(DECODE(FT.CASH_FLOW_TYPE, ''IN FLOW'', FT.GROSS_AMOUNT)), 0) InflowGrossAmt
			,coalesce(sum(DECODE(FT.CASH_FLOW_TYPE, ''OUT FLOW'', FT.GROSS_AMOUNT)), 0) OutflowGrossAmt
			,InflowGrossAmt + OutflowGrossAmt AS NetOrganicGrowth
		FROM SHARED.DIM_ADVISOR A
		JOIN TRANSACTIONS.FACT_TRANSACTIONS FT ON FT.SK_DIM_ADVISORS = A.ID
		WHERE month(FT.TRADE_DATE) = month(dateadd(months, - 2, to_date(''@START_DATE@'')))
			AND year(FT.trade_date) = year(dateadd(months, - 2, to_date(''@START_DATE@'')))
			AND A.new_advisor <> 1
			AND ft.departed_advisor_ind <> 1
		GROUP BY A.TEAM_NAME
		)
	,YTDReport AS (
		SELECT 

            A.TEAM_NAME
			,coalesce(sum(DECODE(FT.CASH_FLOW_TYPE, ''IN FLOW'', FT.GROSS_AMOUNT)), 0) YTD_Inflow_GrossAmt
			,coalesce(sum(DECODE(FT.CASH_FLOW_TYPE, ''OUT FLOW'', FT.GROSS_AMOUNT)), 0) YTD_Outflow_GrossAmt
			,YTD_Inflow_GrossAmt + YTD_Outflow_GrossAmt AS YTDNetOrganicGrowth
		FROM SHARED.DIM_ADVISOR A
		JOIN TRANSACTIONS.FACT_TRANSACTIONS FT ON FT.SK_DIM_ADVISORS = A.ID
		WHERE month(FT.TRADE_DATE) <= month(dateadd(months, - 1, to_date(''@START_DATE@'')))
			AND year(FT.trade_date) = year(to_date(''@START_DATE@''))
			AND A.new_advisor <> 1
			AND ft.departed_advisor_ind <> 1
		GROUP BY A.TEAM_NAME
		)
	,PrevYTDReport AS (
		SELECT 

            A.TEAM_NAME
			,coalesce(sum(DECODE(FT.CASH_FLOW_TYPE, ''IN FLOW'', FT.GROSS_AMOUNT)), 0) YTD_Inflow_GrossAmt
			,coalesce(sum(DECODE(FT.CASH_FLOW_TYPE, ''OUT FLOW'', FT.GROSS_AMOUNT)), 0) YTD_Outflow_GrossAmt
			,YTD_Inflow_GrossAmt + YTD_Outflow_GrossAmt AS YTDNetOrganicGrowth
		FROM SHARED.DIM_ADVISOR A
		JOIN TRANSACTIONS.FACT_TRANSACTIONS FT ON FT.SK_DIM_ADVISORS = A.ID
		WHERE month(FT.TRADE_DATE) <= month(dateadd(months, - 1, to_date(''@START_DATE@'')))
			AND year(FT.trade_date) = year(dateadd(years, - 1, to_date(''@START_DATE@'')))
			AND A.new_advisor <> 1
			AND ft.departed_advisor_ind <> 1
		GROUP BY A.TEAM_NAME 
		)

SELECT DISTINCT dense_rank() OVER (
		ORDER BY YTD_Net_Organic_Growth_By_Team DESC
		) AS Team_Rank
	,resultat.team_name
	,resultat.Monthly_Net_Organic_Growth_By_Team
	,resultat.YTD_Net_Organic_Growth_By_Team
FROM (
	SELECT
		LTV.TEAM_NAME

		,coalesce(TM.InflowGrossAmt, 0) AS MONTH_IN_FLOW
		,coalesce(TM.OutFlowGrossAmt, 0) AS MONTH_OUT_FLOW
		,coalesce(TM.NetOrganicGrowth, 0) AS Actual_Monthly_Net_Organic_Growth
		,coalesce(LM.NetOrganicGrowth, 0) AS Prev_Monthly_Net_Organic_Growth
		,Actual_Monthly_Net_Organic_Growth - Prev_Monthly_Net_Organic_Growth AS Month_over_Month_growth
		,coalesce(round(((Actual_Monthly_Net_Organic_Growth - Prev_Monthly_Net_Organic_Growth) / nullif(abs(Prev_Monthly_Net_Organic_Growth), 0) * 100), 2), 0) AS Month_over_Month_growth_Percentage
		,coalesce(YTD.YTD_Inflow_GrossAmt, 0) AS YTD_Inflow_GrossAmt
		,coalesce(YTD.YTD_Outflow_GrossAmt, 0) AS YTD_Outflow_GrossAmt
		,coalesce(YTD.YTDNetOrganicGrowth, 0) AS YTD_Net_Organic_Growth
		,coalesce(PYTD.YTDNetOrganicGrowth, 0) AS Previous_YTD_Net_Organic_Growth
		,YTD_Net_Organic_Growth - Previous_YTD_Net_Organic_Growth AS YTD_Period_over_period_growth
		,coalesce(round(((YTD_Net_Organic_Growth - Previous_YTD_Net_Organic_Growth) / nullif(abs(Previous_YTD_Net_Organic_Growth), 0) * 100), 2), 0) AS YTD_Period_over_period_growth_Percentage
		,round(sum(YTD_Net_Organic_Growth) OVER (PARTITION BY LTV.team_name), 2) AS YTD_Net_Organic_Growth_By_Team
		,round(sum(Actual_Monthly_Net_Organic_Growth) OVER (PARTITION BY LTV.team_name), 2) AS Monthly_Net_Organic_Growth_By_Team
	FROM LatestVersionAdvisors LTV
	LEFT JOIN THISMONTHREPORT TM    ON   LTV.TEAM_NAME = TM.TEAM_NAME  
	LEFT JOIN LASTMONTHREPORT LM    ON   LTV.TEAM_NAME = LM.TEAM_NAME  
	LEFT JOIN YTDReport YTD         ON   LTV.TEAM_NAME = YTD.TEAM_NAME  
	LEFT JOIN PREVYTDREPORT PYTD    ON   LTV.TEAM_NAME = PYTD.TEAM_NAME
	) AS resultat
WHERE resultat.YTD_Net_Organic_Growth_By_Team <> 0

	AND resultat.team_name NOT IN (
		''iA House''
		,''National Branch''
		,''iA Wealth Advice Centre''
		,''''
		)   
ORDER BY Team_Rank
) AS T;
`;
var truncateStatement = snowflake.createStatement({sqlText: vSQLTruncateCmd});
var vSQLTruncateResult = truncateStatement.execute();
vSQLSelectCmd = vSQLSelectCmd.replace(/@START_DATE@/g, p_START_DATE);
var selectStatement = snowflake.createStatement({sqlText: vSQLSelectCmd});
var vSQLResult = selectStatement.execute();
return "SUCCESS";
';

CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DM.EXTRACTIONS.USP_EXECUTE_COPY_IF_THIRD_WORKING_DAY("p_PROCESS_DATE" VARCHAR(10), "p_FILE_PATH" VARCHAR(10))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
var vSQLCopyIntoCMD =  "COPY INTO @DATALAKE.OUT/IAPW/NBIN/" + p_FILE_PATH + "/COMMISSION_ORGANIC_GROWTH_REPORT.csv"
                       + " FROM EXTRACTIONS.WT_COMMISSION_ORGANIC_GROWTH"
                        + " File_format = (format_name = ''EXTRACTIONS.COMMISSION_EXPORT_CSV'', ENCODING = ''UTF8'')"
                        + " SINGLE = TRUE header = TRUE OVERWRITE = TRUE ";
var vSQLIfThirdMonthDay = `
SELECT	iff(
			iff(  DAYNAME(date_trunc(''MONTH'', TO_DATE(''@START_DATE@''))) = ''Sat''
                 ,  dateadd(''DAY'', 4, date_trunc(''MONTH'', TO_DATE(TO_DATE(''@START_DATE@''))))
                 ,  iff(  DAYNAME(date_trunc(''MONTH'', TO_DATE(''@START_DATE@''))) = ''Sun''
                        ,   dateadd(''DAY'', 3, date_trunc(''MONTH'', TO_DATE(TO_DATE(''@START_DATE@''))))
                        ,   iff(	DAYNAME(dateadd( ''DAY'' ,2,date_trunc(''MONTH'', TO_DATE(''@START_DATE@'')))) = ''Sat''
	                        ,  	dateadd(''DAY'', 4, date_trunc(''MONTH'', TO_DATE(TO_DATE(''@START_DATE@''))))
	                            ,	iff(	DAYNAME(dateadd(''DAY'',2, date_trunc(''MONTH'', TO_DATE(TO_DATE(''@START_DATE@''))))) = ''Sun''
		                                ,	iff(	DAYNAME(date_trunc(''MONTH'', TO_DATE(''@START_DATE@''))) = ''Fri''
												,	dateadd(''DAY'', 4, date_trunc(''MONTH'', TO_DATE(TO_DATE(''@START_DATE@''))))
												,	dateadd(''DAY'', 3, date_trunc(''MONTH'', TO_DATE(TO_DATE(''@START_DATE@''))))
											)	
		                                ,	dateadd(''DAY'', 2, date_trunc(''MONTH'', TO_DATE(TO_DATE(''@START_DATE@''))))
											
									)
	                        )
					)
            ) = TO_DATE(TO_DATE(''@START_DATE@''))
	     ,	TRUE
	     ,	FALSE
        )
`; 
vSQLIfThirdMonthDay = vSQLIfThirdMonthDay.replace(/@START_DATE@/g, p_PROCESS_DATE);
var vExecuteThirdDay = snowflake.createStatement({sqlText: vSQLIfThirdMonthDay, binds: [p_PROCESS_DATE]});
var vExecuteThirdDay = snowflake.createStatement({sqlText: vSQLIfThirdMonthDay});
var vSQLThirdDayvExecuteCopyIntoResul = vExecuteThirdDay.execute();
vSQLThirdDayvExecuteCopyIntoResul.next();
var vReturnRows = [];
if (vSQLThirdDayvExecuteCopyIntoResul.getColumnValue(1)==true){
        //      Ecexute Sp EXTRACTIONS.USP_COMMISSION_ORGANIC_GROWTH
        var vSQLCallUSPCommision = " CALL  EXTRACTIONS.USP_COMMISSION_ORGANIC_GROWTH (''"+ p_PROCESS_DATE + "'');"
        var vExecuteCallSP = snowflake.createStatement({sqlText: vSQLCallUSPCommision});
        var vExecuteCallSPResul = vExecuteCallSP.execute();
        vExecuteCallSPResul.next();     
        //      Ecexute Copy Into DataLake
        var vExecuteCopyInto = snowflake.createStatement({sqlText: vSQLCopyIntoCMD});
        var vExecuteCopyIntoResul = vExecuteCopyInto.execute();
        vExecuteCopyIntoResul.next();
        vReturnRows.push(vExecuteCopyIntoResul.getColumnValue(1));
        return vReturnRows + '' rows exported'';
}
';



-- the tables founds in the tools schema have been skipped

--data Warehouse
alter TABLE DB_IAW_#env#_DWH.HOLDINGS_BDV.WT_INVESTMENT_CASH_IAS_NBIN 
add column
	COMMISSIONPCT_ADVISOR NUMBER(6,3) COMMENT 'Advisor Commission PCT',
	COMMISSIONPCT_FINANCIAL NUMBER(6,3) COMMENT 'Financial Commission PCT'
;

alter TABLE DB_IAW_#env#_DWH.HOLDINGS_BDV.WT_INVESTMENT_IAS_NBIN
add column
	COMMISSIONPCT_ADVISOR NUMBER(6,3) COMMENT 'Advisor Commission PCT',
	COMMISSIONPCT_FINANCIAL NUMBER(6,3) COMMENT 'Financial Commission PCT'
;

alter TABLE DB_IAW_#env#_DWH.HOLDINGS_BDV.WT_INVESTMENT_IAS_UNIVERIS
add column
	COMMISSIONPCT_ADVISOR NUMBER(6,3) COMMENT 'Advisor Commission PCT',
	COMMISSIONPCT_FINANCIAL NUMBER(6,3) COMMENT 'Financial Commission PCT'
;

alter TABLE DB_IAW_#env#_DWH.HOLDINGS_BDV.WT_INVESTMENT_INVESTIA_UNIVERIS
add column
	COMMISSIONPCT_ADVISOR NUMBER(6,3) COMMENT 'Advisor Commission PCT',
	COMMISSIONPCT_FINANCIAL NUMBER(6,3) COMMENT 'Financial Commission PCT'
;

create or replace view DB_IAW_#env#_DWH.HOLDINGS_BDV.VW_INITIAL_LOADING_INVESTMENT_CASH_IAS_NBIN(
	MD_SEQ,
	HK_LINK,
	HK_HUB_CONTRACT,
	HK_HUB_INVESTMENT_PRODUCT_TYPE,
	HK_HUB_PARTY_ROLE_ADVISOR,
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
	MD_START_DT,
	MD_CREATION_DT,
	MD_EXTRACT_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	A_C_SUMM_SD_NET_AMT,
	A_C_SUMM_TD_NET_AMT,
	A_C_SUMM_BALANCE_BUS_DATE,
	CONTRACT_ID,
	RR_CD,
	INVESTMENT_PRODUCT_ID,
	MASTER_CODE,
	A_C_CLIENT,
	ACCOUNT_RAP_CODE,
	ASC_1_RESP_PLAN_TYPES,
	RETAIL_PLAN,
	A_C_CURRENCY,
	COMMISSIONPCT,
	ISSUE_COMPANY_NAME,
	ASC_3_MANAGED_TYPE,
	ADMINISTRATOR_TYPE,
	A_C_ACCOUNT_CLASS,
	RETAIL_PLAN_RESP,
	EXCHANGERATE,
	COMMISSIONPCT_ADVISOR,
	COMMISSIONPCT_FINANCIAL
) as
WITH LATEST_VERSION_SHARE AS (
	SELECT 
	SLH.HK_LINK,
	COMM_SHARE.HK_HUB_REGISTERED_REPRESENTATIVE,
	COMM_SHARE.MD_START_DT,
	COMM_SHARE.HK_HUB_PARTY_ROLE_ADVISOR,
	COMM_SHARE.MASTER_CODE,
	COMM_SHARE.COMMISSIONPCT,
	COALESCE (COMM_SHARE.MD_ACTIVE,'A') AS MD_ACTIVE,
	COALESCE (ROW_NUMBER() OVER (PARTITION BY SLH.HK_LINK,COMM_SHARE.HK_LINK ORDER BY COMM_SHARE.MD_START_DT DESC ),1) AS RANK_SHARE,
	COMM_SHARE.COMMISSIONPCT_ADVISOR,
	COMM_SHARE.COMMISSIONPCT_FINANCIAL
	FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_CASH_RR_IAS_NBIN SLH
	INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
	    ON  SLH.HK_LINK=LH.HK_LINK
	LEFT JOIN 	( SELECT LCS.HK_LINK,LCS.HK_HUB_REGISTERED_REPRESENTATIVE,CS.MD_START_DT,LCS.HK_HUB_PARTY_ROLE_ADVISOR,LCS.MASTER_CODE,CS.COMMISSIONPCT,CS.MD_ACTIVE,CS.COMMISSIONPCT_ADVISOR,CS.COMMISSIONPCT_FINANCIAL
	        	FROM SHARED_BDV.LINK_PARTY_RELATIONSHIP_SHARE LCS 
	        	INNER JOIN SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_SHARE CS 
	        		ON CS.HK_LINK=LCS.HK_LINK AND CS.MD_SRC_SYSTEM = 'IAS'
	    		) COMM_SHARE
	    ON LH.HK_HUB_REGISTERED_REPRESENTATIVE=COMM_SHARE.HK_HUB_REGISTERED_REPRESENTATIVE
	    AND  COMM_SHARE.MD_START_DT <= DATEADD(SECOND, 86399, SLH.MD_START_DT) 
),
LATEST_VERSION_CONTRACT AS (
	SELECT SLH.HK_LINK,
	CONTRACT.HK_HUB,
	CONTRACT.A_C_CLIENT, 
	CONTRACT.ACCOUNT_RAP_CODE,
	CONTRACT.ASC_1_RESP_PLAN_TYPES,
	CONTRACT.RETAIL_PLAN,
	CONTRACT.A_C_CURRENCY,
	CONTRACT.ASC_3_MANAGED_TYPE,
	CONTRACT.ADMINISTRATOR_TYPE,
	CONTRACT.A_C_ACCOUNT_CLASS,
	CONTRACT.RETAIL_PLAN_RESP,
	COALESCE (CONTRACT.MD_ACTIVE,'A') AS MD_ACTIVE,
	COALESCE (ROW_NUMBER() OVER (PARTITION BY SLH.HK_LINK,CONTRACT.HK_HUB ORDER BY CONTRACT.MD_START_DT DESC ),1) AS RANK_CONTRACT
	FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_CASH_RR_IAS_NBIN SLH
	INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
    ON  SLH.HK_LINK=LH.HK_LINK
	LEFT JOIN  SHARED_RDV.SAT_CONTRACT_IAS_NBIN CONTRACT
	    ON LH.HK_HUB_CONTRACT = CONTRACT.HK_HUB
	    AND CONTRACT.MD_START_DT <= SLH.MD_START_DT
)
SELECT 	LH.MD_SEQ,	
		SHA1(UPPER(CONCAT(
		      COALESCE(TRIM(LH.MD_SEQ), '#NULL#'), '|' 
		    , COALESCE(TRIM(LH.MD_SOURCE), '#NULL#'), '|' 
		    , COALESCE(TRIM(LH.MD_SRC_SYSTEM), '#NULL#'), '|' 
		    , COALESCE(TRIM(SLH.MD_EXTRACT_DT), '#NULL#'), '|' 
		    , COALESCE(TRIM(LH.CONTRACT_ID), '#NULL#'), '|' 
		    , COALESCE(TRIM(COMM_SHARE.MASTER_CODE), '#NULL#'), '|' 
		    , COALESCE(TRIM(LH.INVESTMENT_PRODUCT_ID), '#NULL#'), '|' 
		    , COALESCE(TRIM(CONTRACT.A_C_CLIENT), '#NULL#'), '|' 
		    ,'#NULL#', '|' -- PLN_MNEM
		    ,COALESCE(TRIM(CONTRACT.ACCOUNT_RAP_CODE), '#NULL#'), '|' 
		    ,COALESCE(TRIM(CONTRACT.RETAIL_PLAN),'#NULL#'), '|'
		    ,COALESCE(TRIM(CONTRACT.ASC_1_RESP_PLAN_TYPES),'#NULL#'), '|' 
		    , '#NULL#' -- PLN_SYSID
	    ))) AS HK_LINK,
		COALESCE(LH.HK_HUB_CONTRACT,'0') AS HK_HUB_CONTRACT, 
		SHA1(CONCAT('IAS', '|' , 'IASCASH')) AS HK_HUB_INVESTMENT_PRODUCT_TYPE, 
		COALESCE(COMM_SHARE.HK_HUB_PARTY_ROLE_ADVISOR,'0') AS HK_HUB_PARTY_ROLE_ADVISOR, 
		DECODE(TRUE, CONTRACT.A_C_CLIENT IS NULL ,'0',SHA1(UPPER(CONCAT(COALESCE(TRIM(LH.MD_SRC_SYSTEM), '#NULL#'), '|' , COALESCE(TRIM(CONTRACT.A_C_CLIENT), '#NULL#')))))  AS HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, 
		DECODE(TRUE, CONTRACT.ASC_1_RESP_PLAN_TYPES IS NULL AND CONTRACT.RETAIL_PLAN IS NULL AND CONTRACT.ACCOUNT_RAP_CODE IS NULL ,'0', 
		SHA1(UPPER(CONCAT(COALESCE(TRIM(LH.MD_SRC_SYSTEM),'#NULL#') ,'|', '#NULL#','|',COALESCE(TRIM(CONTRACT.ACCOUNT_RAP_CODE),'#NULL#'), '|',  COALESCE(TRIM(CONTRACT.RETAIL_PLAN),'#NULL#'),'|', 
		COALESCE(TRIM(CASE WHEN CONTRACT.ACCOUNT_RAP_CODE <> 'Z' THEN NULL ELSE CONTRACT.ASC_1_RESP_PLAN_TYPES END),'#NULL#'))))) AS HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
		--DATEADD(DAY,1,SLH.A_C_SUMM_BALANCE_BUS_DATE) AS MD_START_DT, 
		SLH.MD_EXTRACT_DT AS MD_START_DT,
		CURRENT_TIMESTAMP() AS MD_CREATION_DT, 
		SLH.MD_EXTRACT_DT AS MD_EXTRACT_DT, 
		LH.MD_SOURCE AS MD_SOURCE, 
		LH.MD_SRC_SYSTEM AS MD_SRC_SYSTEM, 
		SLH.A_C_SUMM_SD_NET_AMT,
		SLH.A_C_SUMM_TD_NET_AMT,
		--SLH.A_C_SUMM_BALANCE_BUS_DATE ,
		CASE WHEN DATEDIFF( DAY, SLH.MD_EXTRACT_DT, SLH.A_C_SUMM_BALANCE_BUS_DATE ) <> -1 THEN DATEADD(DAY,-1,SLH.MD_EXTRACT_DT) ELSE SLH.A_C_SUMM_BALANCE_BUS_DATE END AS A_C_SUMM_BALANCE_BUS_DATE,
		LH.CONTRACT_ID AS CONTRACT_ID, 
		LH.RR_CD AS RR_CD, 
		LH.INVESTMENT_PRODUCT_ID AS INVESTMENT_PRODUCT_ID, 
		COMM_SHARE.MASTER_CODE AS MASTER_CODE, 
		CONTRACT.A_C_CLIENT AS A_C_CLIENT, 
		CONTRACT.ACCOUNT_RAP_CODE,
		CONTRACT.ASC_1_RESP_PLAN_TYPES AS ASC_1_RESP_PLAN_TYPES	,
		CONTRACT.RETAIL_PLAN,
		CONTRACT.A_C_CURRENCY,
		COMM_SHARE.COMMISSIONPCT,
		'' AS ISSUE_COMPANY_NAME,
		CONTRACT.ASC_3_MANAGED_TYPE,
		CONTRACT.ADMINISTRATOR_TYPE,
		CONTRACT.A_C_ACCOUNT_CLASS,
		CONTRACT.RETAIL_PLAN_RESP,
		LER.EXCHANGERATE,
		COMM_SHARE.COMMISSIONPCT_ADVISOR,
		COMM_SHARE.COMMISSIONPCT_FINANCIAL
FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_CASH_RR_IAS_NBIN SLH
INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
    ON  SLH.HK_LINK=LH.HK_LINK
LEFT JOIN LATEST_VERSION_SHARE COMM_SHARE
    ON LH.HK_HUB_REGISTERED_REPRESENTATIVE=COMM_SHARE.HK_HUB_REGISTERED_REPRESENTATIVE
    AND  COMM_SHARE.HK_LINK = SLH.HK_LINK 
    AND  COMM_SHARE.MD_ACTIVE = 'A' AND COMM_SHARE.RANK_SHARE = 1
LEFT JOIN LATEST_VERSION_CONTRACT CONTRACT
    ON LH.HK_HUB_CONTRACT = CONTRACT.HK_HUB
    AND CONTRACT.HK_LINK = SLH.HK_LINK 
    AND  CONTRACT.MD_ACTIVE = 'A' AND CONTRACT.RANK_CONTRACT = 1
LEFT JOIN SHARED_BDV.TRANSLINK_EXCHANGE_RATE LER
	ON LER.EXCHANGE_DATE = SLH.A_C_SUMM_BALANCE_BUS_DATE;


create or replace view DB_IAW_#env#_DWH.HOLDINGS_BDV.VW_INITIAL_LOADING_INVESTMENT_IAS_NBIN(
	MD_SEQ,
	HK_LINK,
	HK_HUB_CONTRACT,
	HK_HUB_INVESTMENT_PRODUCT_TYPE,
	HK_HUB_PARTY_ROLE_ADVISOR,
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
	MD_START_DT,
	MD_CREATION_DT,
	MD_EXTRACT_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	A_C_SUMM_SD_NET_AMT,
	A_C_SUMM_TD_NET_AMT,
	A_C_SUMM_BALANCE_BUS_DATE,
	CONTRACT_ID,
	RR_CD,
	INVESTMENT_PRODUCT_ID,
	MASTER_CODE,
	A_C_CLIENT,
	ACCOUNT_RAP_CODE,
	ASC_1_RESP_PLAN_TYPES,
	RETAIL_PLAN,
	A_C_CURRENCY,
	COMMISSIONPCT,
	ISSUE_COMPANY_NAME,
	ASC_3_MANAGED_TYPE,
	ADMINISTRATOR_TYPE,
	A_C_ACCOUNT_CLASS,
	RETAIL_PLAN_RESP,
	EXCHANGERATE,
	COMMISSIONPCT_ADVISOR,
	COMMISSIONPCT_FINANCIAL
) as
WITH LATEST_VERSION_SHARE AS (
	SELECT 
	SLH.HK_LINK,
	COMM_SHARE.HK_HUB_REGISTERED_REPRESENTATIVE,
	COMM_SHARE.MD_START_DT,
	COMM_SHARE.HK_HUB_PARTY_ROLE_ADVISOR,
	COMM_SHARE.MASTER_CODE,
	COMM_SHARE.COMMISSIONPCT,
	COALESCE (COMM_SHARE.MD_ACTIVE,'A') AS MD_ACTIVE,
	COALESCE (ROW_NUMBER() OVER (PARTITION BY SLH.HK_LINK,COMM_SHARE.HK_LINK ORDER BY COMM_SHARE.MD_START_DT DESC ),1) AS RANK_SHARE,
	COMM_SHARE.COMMISSIONPCT_ADVISOR,
	COMM_SHARE.COMMISSIONPCT_FINANCIAL
	FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_CASH_RR_IAS_NBIN SLH
	INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
	    ON  SLH.HK_LINK=LH.HK_LINK
	LEFT JOIN 	( SELECT LCS.HK_LINK,LCS.HK_HUB_REGISTERED_REPRESENTATIVE,CS.MD_START_DT,LCS.HK_HUB_PARTY_ROLE_ADVISOR,LCS.MASTER_CODE,CS.COMMISSIONPCT,CS.MD_ACTIVE,CS.COMMISSIONPCT_ADVISOR,CS.COMMISSIONPCT_FINANCIAL
	        	FROM SHARED_BDV.LINK_PARTY_RELATIONSHIP_SHARE LCS 
	        	INNER JOIN SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_SHARE CS 
	        		ON CS.HK_LINK=LCS.HK_LINK AND CS.MD_SRC_SYSTEM = 'IAS'
	    		) COMM_SHARE
	    ON LH.HK_HUB_REGISTERED_REPRESENTATIVE=COMM_SHARE.HK_HUB_REGISTERED_REPRESENTATIVE
	    AND  COMM_SHARE.MD_START_DT <= DATEADD(SECOND, 86399, SLH.MD_START_DT)
),
LATEST_VERSION_CONTRACT AS (
	SELECT SLH.HK_LINK,
	CONTRACT.HK_HUB,
	CONTRACT.A_C_CLIENT, 
	CONTRACT.ACCOUNT_RAP_CODE,
	CONTRACT.ASC_1_RESP_PLAN_TYPES,
	CONTRACT.RETAIL_PLAN,
	CONTRACT.A_C_CURRENCY,
	CONTRACT.ASC_3_MANAGED_TYPE,
	CONTRACT.ADMINISTRATOR_TYPE,
	CONTRACT.A_C_ACCOUNT_CLASS,
	CONTRACT.RETAIL_PLAN_RESP,
	COALESCE (CONTRACT.MD_ACTIVE,'A') AS MD_ACTIVE,
	COALESCE (ROW_NUMBER() OVER (PARTITION BY SLH.HK_LINK,CONTRACT.HK_HUB ORDER BY CONTRACT.MD_START_DT DESC ),1) AS RANK_CONTRACT
	FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_CASH_RR_IAS_NBIN SLH
	INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
    ON  SLH.HK_LINK=LH.HK_LINK
	LEFT JOIN  SHARED_RDV.SAT_CONTRACT_IAS_NBIN CONTRACT
	    ON LH.HK_HUB_CONTRACT = CONTRACT.HK_HUB
	    AND CONTRACT.MD_START_DT <= SLH.MD_START_DT
)
SELECT 	LH.MD_SEQ,	
		SHA1(UPPER(CONCAT(
		      COALESCE(TRIM(LH.MD_SEQ), '#NULL#'), '|' 
		    , COALESCE(TRIM(LH.MD_SOURCE), '#NULL#'), '|' 
		    , COALESCE(TRIM(LH.MD_SRC_SYSTEM), '#NULL#'), '|' 
		    , COALESCE(TRIM(SLH.MD_EXTRACT_DT), '#NULL#'), '|' 
		    , COALESCE(TRIM(LH.CONTRACT_ID), '#NULL#'), '|' 
		    , COALESCE(TRIM(COMM_SHARE.MASTER_CODE), '#NULL#'), '|' 
		    , COALESCE(TRIM(LH.INVESTMENT_PRODUCT_ID), '#NULL#'), '|' 
		    , COALESCE(TRIM(CONTRACT.A_C_CLIENT), '#NULL#'), '|' 
		    ,'#NULL#', '|' -- PLN_MNEM
		    ,COALESCE(TRIM(CONTRACT.ACCOUNT_RAP_CODE), '#NULL#'), '|' 
		    ,COALESCE(TRIM(CONTRACT.RETAIL_PLAN),'#NULL#'), '|'
		    ,COALESCE(TRIM(CONTRACT.ASC_1_RESP_PLAN_TYPES),'#NULL#'), '|' 
		    , '#NULL#' -- PLN_SYSID
	    ))) AS HK_LINK,
		COALESCE(LH.HK_HUB_CONTRACT,'0') AS HK_HUB_CONTRACT, 
		SHA1(CONCAT('IAS', '|' , 'IASCASH')) AS HK_HUB_INVESTMENT_PRODUCT_TYPE, 
		COALESCE(COMM_SHARE.HK_HUB_PARTY_ROLE_ADVISOR,'0') AS HK_HUB_PARTY_ROLE_ADVISOR, 
		DECODE(TRUE, CONTRACT.A_C_CLIENT IS NULL ,'0',SHA1(UPPER(CONCAT(COALESCE(TRIM(LH.MD_SRC_SYSTEM), '#NULL#'), '|' , COALESCE(TRIM(CONTRACT.A_C_CLIENT), '#NULL#')))))  AS HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, 
		DECODE(TRUE, CONTRACT.ASC_1_RESP_PLAN_TYPES IS NULL AND CONTRACT.RETAIL_PLAN IS NULL AND CONTRACT.ACCOUNT_RAP_CODE IS NULL ,'0', 
		SHA1(UPPER(CONCAT(COALESCE(TRIM(LH.MD_SRC_SYSTEM),'#NULL#') ,'|', '#NULL#','|',COALESCE(TRIM(CONTRACT.ACCOUNT_RAP_CODE),'#NULL#'), '|',  COALESCE(TRIM(CONTRACT.RETAIL_PLAN),'#NULL#'),'|', 
		COALESCE(TRIM(CASE WHEN CONTRACT.ACCOUNT_RAP_CODE <> 'Z' THEN NULL ELSE CONTRACT.ASC_1_RESP_PLAN_TYPES END),'#NULL#'))))) AS HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
		--DATEADD(DAY,1,SLH.A_C_SUMM_BALANCE_BUS_DATE) AS MD_START_DT, 
		SLH.MD_EXTRACT_DT AS MD_START_DT,
		CURRENT_TIMESTAMP() AS MD_CREATION_DT, 
		SLH.MD_EXTRACT_DT AS MD_EXTRACT_DT, 
		LH.MD_SOURCE AS MD_SOURCE, 
		LH.MD_SRC_SYSTEM AS MD_SRC_SYSTEM, 
		SLH.A_C_SUMM_SD_NET_AMT,
		SLH.A_C_SUMM_TD_NET_AMT,
		--SLH.A_C_SUMM_BALANCE_BUS_DATE ,
		CASE WHEN DATEDIFF( DAY, SLH.MD_EXTRACT_DT, SLH.A_C_SUMM_BALANCE_BUS_DATE ) <> -1 THEN DATEADD(DAY,-1,SLH.MD_EXTRACT_DT) ELSE SLH.A_C_SUMM_BALANCE_BUS_DATE END AS A_C_SUMM_BALANCE_BUS_DATE,
		LH.CONTRACT_ID AS CONTRACT_ID, 
		LH.RR_CD AS RR_CD, 
		LH.INVESTMENT_PRODUCT_ID AS INVESTMENT_PRODUCT_ID, 
		COMM_SHARE.MASTER_CODE AS MASTER_CODE, 
		CONTRACT.A_C_CLIENT AS A_C_CLIENT, 
		CONTRACT.ACCOUNT_RAP_CODE,
		CONTRACT.ASC_1_RESP_PLAN_TYPES AS ASC_1_RESP_PLAN_TYPES	,
		CONTRACT.RETAIL_PLAN,
		CONTRACT.A_C_CURRENCY,
		COMM_SHARE.COMMISSIONPCT,
		'' AS ISSUE_COMPANY_NAME,

		CONTRACT.ASC_3_MANAGED_TYPE,
		CONTRACT.ADMINISTRATOR_TYPE,
		CONTRACT.A_C_ACCOUNT_CLASS,
		CONTRACT.RETAIL_PLAN_RESP,
		LER.EXCHANGERATE,
		COMM_SHARE.COMMISSIONPCT_ADVISOR,
		COMM_SHARE.COMMISSIONPCT_FINANCIAL
FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_CASH_RR_IAS_NBIN SLH
INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
    ON  SLH.HK_LINK=LH.HK_LINK
LEFT JOIN LATEST_VERSION_SHARE COMM_SHARE
    ON LH.HK_HUB_REGISTERED_REPRESENTATIVE=COMM_SHARE.HK_HUB_REGISTERED_REPRESENTATIVE
    AND  COMM_SHARE.HK_LINK = SLH.HK_LINK 
    AND  COMM_SHARE.MD_ACTIVE = 'A' AND COMM_SHARE.RANK_SHARE = 1
LEFT JOIN LATEST_VERSION_CONTRACT CONTRACT
    ON LH.HK_HUB_CONTRACT = CONTRACT.HK_HUB
    AND CONTRACT.HK_LINK = SLH.HK_LINK 
    AND  CONTRACT.MD_ACTIVE = 'A' AND CONTRACT.RANK_CONTRACT = 1
LEFT JOIN SHARED_BDV.TRANSLINK_EXCHANGE_RATE LER
	ON LER.EXCHANGE_DATE = SLH.A_C_SUMM_BALANCE_BUS_DATE;



create or replace view DB_IAW_#env#_DWH.HOLDINGS_BDV.VW_INITIAL_LOADING_INVESTMENT_INVESTIA_UNIVERIS(
	HK_HUB_CONTRACT,
	HK_HUB_INVESTMENT_PRODUCT_TYPE,
	HK_HUB_PARTY_ROLE_ADVISOR,
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
	MD_SEQ,
	MD_START_DT,
	MD_EXTRACT_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	CONTRACT_ID,
	INVESTMENT_PRODUCT_ID,
	MASTER_CODE,
	RR_CD,
	UNIVERIS_CLIENT_ID,
	PLN_MNEM,
	COMMISSIONPCT,
	ISSUER_COMPANY_NAME,
	ADMINISTRATOR_TYPE,
	BAL_DATE,
	MV,
	AUA,
	UNIVERIS_PLAN_ID,
	IVD_LOAD_FLAG,
	WF_IND,
	COMMISSIONPCT_ADVISOR,
	COMMISSIONPCT_FINANCIAL
) as
WITH 
LATEST_VERSION_INVESTMENT_CONTRACT AS (
	SELECT SLH.HK_LINK,
	CONTRACT.HK_HUB_REGISTERED_REPRESENTATIVE,
    CONTRACT.HK_HUB_CONTRACT,
    CONTRACT.RR_CD,
	COALESCE (CONTRACT.MD_ACTIVE,'A') AS MD_ACTIVE,
	COALESCE (ROW_NUMBER() OVER (PARTITION BY SLH.HK_LINK, CONTRACT.HK_HUB_CONTRACT ORDER BY CONTRACT.MD_START_DT DESC ),1) AS RANK_CONTRACT
	FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_RR_INVESTIA_UNIVERIS SLH
	INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
    ON  SLH.HK_LINK=LH.HK_LINK
	LEFT JOIN  
    (   SELECT L.HK_HUB_REGISTERED_REPRESENTATIVE, L.HK_HUB_CONTRACT,L.RR_CD, S.MD_ACTIVE, S.MD_START_DT 
        FROM SHARED_RDV.LINK_INVESTMENT_CONTRACT_RR L 
        INNER JOIN SHARED_RDV.SAT_LINK_INVESTMENT_CONTRACT_INVESTIA_UNIVERIS S ON L.HK_LINK = S.HK_LINK
    )   CONTRACT
	    ON LH.HK_HUB_CONTRACT = CONTRACT.HK_HUB_CONTRACT
	    AND CONTRACT.MD_START_DT <= SLH.MD_START_DT
),
LATEST_VERSION_CONTRACT AS (
	SELECT SLH.HK_LINK,
	CONTRACT.HK_HUB,
	CONTRACT.ADMINISTRATOR_TYPE,
	COALESCE (CONTRACT.MD_ACTIVE,'A') AS MD_ACTIVE,
	COALESCE (ROW_NUMBER() OVER (PARTITION BY SLH.HK_LINK, CONTRACT.HK_HUB ORDER BY CONTRACT.MD_START_DT DESC ),1) AS RANK_CONTRACT
	FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_RR_INVESTIA_UNIVERIS SLH
	INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
    ON  SLH.HK_LINK=LH.HK_LINK
	LEFT JOIN  SHARED_RDV.SAT_CONTRACT_IAS_NBIN CONTRACT
	    ON LH.HK_HUB_CONTRACT = CONTRACT.HK_HUB
	    AND CONTRACT.MD_START_DT <= SLH.MD_START_DT
),
LATEST_VERSION_SHARE AS (
	SELECT 
      SLH.HK_LINK,
      COMM_SHARE.HK_HUB_REGISTERED_REPRESENTATIVE,
      LIC.HK_HUB_CONTRACT,
      LIC.RR_CD,
      COMM_SHARE.MD_START_DT,
      COMM_SHARE.HK_HUB_PARTY_ROLE_ADVISOR,
      COMM_SHARE.MASTER_CODE,
      COMM_SHARE.COMMISSIONPCT,
      COALESCE (COMM_SHARE.MD_ACTIVE,'A') AS MD_ACTIVE,
      COALESCE (ROW_NUMBER() OVER (PARTITION BY SLH.HK_LINK,COMM_SHARE.HK_LINK ORDER BY COMM_SHARE.MD_START_DT DESC ),1) AS RANK_SHARE,
	  COMM_SHARE.COMMISSIONPCT_ADVISOR,
	  COMM_SHARE.COMMISSIONPCT_FINANCIAL
    FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_RR_INVESTIA_UNIVERIS SLH
	INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
	    ON  SLH.HK_LINK=LH.HK_LINK	
    LEFT JOIN LATEST_VERSION_INVESTMENT_CONTRACT LIC
        ON SLH.HK_LINK = LIC.HK_LINK
        AND LH.HK_HUB_CONTRACT= LIC.HK_HUB_CONTRACT
	    AND LIC.MD_ACTIVE = 'A' AND LIC.RANK_CONTRACT = 1
	LEFT JOIN 	( SELECT LCS.HK_LINK,LCS.HK_HUB_REGISTERED_REPRESENTATIVE,CS.MD_START_DT,LCS.HK_HUB_PARTY_ROLE_ADVISOR,LCS.MASTER_CODE,CS.COMMISSIONPCT,CS.MD_ACTIVE,CS.COMMISSIONPCT_ADVISOR,CS.COMMISSIONPCT_FINANCIAL
	        	FROM SHARED_BDV.LINK_PARTY_RELATIONSHIP_SHARE LCS 
	        	INNER JOIN SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_SHARE CS 
	        		ON CS.HK_LINK=LCS.HK_LINK AND CS.MD_SRC_SYSTEM = 'INVESTIA-UNIVERIS'
	    		) COMM_SHARE
	ON LIC.HK_HUB_REGISTERED_REPRESENTATIVE=COMM_SHARE.HK_HUB_REGISTERED_REPRESENTATIVE
	AND  COMM_SHARE.MD_START_DT <= DATEADD(SECOND, 86399, SLH.MD_START_DT) 
),
LATEST_VERSION_PRODUCT AS (
	SELECT SLH.HK_LINK,
	PRODUCT.HK_HUB ,
	PRODUCT.ISSUER_COMPANY_NAME,
	COALESCE (PRODUCT.MD_ACTIVE,'A') AS MD_ACTIVE,
	COALESCE (ROW_NUMBER() OVER (PARTITION BY SLH.HK_LINK,PRODUCT.HK_HUB ORDER BY PRODUCT.MD_START_DT DESC ),1) AS RANK_PRODUCT
	FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_RR_INVESTIA_UNIVERIS SLH
	INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
    ON  SLH.HK_LINK=LH.HK_LINK
	LEFT JOIN  
	(SELECT H.HK_HUB , P.ISSUER_COMPANY_NAME, P.MD_ACTIVE, P.MD_START_DT FROM SHARED_BDV.SAT_INVESTMENT_PRODUCT_TYPE_COMPUTE P 
	INNER JOIN SHARED_RDV.HUB_INVESTMENT_PRODUCT_TYPE H ON H.HK_HUB = P.HK_HUB WHERE P.MD_SRC_SYSTEM = 'INVESTIA-UNIVERIS') PRODUCT
	    ON LH.HK_HUB_INVESTMENT_PRODUCT_TYPE = PRODUCT.HK_HUB
	    AND PRODUCT.MD_START_DT <= SLH.MD_START_DT
),
LATEST_VERSION_BDV_INVESTMENT_CONTRACT AS (
SELECT SLR.HK_LINK,
SLR.MD_START_DT,
LC.HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES ,
LC.PLN_MNEM ,
LC.HK_HUB_CONTRACT,
LC.MD_SRC_SYSTEM ,
LC.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
COMM_SHARE.HK_HUB_PARTY_ROLE_ADVISOR,
COALESCE (SLC.MD_ACTIVE,'A') AS MD_ACTIVE,
COALESCE (ROW_NUMBER() OVER (PARTITION BY SLR.HK_LINK,LR.HK_HUB_CONTRACT ORDER BY SLC.MD_START_DT DESC ),1) AS RANK_CONTRACT
FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_RR_INVESTIA_UNIVERIS SLR
INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LR
ON SLR.HK_LINK = LR.HK_LINK
LEFT JOIN LATEST_VERSION_SHARE COMM_SHARE
ON COMM_SHARE.HK_LINK = SLR.HK_LINK
AND COMM_SHARE.MD_ACTIVE = 'A' AND COMM_SHARE.RANK_SHARE = 1
LEFT JOIN SHARED_BDV.LINK_INVESTMENT_CONTRACT LC
ON LC.HK_HUB_CONTRACT = LR.HK_HUB_CONTRACT
AND lc.HK_HUB_PARTY_ROLE_ADVISOR = COMM_SHARE.HK_HUB_PARTY_ROLE_ADVISOR
LEFT JOIN SHARED_BDV.SAT_LINK_INVESTMENT_CONTRACT SLC
ON SLC.HK_LINK = LC.HK_LINK
AND SLC.MD_START_DT <= SLR.MD_START_DT
)
SELECT DISTINCT
  LH.HK_HUB_CONTRACT,
  LH.HK_HUB_INVESTMENT_PRODUCT_TYPE,
  COMM_SHARE.HK_HUB_PARTY_ROLE_ADVISOR,
  LIC.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
  LIC.HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
  LH.MD_SEQ,
  SLH.MD_START_DT,
  LH.MD_EXTRACT_DT,
  LH.MD_SOURCE,
  LH.MD_SRC_SYSTEM,
  LH.CONTRACT_ID,
  LH.INVESTMENT_PRODUCT_ID,
  COMM_SHARE.MASTER_CODE,
  COMM_SHARE.RR_CD, 
  LH.UNIVERIS_CLIENT_ID,
  LIC.PLN_MNEM,
  COMM_SHARE.COMMISSIONPCT,
  PRODUCT.ISSUER_COMPANY_NAME,
  CONTRACT.ADMINISTRATOR_TYPE,
  SLH.BAL_DATE,
  SLH.MV,
  SLH.AUA,
  LH.UNIVERIS_PLAN_ID,
  SLH.IVD_LOAD_FLAG,
  SLH.WF_IND,
  COMM_SHARE.COMMISSIONPCT_ADVISOR,
  COMM_SHARE.COMMISSIONPCT_FINANCIAL
FROM HOLDINGS_RDV.SAT_LINK_INVESTMENT_RR_INVESTIA_UNIVERIS SLH
INNER JOIN HOLDINGS_RDV.LINK_INVESTMENT_RR_IAS_NBIN LH
    ON  SLH.HK_LINK=LH.HK_LINK
LEFT JOIN LATEST_VERSION_SHARE COMM_SHARE
    ON LH.HK_HUB_CONTRACT =COMM_SHARE.HK_HUB_CONTRACT
    AND  COMM_SHARE.HK_LINK = SLH.HK_LINK 
    AND  COMM_SHARE.MD_ACTIVE = 'A' AND COMM_SHARE.RANK_SHARE = 1
LEFT JOIN LATEST_VERSION_PRODUCT PRODUCT 
	ON PRODUCT.HK_HUB = LH.HK_HUB_INVESTMENT_PRODUCT_TYPE 
	AND LH.HK_LINK = PRODUCT.HK_LINK
	AND PRODUCT.MD_ACTIVE = 'A' AND PRODUCT.RANK_PRODUCT = 1
LEFT JOIN LATEST_VERSION_BDV_INVESTMENT_CONTRACT LIC
    ON LIC.HK_LINK = SLH.HK_LINK
	AND LIC.HK_HUB_PARTY_ROLE_ADVISOR =COMM_SHARE.HK_HUB_PARTY_ROLE_ADVISOR
	AND LIC.MD_ACTIVE = 'A' AND LIC.RANK_CONTRACT = 1
LEFT JOIN LATEST_VERSION_CONTRACT CONTRACT 
	ON CONTRACT.HK_HUB = LH.HK_HUB_CONTRACT 
	AND LH.HK_LINK = CONTRACT.HK_LINK
	AND CONTRACT.MD_ACTIVE = 'A' AND CONTRACT.RANK_CONTRACT = 1;


	create or replace TABLE DB_IAW_#env#_DWH.HOLDINGS_RDV.SAT_LINK_INVESTMENT_IAS_UNIVERIS -- in dev
	create or replace TABLE DB_IAW_#env#_DWH.HOLDINGS_RDV.SAT_LINK_INVESTMENT_INVESTIA_UNIVERIS -- in accp

	create or replace TABLE DB_IAW_#env#_DWH.HOLDINGS_RDV.SAT_LINK_INVESTMENT_INVESTIA_UNIVERIS -- in dev
	create or replace TABLE DB_IAW_#env#_DWH.HOLDINGS_RDV.SAT_LINK_INVESTMENT_RR_IAS_NBIN -- in accp

	create or replace view DB_IAW_#env#_DWH.REVENUES_BDV.VW_INITIAL_LOADING_INVESTIA_REVENUE_PAYABLE_WT_LINK_REVENUE -- does not exist in accp
	create or replace view DB_IAW_#env#_DWH.REVENUES_BDV.VW_INITIAL_LOADING_INVESTIA_TRAILER_FEES_WT_LINK_REVENUE(
	create or replace view DB_IAW_#env#_DWH.REVENUES_BDV.VW_INITIAL_LOADING_INVESTIA_WRAP_FEES_WT_LINK_REVENUE(
	create or replace view DB_IAW_#env#_DWH.REVENUES_BDV.VW_INITIAL_LOADING_UNIVERIS_REVENUE_PAYABLE_WT_LINK_REVENUE_NEW
	create or replace view DB_IAW_#env#_DWH.REVENUES_BDV.VW_INITIAL_LOADING_UNIVERIS_REVENUE_PAYABLE_WT_LINK_REVENUE

create or replace view DB_IAW_#env#_DWH.REVENUES_BDV.VW_INITIAL_LOADING_WT_LINK_REVENUE(
	PLN_MNEM,
	MARKETPRODUCT_ID,
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	HK_HUB_PARTY_ROLE_ADVISOR,
	HK_HUB_CONTRACT,
	MD_START_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	MD_EXTRACT_DT,
	CLIENT_ID,
	CONTRACT_ID,
	ADVISOR_ID,
	MASTER_CODE,
	PAYMENT_DATE,
	REVENUE,
	REVENUE_TYPE,
	REVENUE_SUBTYPE,
	ENTRY_TYPE,
	STAMP,
	INSURANCE_REVENUE,
	TRANSID
) as
WITH EXCLUSION AS
(
SELECT
    R.REPID,
    S.IND_EXCLUDE,
    S.MD_ACTIVE
FROM STEWARDSHIP_RDV.REF_MANUAL_ADVISOR_RVP_IAS R                    
INNER JOIN STEWARDSHIP_RDV.SAT_REF_MANUAL_ADVISOR_RVP_IAS S
ON R.HK_HUB = S.HK_HUB
QUALIFY ROW_NUMBER() OVER (PARTITION BY R.REPID ORDER BY S.MD_START_DT DESC)=1  
),
LATEST_VERSION_CLIENT_CONTRACT AS (
	SELECT 
	LR.HK_LINK,
	VW_CC.HK_HUB_CONTRACT ,
	VW_CC.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	VW_CC.A_C_CLIENT, 
	COALESCE (VW_CC.MD_ACTIVE,'A') AS MD_ACTIVE,
	COALESCE (ROW_NUMBER() OVER (PARTITION BY LR.HK_LINK,VW_CC.HK_HUB_CONTRACT ORDER BY VW_CC.MD_START_DT DESC ),1) AS RANK_CLIENT_CONTRACT
	FROM REVENUES_RDV.LINK_REVENUE_RR_IAS_COMMISSION LR
	LEFT JOIN SHARED_BDV.VW_CLIENT_CONTRACT VW_CC 
	ON VW_CC.HK_HUB_CONTRACT = LR.HK_HUB_CONTRACT
	AND  VW_CC.MD_START_DT <= LR.MD_START_DT
)
SELECT 
	'-1' AS PLN_MNEM,
	'-1' AS MARKETPRODUCT_ID,
	VW_CC.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, 
	LR.HK_HUB_PARTY_ROLE_ADVISOR, 
	LR.HK_HUB_CONTRACT, 
	--DATEADD(DAY,1,LR.PROCESSDATE) AS MD_START_DT, 
	-- The Date has been generated as the TRUNC(STAMP) + 1 Day
	LR.MD_START_DT AS MD_START_DT, 
	LR.MD_SOURCE, 
	LR.MD_SRC_SYSTEM, 
	LR.MD_EXTRACT_DT, 
	VW_CC.A_C_CLIENT AS CLIENT_ID, 
	CAST(LR.ACCOUNTID AS VARCHAR(40)) AS CONTRACT_ID, 
	CAST(LR.ADVISOR_ID AS VARCHAR(50)) AS ADVISOR_ID, 
	LR.REPID AS MASTER_CODE, 
	LR.PROCESSDATE AS PAYMENT_DATE, 
	SUM(LR.COMMISSION) AS REVENUE, 
	CASE  WHEN LR.SOURCECODE = 'OFF' THEN 'Trade commissions'
		  WHEN LR.SOURCECODE = 'FXF' THEN 'Fee based/Managed' 
		  WHEN LR.SOURCECODE = 'MGD' THEN 'Fee based/Managed' 
		  WHEN LR.SOURCECODE = 'JRN' THEN 'Trailers' 
		  WHEN LR.SOURCECODE = 'MNL' THEN 'Trade commissions' 
		  WHEN LR.SOURCECODE = 'TRD' THEN 'Trade commissions' 
	ELSE 'Unkown' 
	END AS REVENUE_TYPE,
	CASE WHEN LR.SOURCECODE  = 'OFF' THEN 'OffBook commission' 
		 WHEN LR.SOURCECODE  = 'FXF' THEN 'Fixed fees' 
		 WHEN LR.SOURCECODE  = 'MGD' THEN 'Managed' 
		 WHEN LR.SOURCECODE  = 'JRN' THEN 'Trailer fees and GIC' 
		 WHEN LR.SOURCECODE  = 'MNL' THEN 'Others' 
		 WHEN LR.SOURCECODE  = 'TRD' THEN 'Trade commissions' 
	ELSE 'Unkown' 
	END AS REVENUE_SUBTYPE,
	LR.ENTRY_TYPE AS ENTRY_TYPE,
	LR.STAMP,
	0 AS INSURANCE_REVENUE,
	NULL AS TRANSID
FROM REVENUES_RDV.LINK_REVENUE_RR_IAS_COMMISSION LR
LEFT JOIN LATEST_VERSION_CLIENT_CONTRACT VW_CC 
	ON VW_CC.HK_HUB_CONTRACT = LR.HK_HUB_CONTRACT
	AND LR.HK_LINK = VW_CC.HK_LINK
	AND  VW_CC.MD_ACTIVE = 'A' AND VW_CC.RANK_CLIENT_CONTRACT = 1
LEFT JOIN EXCLUSION E 
    ON E.REPID = LR.REPID 
	AND E.IND_EXCLUDE = 1
	AND E.MD_ACTIVE = 'A'
WHERE (((((LR.SOURCECODE <> 'EXP') AND (LR.SOURCECODE <> 'TXR')) AND (LR.REPID <> 'SEAA')) AND (LR.REPID <> 'SEZ9')) AND (LR.REPID <> 'QYYY')
AND ( LR.ACCOUNTID NOT RLIKE '^[A-Z][A-Z].*' OR LR.ACCOUNTID IS NULL )
AND E.REPID IS NULL)
GROUP BY 
    HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, 
	HK_HUB_PARTY_ROLE_ADVISOR, 
	LR.HK_HUB_CONTRACT,
    LR.SOURCECODE,
	MD_START_DT, 
	MD_SOURCE, 
	MD_SRC_SYSTEM, 
	MD_EXTRACT_DT, 
	CLIENT_ID, 
	CONTRACT_ID, 
	ADVISOR_ID, 
	MASTER_CODE, 
	PAYMENT_DATE,
    LR.ENTRY_TYPE,
    LR.STAMP 
UNION 
 SELECT 
	'-1' AS PLN_MNEM,
	'-1' AS MARKETPRODUCT_ID,
	'0' AS HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, 
	LR.HK_HUB_REGISTERED_REPRESENTATIVE AS HK_HUB_PARTY_ROLE_ADVISOR, 
	'0' AS HK_HUB_CONTRACT, 
	LR.MD_START_DT AS MD_START_DT, 
	LR.MD_SOURCE, 
	LR.MD_SRC_SYSTEM, 
	LR.MD_EXTRACT_DT, 
	'-1' AS CLIENT_ID, 
	'-1' AS CONTRACT_ID, 
	LR.USERID AS ADVISOR_ID, 
	LR.REPID AS MASTER_CODE, 
	LR.PROCESSDATE AS PAYMENT_DATE, 
	0 AS REVENUE, 
	'Insurance' AS REVENUE_TYPE,
    'Insurance' AS REVENUE_SUBTYPE,
	LR.ENTRY_TYPE AS ENTRY_TYPE,
	LR.STAMP,
	SUM(COMMISSIONCAD) AS INSURANCE_REVENUE,
	LR.TRANSID
FROM REVENUES_RDV.LINK_INSURANCE_REVENUE_RR_IAS_COMMISSION LR
WHERE LR.SOURCECODE NOT IN ('EXP','TXR','SEAA','SEZ9','QYYY')
GROUP BY 
	HK_HUB_PARTY_ROLE_ADVISOR, 
	MD_START_DT,
	MD_SOURCE, 
	MD_SRC_SYSTEM, 
	MD_EXTRACT_DT,
	MASTER_CODE,
	ADVISOR_ID,
	PAYMENT_DATE,
	LR.SOURCECODE, 
    LR.ENTRY_TYPE,
    LR.STAMP,
    LR.TRANSID;



create or replace view DB_IAW_#env#_DWH.REVENUES_BDV.VW_REVENUE_IAS_COMMISSION(
	HK_LINK,
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	HK_HUB_PARTY_ROLE_ADVISOR,
	HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES,
	HK_HUB_INVESTMENT_PRODUCT_TYPE,
	HK_HUB_CONTRACT,
	MD_START_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	MD_EXTRACT_DT,
	CLIENT_ID,
	MASTER_CODE,
	CONTRACT_ID,
	ADVISOR_ID,
	PLN_MNEM,
	MARKETPRODUCT_ID,
	PAYMENT_DATE,
	REVENUE,
	REVENUE_TYPE,
	REVENUE_SUBTYPE,
	AUA,
	ENTRY_TYPE,
	STAMP,
	INSURANCE_REVENUE,
	TRANSID
) as WITH EXCLUSION AS (
SELECT
	R.REPID,
	S.IND_EXCLUDE,
	S.MD_ACTIVE
FROM
	STEWARDSHIP_RDV.REF_MANUAL_ADVISOR_RVP_IAS R
INNER JOIN STEWARDSHIP_RDV.SAT_REF_MANUAL_ADVISOR_RVP_IAS S ON
	R.HK_HUB = S.HK_HUB QUALIFY ROW_NUMBER() OVER (PARTITION BY R.REPID
ORDER BY
	S.MD_START_DT DESC)= 1 )

SELECT
	R.HK_LINK,
	R.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	R.HK_HUB_PARTY_ROLE_ADVISOR,
	R.HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES,
	R.HK_HUB_INVESTMENT_PRODUCT_TYPE,
	R.HK_HUB_CONTRACT,
	R.MD_START_DT,
	R.MD_SOURCE,
	R.MD_SRC_SYSTEM,
	R.MD_EXTRACT_DT,
	R.CLIENT_ID,
	R.MASTER_CODE,
	R.CONTRACT_ID,
	R.ADVISOR_ID,
	R.PLN_MNEM,
	R.MARKETPRODUCT_ID,
	R.PAYMENT_DATE,
	R.REVENUE,
	R.REVENUE_TYPE,
	R.REVENUE_SUBTYPE,
	R.AUA,
	R.ENTRY_TYPE,
	R.STAMP,
	R.INSURANCE_REVENUE,
	R.TRANSID
FROM
	REVENUES_BDV.WT_LINK_REVENUE R
LEFT JOIN EXCLUSION E ON

	E.REPID = R.MASTER_CODE
	AND E.IND_EXCLUDE = 1
	AND E.MD_ACTIVE = 'A'
WHERE
	R.MD_SRC_SYSTEM = 'IAS-COMMISSION'
	AND ( R.CONTRACT_ID NOT RLIKE '^[A-Z][A-Z].*'
		OR R.CONTRACT_ID IS NULL )
	AND E.REPID IS NULL;
create or replace view DB_IAW_#env#_DWH.REVENUES_BDV.VW_REVENUE_IAS_UNIVERIS(
	HK_LINK,
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	HK_HUB_PARTY_ROLE_ADVISOR,
	HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES,
	HK_HUB_INVESTMENT_PRODUCT_TYPE,
	HK_HUB_CONTRACT,
	MD_START_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	MD_EXTRACT_DT,
	CLIENT_ID,
	MASTER_CODE,
	CONTRACT_ID,
	ADVISOR_ID,
	PLN_MNEM,
	MARKETPRODUCT_ID,
	PAYMENT_DATE,
	REVENUE,
	REVENUE_TYPE,
	REVENUE_SUBTYPE,
	AUA,
	PLN_SYSID
) as 
SELECT 
	R.HK_LINK, 
	R.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, 
	R.HK_HUB_PARTY_ROLE_ADVISOR, 
	R.HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES, 
	R.HK_HUB_INVESTMENT_PRODUCT_TYPE, 
	R.HK_HUB_CONTRACT, 
	R.MD_START_DT, 
	R.MD_SOURCE, 
	R.MD_SRC_SYSTEM, 
	R.MD_EXTRACT_DT, 
	R.CLIENT_ID, 
	R.MASTER_CODE,
	R.CONTRACT_ID, 
	R.ADVISOR_ID, 
	R.PLN_MNEM, 
	R.MARKETPRODUCT_ID, 
	R.PAYMENT_DATE, 
	R.REVENUE, 
	R.REVENUE_TYPE, 
	R.REVENUE_SUBTYPE, 
	R.AUA,
	R.PLN_SYSID
FROM REVENUES_BDV.WT_LINK_REVENUE R
WHERE R.MD_SRC_SYSTEM = 'IAS-UNIVERIS';


--does not exist
create or replace view DB_IAW_#env#_DWH.REVENUES_RDV.VW_REVENUE_IAS_COMMISSION(
	HK_LINK,
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	HK_HUB_PARTY_ROLE_ADVISOR,
	HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES,
	HK_HUB_INVESTMENT_PRODUCT_TYPE,
	HK_HUB_CONTRACT,
	MD_START_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	MD_EXTRACT_DT,
	CLIENT_ID,
	MASTER_CODE,
	CONTRACT_ID,
	ADVISOR_ID,
	PLN_MNEM,
	MARKETPRODUCT_ID,
	PAYMENT_DATE,
	REVENUE,
	REVENUE_TYPE,
	REVENUE_SUBTYPE,
	AUA
) as 
WITH EXCLUSION AS
(
SELECT
    R.REPID,
    S.IND_EXCLUDE,
    S.MD_ACTIVE
FROM STEWARDSHIP_RDV.REF_MANUAL_ADVISOR_RVP_IAS R                    
INNER JOIN STEWARDSHIP_RDV.SAT_REF_MANUAL_ADVISOR_RVP_IAS S
ON R.HK_HUB = S.HK_HUB
QUALIFY ROW_NUMBER() OVER (PARTITION BY R.REPID ORDER BY S.MD_START_DT DESC)=1  
)
SELECT 
	R.HK_LINK, 
	R.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, 
	R.HK_HUB_PARTY_ROLE_ADVISOR, 
	R.HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES, 
	R.HK_HUB_INVESTMENT_PRODUCT_TYPE, 
	R.HK_HUB_CONTRACT, 
	R.MD_START_DT, 
	R.MD_SOURCE, 
	R.MD_SRC_SYSTEM, 
	R.MD_EXTRACT_DT, 
	R.CLIENT_ID, 
	R.MASTER_CODE,
	R.CONTRACT_ID, 
	R.ADVISOR_ID, 
	R.PLN_MNEM, 
	R.MARKETPRODUCT_ID, 
	R.PAYMENT_DATE, 
	R.REVENUE, 
	R.REVENUE_TYPE, 
	R.REVENUE_SUBTYPE, 
	R.AUA
FROM REVENUES_BDV.WT_LINK_REVENUE R
LEFT JOIN EXCLUSION E 
ON E.REPID = R.MASTER_CODE AND E.IND_EXCLUDE = 1 AND E.MD_ACTIVE = 'A'
WHERE R.MD_SRC_SYSTEM = 'IAS-COMMISSION'
AND ( R.CONTRACT_ID NOT RLIKE '^[A-Z][A-Z].*' OR R.CONTRACT_ID IS NULL )
AND E.REPID IS NULL;
-- validate this DDL:
create or replace TABLE DB_IAW_#env#_DWH.SHARED_BDV.LINK_INVESTMENT_CONTRACT
--
alter table DB_IAW_#env#_DWH.SHARED_BDV.LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE
rename to DB_IAW_#env#_DWH.SHARED_BDV.LINK_PARTY_RELATIONSHIP_SHARE;

create or replace TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE

create or replace TABLE DB_IAW_#env#_DWH.SHARED_BDV.REF_KPI_TARGET_RVP (
	HK_HUB VARCHAR(40) COMMENT 'HASH KEY FOR THE HUB',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'CREATION DATE TIME OF THE OCCURRENCE',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'TASK EXECUTION ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'REPRESENTS THE SOURCE SYSTEM, FILE, ETC. OF THE INSTANCE',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'SOURCE SYSTEM',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'SOURCE EXTRACTION DATE',
	KPI_DATE TIMESTAMP_NTZ(9) COMMENT 'THE END OF EVERY MONTH''S DATE FOR THE SET TARGET',
	METRIC_NAME VARCHAR(100) COMMENT 'THE METRIC NAME DESCRIPTION',
	RVP VARCHAR(100) COMMENT 'THE REGRIONAL VICE PRESIDENT''S NAME'
);

create or replace TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_REF_KPI_TARGET_RVP_IAPW (
	HK_HUB VARCHAR(40) COMMENT 'HASH KEY FOR THE SATELLITE',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'START DATE OF THE IMAGE/VERSION',
	MD_HASHDIFF VARCHAR(40) COMMENT 'REPRESENTS THE WHOLE SET OF HASHED ATTRIBUTES TO BE HISTORIZED FOR AN OCCURRENCE',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'CREATION DATE TIME OF THE OCCURRENCE',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'TASK EXECUTION ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'REPRESENTS THE SOURCE SYSTEM, FILE, ETC. OF THE INSTANCE',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'SOURCE SYSTEM',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'SOURCE EXTRACTION DATE',
	MD_ACTIVE VARCHAR(1) COMMENT 'ACTIVE FLAG, \"A\" ROW EXISTS IN THE SOURCE, \"D\" ROW DOES NOT EXIST IN THE SOURCE',
	TARGET NUMBER(36,2) COMMENT 'THE TARGET METRIC VALUE'
);

-- was transient table / was MD_HASHDIFF VARCHAR(40)
create or replace TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_INVESTMENT_CONTRACT_IAS_NBIN (
	HK_LINK VARCHAR(40) COMMENT 'Hash key for the Link',
	HK_HUB_CONTRACT VARCHAR(40) COMMENT 'Hash key for HUB_CONTRACT',
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER VARCHAR(40) COMMENT 'Hash key for HUB_PARTY_ROLE_ACCOUNT_HOLDER',
	HK_HUB_PARTY_ROLE_ADVISOR VARCHAR(40) COMMENT 'Hash key for HUB_PARTY_ROLE_ADVISOR',
	HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES VARCHAR(40) COMMENT 'Hash key for REF_INVESTMENT_SAVING_PROGRAM_TYPES',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_HASHDIFF VARCHAR(64) COMMENT 'Represents the whole set of hashed attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	CONTRACT_ID VARCHAR(18) COMMENT 'Account ID',
	CLIENT_ID VARCHAR(100) COMMENT 'Client ID',
	MASTER_CD VARCHAR(50) COMMENT 'MASTER CODE of the advisor',
	UNIVERIS_PLAN_ID NUMBER(38,0) COMMENT 'Univeris Plan ID',
	PLN_MNEM VARCHAR(512) COMMENT 'Plan code',
	ACCOUNT_RAP_CODE VARCHAR(10) COMMENT 'To be defined : Last letter of an account ID',
	RETAIL_PLAN VARCHAR(50) COMMENT 'Retail plan code : RS, LF, ...',
	ASC_1_RESP_PLAN_TYPES VARCHAR(10) COMMENT 'subtype of the RESP plans'
);
-- should this table be dropped
-- TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_IAS_NBIN_SAT_REF_INVESTMENT_SAVING_PROGRAM_TYPES_COMPUTE (
--should this table be dropped it does not exist in DEV
-- TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE

alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE
add column
ACCOUNT_AUA_SEGMENT VARCHAR(1000) COMMENT 'Represents the segmentation of advisors based on their AUA',
ACCOUNT_AUA_SEGMENT_ORDER NUMBER(38,0) COMMENT 'Order of the AUA segmentation, this field is done for Power BI display';

alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE
rename to DB_IAW_#env#_DWH.SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_SHARE;

alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE
rename to TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_SHARE;

alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE_MC
add column
	COMMISSIONPCT_ADVISOR NUMBER(6,3) COMMENT 'Advisor Commission PCT',
	COMMISSIONPCT_FINANCIAL NUMBER(6,3) COMMENT 'Financial Commission PCT',
	NETCOMMISSIONPCT_ADVISOR NUMBER(6,3) COMMENT 'Advisor Net Commission PCT',
	NETCOMMISSIONPCT_FINANCIAL NUMBER(6,3) COMMENT 'Financial Net Commission PCT',
	ADVISOR_ROLE VARCHAR(100) COMMENT 'Advisor Role'
;

create or replace view DB_IAW_#env#_DWH.SHARED_BDV.VW_CLIENT_CONTRACT(
	HK_HUB_CONTRACT,
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	A_C_CLIENT,
	MD_START_DT,
	MD_ACTIVE
) as 
SELECT  DISTINCT 
HC.HK_HUB AS HK_HUB_CONTRACT
,SHA1(UPPER(CONCAT(COALESCE(TRIM(HC.MD_SRC_SYSTEM), '#NULL#'), '|' , COALESCE(TRIM(SC.A_C_CLIENT), '#NULL#')))) AS HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER
,A_C_CLIENT
,SC.MD_START_DT 
,SC.MD_ACTIVE 
FROM SHARED_RDV.HUB_CONTRACT HC 
INNER JOIN SHARED_RDV.SAT_CONTRACT_IAS_NBIN SC 
	ON HC.HK_HUB = SC.HK_HUB 
WHERE 
	A_C_CLIENT NOT  RLIKE '^[A-Z][A-Z].*' 
	AND A_C_CLIENT IS NOT NULL;
create or replace view DB_IAW_#env#_DWH.SHARED_BDV.VW_EXCHANGE_RATE(
	HK_LINK,
	MD_START_DT,
	MD_CREATION_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	MD_CREATION_AUDIT_ID,
	MD_EXTRACT_DT,
	EXCHANGE_DATE,
	EXCHANGERATE,
	REVNO
) as
SELECT 
SHA1(UPPER(CONCAT(COALESCE(TRIM('IAS'), '#NULL#'), '|' , COALESCE(TRIM(TO_VARCHAR(EXCHANGE_DATE)), '#NULL#')))) AS HK_LINK,
NVL(MD_START_DT, LAG(MD_START_DT) IGNORE NULLS OVER (ORDER BY EXCHANGE_DATE)) AS MD_START_DT, 
NVL(MD_CREATION_DT, LAG(MD_CREATION_DT) IGNORE NULLS OVER (ORDER BY EXCHANGE_DATE)) AS MD_CREATION_DT,
NVL(MD_SOURCE, LAG(MD_SOURCE) IGNORE NULLS OVER (ORDER BY EXCHANGE_DATE)) AS MD_SOURCE,
NVL(MD_SRC_SYSTEM, LAG(MD_SRC_SYSTEM) IGNORE NULLS OVER (ORDER BY EXCHANGE_DATE)) AS MD_SRC_SYSTEM,
NVL(MD_CREATION_AUDIT_ID, LAG(MD_CREATION_AUDIT_ID) IGNORE NULLS OVER (ORDER BY EXCHANGE_DATE)) AS MD_CREATION_AUDIT_ID,
NVL(MD_EXTRACT_DT, LAG(MD_EXTRACT_DT) IGNORE NULLS OVER (ORDER BY EXCHANGE_DATE)) AS MD_EXTRACT_DT, 
EXCHANGE_DATE,
NVL(EXCHANGERATE, LAG(EXCHANGERATE) IGNORE NULLS OVER (ORDER BY EXCHANGE_DATE)) AS EXCHANGERATE, 
NVL(REVNO, LAG(REVNO) IGNORE NULLS OVER (ORDER BY EXCHANGE_DATE)) AS REVNO
FROM
(SELECT D."DATE" AS EXCHANGE_DATE,E.EXCHANGERATE,HK_LINK, MD_START_DT, MD_CREATION_DT, MD_SOURCE, MD_SRC_SYSTEM, MD_CREATION_AUDIT_ID, MD_EXTRACT_DT, REVNO
FROM DB_IAW_#env#_DWH.STEWARDSHIP_RDV.REF_DATE D
LEFT OUTER JOIN DB_IAW_#env#_DWH.SHARED_RDV.TRANSLINK_EXCHANGE_RATE E 
ON D."DATE"=E.EXCHANGE_DATE 
WHERE D."DATE" BETWEEN (SELECT MIN(EXCHANGE_DATE) FROM DB_IAW_#env#_DWH.SHARED_RDV.TRANSLINK_EXCHANGE_RATE) AND (SELECT MAX(EXCHANGE_DATE) FROM DB_IAW_#env#_DWH.SHARED_RDV.TRANSLINK_EXCHANGE_RATE)
ORDER BY D."DATE") E;
create or replace view DB_IAW_#env#_DWH.SHARED_BDV.VW_IAS_RRCODE_MASTERCODE_TRANS(
	A_C_REPRESENTATIVE,
	COMMISSIONPCT,
	TOREPID,
	MASTER_CODE,
	PHYSICAL,
	COM_TYPE,
	IS_RESHARED,
	MD_START_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	MD_EXTRACT_DT,
	ADVISOR_ROLE
) as
/* Advisors from commission portal : All active users of the portal */
WITH ADV AS 
(
	SELECT DISTINCT TRIM(RM.MAINREPCODE) AS MAINREPCODE, RM.FIRSTNAME, RM.LASTNAME
	FROM SHARED_BDV.WT_REGISTERED_REPRESENTATIVE rm 
	WHERE rm.ACTIVE = 1 
	ORDER BY MAINREPCODE, RM.FIRSTNAME, RM.LASTNAME 
),
/* Only active shares of commissions */
LV_SHARE AS 
(
	SELECT * FROM SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE_MC R
	-- WHERE SHARETYPE <> 'noreference' AND SHARETYPE <> 'option' AND (FROMREPID <> 'SBEP' OR SHARETYPE <> 'override') -- Same filter available in IAS mapping (Pradeep)
),
/* Case 1 : RR code share with a master code of an advisor */
FROM_RR_TO_MAIN AS
(
	SELECT DISTINCT TRIM(s.FROMREPID) AS FROMREPID, s.COMMISSIONPCT, TRIM(s.TOREPID) AS TOREPID, 
	TRIM(ADV_to.MAINREPCODE) AS MASTER_CODE, 1 AS PHYSICAL, 'FROM_RR_TO_MAIN' AS COM_TYPE, 0 AS IS_RESHARED, s.MD_START_DT ,s.MD_SOURCE ,s.MD_EXTRACT_DT, COALESCE(s.ADVISOR_ROLE,'-1') AS ADVISOR_ROLE
	FROM LV_SHARE s 
	LEFT JOIN ADV ADV_to
	ON TRIM(s.TOREPID) = TRIM(ADV_to.MAINREPCODE)
	WHERE ADV_to.MAINREPCODE IS NOT NULL --AND s.COMMISSIONPCT > 0
	ORDER BY FROMREPID
),
/* Case 2 : RR code share with RR code that has a master code */
FROM_RR_TO_RR_TO_MAIN AS
(
	SELECT DISTINCT TRIM(s.FROMREPID) AS FROMREPID, s.COMMISSIONPCT, TRIM(s.TOREPID) AS TOREPID, 
  TRIM(rr.MAINREPCODE) AS MASTER_CODE, 1 AS PHYSICAL, 'FROM_RR_TO_RR_TO_MAIN' AS COM_TYPE, 0 AS IS_RESHARED, s.MD_START_DT,s.MD_SOURCE ,s.MD_EXTRACT_DT, COALESCE(s.ADVISOR_ROLE,'-1') AS ADVISOR_ROLE
	FROM LV_SHARE s 
	LEFT JOIN FROM_RR_TO_MAIN
	ON FROM_RR_TO_MAIN.FROMREPID = TRIM(s.FROMREPID) AND FROM_RR_TO_MAIN.TOREPID = TRIM(s.TOREPID) 	
	LEFT JOIN SHARED_BDV.WT_REGISTERED_REPRESENTATIVE rr 
	ON TRIM(rr.RR_CD) = TRIM(s.TOREPID) AND rr.ACTIVE=1 AND TRIM(rr.RR_CD) = TRIM(rr.MAINREPCODE)
	WHERE FROM_RR_TO_MAIN.FROMREPID IS NULL /*AND s.COMMISSIONPCT > 0*/ AND rr.MAINREPCODE IS NOT NULL
	ORDER BY FROMREPID
),
/* RR code share with an RR code that is not linked to a main rep code */
OTHER AS
(
	SELECT DISTINCT TRIM(s.FROMREPID) AS FROMREPID, s.COMMISSIONPCT, TRIM(s.TOREPID) AS TOREPID, 
  TRIM(s.TOREPID) AS MASTER_CODE, 0 AS PHYSICAL, 'OTHER' AS COM_TYPE, 0 AS IS_RESHARED, s.MD_START_DT,s.MD_SOURCE ,s.MD_EXTRACT_DT, COALESCE(s.ADVISOR_ROLE,'-1')  AS ADVISOR_ROLE
	FROM LV_SHARE s 
	LEFT JOIN FROM_RR_TO_MAIN
	ON FROM_RR_TO_MAIN.FROMREPID = TRIM(s.FROMREPID) AND FROM_RR_TO_MAIN.TOREPID = TRIM(s.TOREPID) 
	LEFT JOIN FROM_RR_TO_RR_TO_MAIN
	ON FROM_RR_TO_RR_TO_MAIN.FROMREPID = TRIM(s.FROMREPID) AND FROM_RR_TO_RR_TO_MAIN.TOREPID = TRIM(s.TOREPID)
	WHERE /*s.COMMISSIONPCT > 0 AND*/ FROM_RR_TO_MAIN.FROMREPID IS NULL AND  FROM_RR_TO_RR_TO_MAIN.FROMREPID IS NULL 
	ORDER BY FROMREPID
),
AV_ALL AS
(
	SELECT T.A_C_REPRESENTATIVE, T.COMMISSIONPCT, T.TOREPID, T.MASTER_CODE, T.PHYSICAL, T.COM_TYPE, T.IS_RESHARED, T.MD_START_DT, T.MD_SOURCE,'IAS' AS MD_SRC_SYSTEM ,T.MD_EXTRACT_DT,T.ADVISOR_ROLE
 	FROM 
	(
		SELECT FROMREPID AS A_C_REPRESENTATIVE, COMMISSIONPCT, TOREPID, MASTER_CODE, PHYSICAL, COM_TYPE, IS_RESHARED,MD_START_DT,MD_SOURCE,MD_EXTRACT_DT,ADVISOR_ROLE
		FROM FROM_RR_TO_MAIN
		WHERE MASTER_CODE IS NOT NULL
		
		UNION ALL
		
		SELECT FROMREPID AS A_C_REPRESENTATIVE, COMMISSIONPCT, TOREPID, MASTER_CODE, PHYSICAL, COM_TYPE, IS_RESHARED,MD_START_DT,MD_SOURCE,MD_EXTRACT_DT,ADVISOR_ROLE
		FROM FROM_RR_TO_RR_TO_MAIN
		WHERE MASTER_CODE IS NOT NULL
		
		UNION ALL
		
		SELECT FROMREPID AS A_C_REPRESENTATIVE, COMMISSIONPCT, TOREPID, MASTER_CODE, PHYSICAL, COM_TYPE, IS_RESHARED,MD_START_DT,MD_SOURCE,MD_EXTRACT_DT,ADVISOR_ROLE
		FROM OTHER
		WHERE MASTER_CODE IS NOT NULL
	) AS T
)
SELECT *
FROM AV_ALL
ORDER BY A_C_REPRESENTATIVE;


--to be dropped
drop TABLE DB_IAW_#env#_DWH.REVENUES_RDV.LINK_REVENUE_RR_IAS_COMMISSION_CLONE

--dought
VW_CLIENT_CONTRACT