--Modification on DEV
-- to be modified
create or replace TABLE DB_IAW_#env#_DM.HOLDINGS.FACT_HOLDINGS (
	ID NUMBER(38,0) autoincrement COMMENT 'ID of fact holdings',
	HK_LINK VARCHAR(40) COMMENT 'Hash key for the Link',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	SK_DIM_ACCOUNTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_ACCOUNTS',
	SK_DIM_MARKETPRODUCTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_MARKETPRODUCTS',
	SK_DIM_ADVISORS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_ADVISORS',
	SK_DIM_CLIENTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_CLIENTS',
	SK_DIM_PLANS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_PLANS',
	RR_CD VARCHAR(50) COMMENT 'Advisor RR code',
	PLN_SYSID VARCHAR(1000) COMMENT 'UNIVERIS Plan system Identifier',
	BALANCE_DATE TIMESTAMP_NTZ(9) COMMENT 'BALANCE DATE',
	HOLDING_VALUE NUMBER(38,9) COMMENT 'HOLDING Value',
	AUA NUMBER(38,12) COMMENT 'AUA Value',
	AUM NUMBER(38,12) COMMENT 'AUM Value',
	AUM_CLARINGTON NUMBER(38,12) COMMENT 'AUA CLARINGTON Value',
	AUM_IA NUMBER(38,12) COMMENT 'AUA IA Value',
	CASH_POSITION NUMBER(38,12) COMMENT 'CASH POSITION Value',
	PROGRAM_TYPE VARCHAR(50) COMMENT 'PROGRAM TYPE',
	ACCOUNT_PROGRAM_TYPE VARCHAR(50) COMMENT 'ACCOUNT PROGRAM TYPE',
	ADMINISTRATORY_TYPE VARCHAR(1000) COMMENT 'ADMINISTRATORY TYPE',
	AUA_ACCRUED_INTEREST NUMBER(38,2)
);

create or replace TABLE DB_IAW_#env#_DM.HOLDINGS.WT_FACT_HOLDINGS (
	HK_LINK VARCHAR(40) COMMENT 'Hash key for the Link',
	HK_HUB_CONTRACT VARCHAR(40) COMMENT 'Hash key for CONTRACT',
	HK_HUB_INVESTMENT_PRODUCT_TYPE VARCHAR(40) COMMENT 'Hash key for the REF_MAPPING_PRODUCT_TYPE',
	HK_HUB_PARTY_ROLE_ADVISOR VARCHAR(40) COMMENT 'Hash key for the HUB_PARTY_ROLE_ADVISOR',
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER VARCHAR(40) COMMENT 'Hash key for HUB_PARTY_ROLE_ACCOUNT_HOLDER',
	HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES VARCHAR(40) COMMENT 'Hash key for the REF_INVESTMENT_SAVING_PROGRAM_TYPES',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	SK_DIM_ACCOUNTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_ACCOUNTS',
	SK_DIM_MARKETPRODUCTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_MARKETPRODUCTS',
	SK_DIM_ADVISORS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_ADVISORS',
	SK_DIM_CLIENTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_CLIENTS',
	SK_DIM_PLANS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_PLANS',
	RR_CD VARCHAR(50) COMMENT 'Advisor RR code',
	PLN_SYSID VARCHAR(1000) COMMENT 'UNIVERIS Plan System Identifier',
	BALANCE_DATE TIMESTAMP_NTZ(9) COMMENT 'BALANCE DATE',
	HOLDING_VALUE NUMBER(38,9) COMMENT 'HOLDING Value',
	AUA NUMBER(38,12) COMMENT 'AUA Value',
	AUM NUMBER(38,12) COMMENT 'AUM Value',
	AUM_CLARINGTON NUMBER(38,12) COMMENT 'AUA CLARINGTON Value',
	AUM_IA NUMBER(38,12) COMMENT 'AUA IA Value',
	CASH_POSITION NUMBER(38,12) COMMENT 'CASH POSITION Value',
	PROGRAM_TYPE VARCHAR(50) COMMENT 'PROGRAM TYPE',
	ACCOUNT_PROGRAM_TYPE VARCHAR(50) COMMENT 'ACCOUNT PROGRAM TYPE',
	ADMINISTRATORY_TYPE VARCHAR(1000) COMMENT 'ADMINISTRATORY TYPE',
	AUA_ACCRUED_INTEREST NUMBER(38,2)
);

CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DM.HOLDINGS.SP_CONV_LOADDM_DM_WT_TO_DM_DIM_FACT_REVENUES_INSERT("ENV" VARCHAR(1000), "JOB_NAME" VARCHAR(16777216), "JOB_AUDIT_ID" VARCHAR(16777216), "RUN_ID" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
DECLARE
INS_QUERY STRING;
BEGIN
INS_QUERY = "INSERT INTO DB_IAW_"+ENV+"_DM.REVENUES.FACT_REVENUE(
HK_LINK,
MD_START_DT,
MD_CREATION_DT,
MD_CREATION_AUDIT_ID,
MD_SOURCE,
MD_SRC_SYSTEM,
MD_EXTRACT_DT,
MD_SECURITY_TYPE,
SK_DIM_CLIENTS,
SK_DIM_ADVISORS,
SK_DIM_PLANS,
SK_DIM_MARKETPRODUCTS,
SK_DIM_ACCOUNTS,
PAYMENT_DATE,
REVENUE_AMOUNT,
REVENUE_TYPE,
REVENUE_SUBTYPE,
AUA)
VALUES(
SELECT 
M.HK_LINK, 
M.MD_START_DT, 
CURRENT_TIMESTAMP(), 
CONCAT("+JOB_AUDIT_ID+",''#'',"+JOB_NAME+","+RUN_ID+"),
M.MD_SOURCE,
M.MD_SRC_SYSTEM,
M.MD_EXTRACT_DT,
M.MD_SECURITY_TYPE,
M.SK_DIM_CLIENTS,
M.SK_DIM_ADVISORS,
M.SK_DIM_PLANS,
M.SK_DIM_MARKETPRODUCTS,
M.SK_DIM_ACCOUNTS,
M.PAYMENT_DATE,
M.REVENUE_AMOUNT,
M.REVENUE_TYPE,
M.REVENUE_SUBTYPE,
M.AUA
FROM DB_IAW_"+ENV+"_DM.REVENUES.WT_FACT_REVENUE M
RIGHT OUTER JOIN DB_IAW_"+ENV+"_DM.REVENUES.FACT_REVENUE D
ON M.HK_LINK = D.HK_LINK
WHERE D.HK_LINK IS NULL);";

EXECUTE IMMEDIATE :INS_QUERY;
END
';

create or replace view DB_IAW_#env#_DM.HOLDINGS.VW_FACT_HOLDINGS(
	MD_START_DT,
	MD_SRCSYSTEM,
	SK_DIM_ACCOUNTS,
	SK_DIM_MARKETPRODUCTS,
	"Rep code",
	SK_DIM_ADVISORS,
	SK_DIM_CLIENTS,
	PLN_SYSID,
	SK_DIM_PLANS,
	"Balance date",
	"Market value",
	AUA,
	AUM,
	"AUM Clarington",
	"AUM iA",
	"Cash position",
	"Program type",
	"Account program type",
	"Administratory type",
	AUA_ACCRUED_INTEREST
) as 
	SELECT 
	MD_START_DT ,
	MD_SRC_SYSTEM ,
	SK_DIM_ACCOUNTS ,
	SK_DIM_MARKETPRODUCTS ,
	RR_CD ,
	SK_DIM_ADVISORS,
	SK_DIM_CLIENTS,
	PLN_SYSID ,
	SK_DIM_PLANS,
	BALANCE_DATE ,
	HOLDING_VALUE ,
	AUA ,
	AUM ,
	AUM_CLARINGTON ,
	AUM_IA ,
	CASH_POSITION ,
	PROGRAM_TYPE ,
	ACCOUNT_PROGRAM_TYPE ,
	ADMINISTRATORY_TYPE,
AUA_ACCRUED_INTEREST	
	FROM DB_IAW_#env#_DM.HOLDINGS.FACT_HOLDINGS
	WHERE DATE(BALANCE_DATE) >= (SELECT DATE(DATEADD(MONTH, -1,MAX(BALANCE_DATE) ))  FROM HOLDINGS.FACT_HOLDINGS);

CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DM.HOLDINGS.SP_CONV_LOADDM_DM_WT_TO_DM_FACT_HOLDINGS_INSERT("ENV" VARCHAR(1000), "JOB_NAME" VARCHAR(16777216), "JOB_AUDIT_ID" VARCHAR(16777216), "DATA_START_DATE" VARCHAR(10), "RUN_ID" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
DECLARE
INS_QUERY STRING;
BEGIN
INS_QUERY = "INSERT INTO DB_IAW_"+ENV+"_DM.HOLDINGS.FACT_HOLDINGS(
HK_LINK,
MD_START_DT,
MD_CREATION_DT,
MD_CREATION_AUDIT_ID,
MD_SOURCE,
MD_SRC_SYSTEM,
MD_EXTRACT_DT,
MD_SECURITY_TYPE,
SK_DIM_ACCOUNTS,
SK_DIM_MARKETPRODUCTS,
SK_DIM_ADVISORS,
SK_DIM_CLIENTS,
SK_DIM_PLANS,
RR_CD,
PLN_SYSID,
BALANCE_DATE,
HOLDING_VALUE,
AUA,
AUM,
AUM_CLARINGTON,
AUM_IA,
CASH_POSITION,
PROGRAM_TYPE,
ACCOUNT_PROGRAM_TYPE,
ADMINISTRATORY_TYPE)
VALUES(
SELECT 
M.HK_LINK, 
TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD''), 
CURRENT_TIMESTAMP(), 
CONCAT("+JOB_AUDIT_ID+",''#'',"+JOB_NAME+","+RUN_ID+"),
M.MD_SOURCE,
M.MD_SRC_SYSTEM,
M.MD_EXTRACT_DT,
M.MD_SECURITY_TYPE,
M.SK_DIM_ACCOUNTS,
M.SK_DIM_MARKETPRODUCTS,
M.SK_DIM_ADVISORS,
M.SK_DIM_CLIENTS,
M.SK_DIM_PLANS,
M.RR_CD,
M.PLN_SYSID,
M.BALANCE_DATE,
M.HOLDING_VALUE,
M.AUA,
M.AUM,
M.AUM_CLARINGTON,
M.AUM_IA,
M.CASH_POSITION,
M.PROGRAM_TYPE,
M.ACCOUNT_PROGRAM_TYPE,
M.ADMINISTRATORY_TYPE
FROM DB_IAW_"+ENV+"_DM.HOLDINGS.WT_FACT_HOLDINGS M
RIGHT OUTER JOIN DB_IAW_"+ENV+"_DM.HOLDINGS.FACT_HOLDINGS D
ON M.HK_LINK = D.HK_LINK
WHERE D.HK_LINK IS NULL);";
EXECUTE IMMEDIATE :INS_QUERY;
END
';

create or replace TABLE DB_IAW_#env#_DM.REVENUES.FACT_REVENUE (
	ID NUMBER(38,0) autoincrement COMMENT 'Surrogate key of the dimension',
	HK_LINK VARCHAR(40) COMMENT 'Hash key for the Link',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	SK_DIM_CLIENTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_CLIENTS',
	SK_DIM_ADVISORS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_ADVISORS',
	SK_DIM_PLANS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_PLANS',
	SK_DIM_MARKETPRODUCTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_MARKETPRODUCTS',
	SK_DIM_ACCOUNTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_ACCOUNTS',
	PAYMENT_DATE TIMESTAMP_NTZ(9) COMMENT 'PAYMENT Date',
	REVENUE_AMOUNT NUMBER(38,12) COMMENT 'REVENUE AMOUNT',
	REVENUE_TYPE VARCHAR(512) COMMENT 'REVENUE TYPE',
	REVENUE_SUBTYPE VARCHAR(512) COMMENT 'REVENUE SUBTYPE',
	AUA NUMBER(38,12) COMMENT 'AUA Value',
	INSURANCE_REVENUE NUMBER(38,12) COMMENT 'Insurance Revenues'
);

create or replace TABLE DB_IAW_#env#_DM.REVENUES.WT_FACT_REVENUE (
	HK_LINK VARCHAR(40) COMMENT 'Hash key for the Link',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER VARCHAR(40) COMMENT 'Hash key HUB_PARTY_ROLE_ACCOUNT_HOLDER',
	HK_HUB_PARTY_ROLE_ADVISOR VARCHAR(40) COMMENT 'Hash key for HUB_REGISTERED_REPRESENTATIVE_COMMISSION',
	HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES VARCHAR(40) COMMENT 'Hash key for REF_INVESTMENT_SAVING_PROGRAM_TYPES',
	HK_HUB_INVESTMENT_PRODUCT_TYPE VARCHAR(40) COMMENT 'Hash key for REF_MAPPING_PRODUCT_TYPE',
	HK_HUB_CONTRACT VARCHAR(40) COMMENT 'Hash key for HUB_CONTRACT',
	SK_DIM_CLIENTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_CLIENTS',
	SK_DIM_ADVISORS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_ADVISORS',
	SK_DIM_PLANS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_PLANS',
	SK_DIM_MARKETPRODUCTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_MARKETPRODUCTS',
	SK_DIM_ACCOUNTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_ACCOUNTS',
	PAYMENT_DATE TIMESTAMP_NTZ(9) COMMENT 'Process Date',
	REVENUE_AMOUNT NUMBER(38,12) COMMENT 'REVENUE AMOUNT',
	REVENUE_TYPE VARCHAR(512) COMMENT 'REVENUE TYPE',
	REVENUE_SUBTYPE VARCHAR(512) COMMENT 'REVENUE SUBTYPE',
	AUA NUMBER(38,12) COMMENT 'AUA Value',
	INSURANCE_REVENUE NUMBER(38,12) COMMENT 'Insurance Revenues'
);

CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DM.REVENUES.SP_CONV_LOADDM_BDV_HOLDINGS_TO_DM_WT_FACT_HOLDINGS("ENV" VARCHAR(1000), "DATA_START_DATE" VARCHAR(10))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
DECLARE
TRUNC_QUERY STRING;
INS_QUERY STRING;
UPD_QUERY STRING;
BEGIN
TRUNC_QUERY := "TRUNCATE TABLE DB_IAW_"+ENV+"_DM.HOLDINGS.WT_FACT_HOLDINGS;";
INS_QUERY := "
INSERT INTO
	DB_IAW_"+ENV+"_DM.HOLDINGS.WT_FACT_HOLDINGS (
		HK_LINK,
		HK_HUB_CONTRACT,
		HK_HUB_INVESTMENT_PRODUCT_TYPE,
		HK_HUB_PARTY_ROLE_ADVISOR,
		HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
		HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
		MD_START_DT,
		MD_SOURCE,
		MD_SRC_SYSTEM,
		MD_EXTRACT_DT,
		MD_SECURITY_TYPE,
		SK_DIM_ACCOUNTS,
		SK_DIM_MARKETPRODUCTS,
		SK_DIM_ADVISORS,
		SK_DIM_CLIENTS,
		SK_DIM_PLANS,
		RR_CD,
		PLN_SYSID,
		BALANCE_DATE,
		HOLDING_VALUE,
		AUA,
		AUM,
		AUM_CLARINGTON,
		AUM_IA,
		CASH_POSITION,
		PROGRAM_TYPE,
		ACCOUNT_PROGRAM_TYPE,
		ADMINISTRATORY_TYPE )
VALUES
	(
	SELECT 
	SLI.HK_LINK,
	LI.HK_HUB_CONTRACT,
	LI.HK_HUB_INVESTMENT_PRODUCT_TYPE,
	LI.HK_HUB_PARTY_ROLE_ADVISOR,
	LI.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	LI.HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
	SLI.MD_START_DT,
	SLI.MD_SOURCE,
	LI.MD_SRC_SYSTEM,
	LI.MD_EXTRACT_DT,
	CASE WHEN DAC.ID IS NULL THEN ''-1'' ELSE DAC.ID END AS O_ACNT_ID,
	CASE WHEN DFI.ID IS NULL THEN ''-1'' ELSE DFI.ID END AS O_PRODUCT_ID,
	CASE WHEN DA.ID IS NULL THEN ''-1'' ELSE DA.ID END AS O_ADV_ID,
	CASE WHEN DC.ID IS NULL THEN ''-1'' ELSE DC.ID END AS O_CLIENT_ID,
	CASE WHEN DP.ID IS NULL THEN ''-1'' ELSE DP.ID END AS O_PLAN_ID,
	SLI.RR_CD,
	SLI.PLN_SYSID,
	SLI.BALANCE_DATE,
	SLI.HOLDING_VALUE,
	SLI.AUA,
	SLI.AUM,
	SLI.AUM_CLARINGTON,
	SLI.AUM_IA,
	SLI.CASH_POSITION,
	SLI.PROGRAM_TYPE,
	SLI.ACCOUNT_PROGRAM_TYPE,
	SLI.ADMINISTRATORY_TYPE
	FROM DB_IAW_"+ENV+"_DWH.HOLDINGS_BDV.SAT_LINK_INVESTMENT SLI 
	JOIN DB_IAW_"+ENV+"_DWH.HOLDINGS_BDV.LINK_INVESTMENT LI
	ON SLI.HK_LINK = LI.HK_LINK 
	JOIN DB_IAW_"+ENV+"_DM.HOLDINGS.FACT_HOLDINGS FH
	ON LI.HK_LINK = FH.HK_LINK
	RIGHT OUTER JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_FINANCIAL_INSTRUMENTS DFI
	ON LI.HK_HUB_INVESTMENT_PRODUCT_TYPE = DFI.HK_HUB
	RIGHT OUTER JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_ADVISOR DA
	ON LI.HK_HUB_PARTY_ROLE_ADVISOR = DA.HK_HUB
	RIGHT OUTER JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_PLANS DP
	ON LI.HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES = DP.HK_HUB
	RIGHT OUTER JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_CLIENTS DC
	ON LI.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER = DC.HK_HUB
	RIGHT OUTER JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_ACCOUNTS DAC
	ON LI.HK_HUB_CONTRACT = DAC.HK_HUB
	WHERE 
	SLI.MD_START_DT = TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') 
	AND FH.HK_LINK IS NULL
	AND (DFI.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DFI.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DFI.MD_END_DT = ''''))
	AND (DA.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DA.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DA.MD_END_DT = ''''))
	AND (DP.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DP.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DP.MD_END_DT = ''''))
	AND (DC.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DC.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DC.MD_END_DT = ''''))
	AND (DAC.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DAC.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DAC.MD_END_DT = ''''));
              ";
EXECUTE IMMEDIATE :TRUNC_QUERY;
EXECUTE IMMEDIATE :INS_QUERY;
END
';
CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DM.REVENUES.SP_CONV_LOADDM_BDV_REVENUES_TO_DM_WT_FACT_REVENUES("ENV" VARCHAR(1000), "JOB_NAME" VARCHAR(16777216), "DATA_START_DT" VARCHAR(10), "JOB_AUDIT_ID" VARCHAR(16777216), "RUN_ID" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
DECLARE
TRUNC_QUERY STRING;
INS_QUERY STRING;
UPD_QUERY STRING;
BEGIN
TRUNC_QUERY := "TRUNCATE TABLE DB_IAW_"+ENV+"_DM.REVENUES.WT_FACT_REVENUE;";
INS_COPY_QUERY := "
INSERT INTO
	DB_IAW_"+ENV+"_DM.REVENUES.WT_FACT_REVENUE (
		MD_START_DT, 
		MD_SRC_SYSTEM, 
		MD_EXTRACT_DT, 
		MD_SOURCE, 
		HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, 
		HK_HUB_PARTY_ROLE_ADVISOR, 
		HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES, 
		HK_HUB_INVESTMENT_PRODUCT_TYPE, 
		HK_HUB_CONTRACT, SK_DIM_CLIENTS, 
		SK_DIM_ADVISORS, SK_DIM_PLANS, 
		SK_DIM_MARKETPRODUCTS, 
		SK_DIM_ACCOUNTS, 
		PAYMENT_DATE, 
		REVENUE_AMOUNT, 
		REVENUE_TYPE, 
		REVENUE_SUBTYPE )
VALUES
	(
	SELECT 
	MAX(LR.MD_START_DT) AS o_MAX_START_DATE,
	MAX(LR.MD_SRC_SYSTEM) AS o_MAX_MD_SRC_SYSTEM,
	MAX(LR.MD_EXTRACT_DT) AS o_MAX_MD_EXTRACT_DT,
	MAX(LR.MD_SOURCE) AS o_MAX_MD_SOURCE,
	LR.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	LR.HK_HUB_PARTY_ROLE_ADVISOR, 
	LR.HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES,
	LR.HK_HUB_INVESTMENT_PRODUCT_TYPE,
	LR.HK_HUB_CONTRACT,
	CASE WHEN DC.ID IS NULL THEN ''-1'' ELSE DC.ID END AS o_CLIENT_ID,
	CASE WHEN DA.ID IS NULL THEN ''-1'' ELSE DFI.ID END AS o_ADV_ID,
	CASE WHEN DP.ID IS NULL THEN ''-1'' ELSE DP.ID END AS o_PLAN_ID,
	CASE WHEN DFI.ID IS NULL THEN ''-1'' ELSE DFI.ID END AS o_Product_ID,
	CASE WHEN DAC.ID IS NULL THEN ''-1'' ELSE DAC.ID END AS o_ACNT_ID,
	LR.PAYMENT_DATE,
	SUM(LR.REVENUE) AS o_SUM_REVENUE,
	LR.REVENUE_TYPE,
	LR.REVENUE_SUBTYPE
	FROM DB_IAW_"+ENV+"_DWH.REVENUES_BDV.LINK_REVENUE LR 
	LEFT JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_FINANCIAL_INSTRUMENTS DFI
	ON LR.HK_HUB_INVESTMENT_PRODUCT_TYPE = DFI.HK_HUB 
	LEFT JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_ADVISOR DA
	ON LR.HK_HUB_PARTY_ROLE_ADVISOR = DA.HK_HUB
	LEFT JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_PLANS DP
	ON LR.HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES = DP.HK_HUB
	LEFT JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_CLIENTS DC
	ON LR.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER = DC.HK_HUB
	LEFT JOIN DB_IAW_"+ENV+"_DM.SHARED.DIM_ACCOUNTS DAC
	ON LR.HK_HUB_CONTRACT = DAC.HK_HUB
	WHERE 
	LR.MD_START_DT = TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') 
	AND (DFI.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DFI.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DFI.MD_END_DT = ''''))
	AND (DA.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DA.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DA.MD_END_DT = ''''))
	AND (DP.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DP.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DP.MD_END_DT = ''''))
	AND (DC.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DC.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DC.MD_END_DT = ''''))
	AND (DAC.MD_START_DT <= TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') AND (DAC.MD_END_DT> TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD'') OR DAC.MD_END_DT = ''''))
	GROUP BY 
	LR.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, LR.HK_HUB_PARTY_ROLE_ADVISOR, LR.HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES, LR.HK_HUB_INVESTMENT_PRODUCT_TYPE, LR.HK_HUB_CONTRACT, o_ACNT_ID, o_CLIENT_ID, o_PLAN_ID, o_ADV_ID, o_PRODUCT_ID, LR.REVENUE_TYPE, LR.REVENUE_SUBTYPE, LR.PAYMENT_DATE, LR.REVENUE;
              ";

UPD_QUERY := "UPDATE DB_IAW_"+ENV+"_DM.REVENUES.WT_FACT_REVENUE SET
	HK_LINK = SHA1(UPPER(CONCAT(
	  COALESCE(TRIM(MD_SRC_SYSTEM), ''#NULL#''), ''|''
	, COALESCE(TRIM(HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER), ''#NULL#''), ''|''
	, COALESCE(TRIM(HK_HUB_PARTY_ROLE_ADVISOR), ''#NULL#''), ''|''
	, COALESCE(TRIM(HK_HUB_REF_INVESTMENT_SAVING_PROGRAM_TYPES), ''#NULL#''), ''|''
	, COALESCE(TRIM(HK_HUB_INVESTMENT_PRODUCT_TYPE), ''#NULL#''), ''|''
	, COALESCE(TRIM(HK_HUB_CONTRACT), ''#NULL#''), ''|''
	, COALESCE(TRIM(PAYMENT_DATE), ''#NULL#''), ''|''
	, COALESCE(TRIM(REVENUE_TYPE), ''#NULL#''), ''|''
	, COALESCE(TRIM(REVENUE_SUBTYPE), ''#NULL#'')
	)))
	Where 1=1";

EXECUTE IMMEDIATE :INS_PRE_QUERY;
EXECUTE IMMEDIATE :INS_COPY_QUERY;
END
';

CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DM.REVENUES.SP_CONV_LOADDM_DM_WT_TO_DM_DIM_FACT_REVENUES_INSERT("ENV" VARCHAR(1000), "JOB_NAME" VARCHAR(16777216), "JOB_AUDIT_ID" VARCHAR(16777216), "RUN_ID" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
DECLARE
INS_QUERY STRING;
BEGIN
INS_QUERY = "INSERT INTO DB_IAW_"+ENV+"_DM.REVENUES.FACT_REVENUE(
HK_LINK,
MD_START_DT,
MD_CREATION_DT,
MD_CREATION_AUDIT_ID,
MD_SOURCE,
MD_SRC_SYSTEM,
MD_EXTRACT_DT,
MD_SECURITY_TYPE,
SK_DIM_CLIENTS,
SK_DIM_ADVISORS,
SK_DIM_PLANS,
SK_DIM_MARKETPRODUCTS,
SK_DIM_ACCOUNTS,
PAYMENT_DATE,
REVENUE_AMOUNT,
REVENUE_TYPE,
REVENUE_SUBTYPE,
AUA)
VALUES(
SELECT 
M.HK_LINK, 
M.MD_START_DT, 
CURRENT_TIMESTAMP(), 
CONCAT("+JOB_AUDIT_ID+",''#'',"+JOB_NAME+","+RUN_ID+"),
M.MD_SOURCE,
M.MD_SRC_SYSTEM,
M.MD_EXTRACT_DT,
M.MD_SECURITY_TYPE,
M.SK_DIM_CLIENTS,
M.SK_DIM_ADVISORS,
M.SK_DIM_PLANS,
M.SK_DIM_MARKETPRODUCTS,
M.SK_DIM_ACCOUNTS,
M.PAYMENT_DATE,
M.REVENUE_AMOUNT,
M.REVENUE_TYPE,
M.REVENUE_SUBTYPE,
M.AUA
FROM DB_IAW_"+ENV+"_DM.REVENUES.WT_FACT_REVENUE M
RIGHT OUTER JOIN DB_IAW_"+ENV+"_DM.REVENUES.FACT_REVENUE D
ON M.HK_LINK = D.HK_LINK
WHERE D.HK_LINK IS NULL);";

EXECUTE IMMEDIATE :INS_QUERY;
END
';

CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DM.REVENUES.SP_CONV_LOADDM_DM_WT_TO_DM_FACT_HOLDINGS_INSERT("ENV" VARCHAR(1000), "JOB_NAME" VARCHAR(16777216), "JOB_AUDIT_ID" VARCHAR(16777216), "DATA_START_DATE" VARCHAR(10), "RUN_ID" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
DECLARE
INS_QUERY STRING;
BEGIN
INS_QUERY = "INSERT INTO DB_IAW_"+ENV+"_DM.HOLDINGS.FACT_HOLDINGS(
HK_LINK,
MD_START_DT,
MD_CREATION_DT,
MD_CREATION_AUDIT_ID,
MD_SOURCE,
MD_SRC_SYSTEM,
MD_EXTRACT_DT,
MD_SECURITY_TYPE,
SK_DIM_ACCOUNTS,
SK_DIM_MARKETPRODUCTS,
SK_DIM_ADVISORS,
SK_DIM_CLIENTS,
SK_DIM_PLANS,
RR_CD,
PLN_SYSID,
BALANCE_DATE,
HOLDING_VALUE,
AUA,
AUM,
AUM_CLARINGTON,
AUM_IA,
CASH_POSITION,
PROGRAM_TYPE,
ACCOUNT_PROGRAM_TYPE,
ADMINISTRATORY_TYPE)
VALUES(
SELECT 
M.HK_LINK, 
TO_DATE("+ DATA_START_DATE +",''YYYY-MM-DD''), 
CURRENT_TIMESTAMP(), 
CONCAT("+JOB_AUDIT_ID+",''#'',"+JOB_NAME+","+RUN_ID+"),
M.MD_SOURCE,
M.MD_SRC_SYSTEM,
M.MD_EXTRACT_DT,
M.MD_SECURITY_TYPE,
M.SK_DIM_ACCOUNTS,
M.SK_DIM_MARKETPRODUCTS,
M.SK_DIM_ADVISORS,
M.SK_DIM_CLIENTS,
M.SK_DIM_PLANS,
M.RR_CD,
M.PLN_SYSID,
M.BALANCE_DATE,
M.HOLDING_VALUE,
M.AUA,
M.AUM,
M.AUM_CLARINGTON,
M.AUM_IA,
M.CASH_POSITION,
M.PROGRAM_TYPE,
M.ACCOUNT_PROGRAM_TYPE,
M.ADMINISTRATORY_TYPE
FROM DB_IAW_"+ENV+"_DM.HOLDINGS.WT_FACT_HOLDINGS M
RIGHT OUTER JOIN DB_IAW_"+ENV+"_DM.HOLDINGS.FACT_HOLDINGS D
ON M.HK_LINK = D.HK_LINK
WHERE D.HK_LINK IS NULL);";
EXECUTE IMMEDIATE :INS_QUERY;
END
';

create or replace TABLE DB_IAW_#env#_DM.SHARED.DIM_ADVISOR (
	ID NUMBER(38,0) autoincrement COMMENT 'Surrogate key of the dimension',
	HK_HUB VARCHAR(40) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_END_DT TIMESTAMP_NTZ(9) COMMENT 'End Date of the image/version',
	MD_HASH_NAT_KEYS VARCHAR(64) DEFAULT '0' COMMENT 'Represents the whole set of hashed natural keys to be historized for an occurrence',
	MD_HASHDIFF_TYPE1 VARCHAR(40) DEFAULT '0' COMMENT 'Represents the whole set of hashed type 1 attributes to be historized for an occurrence',
	MD_HASHDIFF_TYPE2 VARCHAR(40) DEFAULT '0' COMMENT 'Represents the whole set of hashed type 2 attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_MODIFY_DT TIMESTAMP_NTZ(9) COMMENT 'Modification Date Time of the occurrence',
	MD_MODIFY_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	SRC_ID VARCHAR(50) COMMENT 'Not used TBD ?',
	MASTER_CODE VARCHAR(50) COMMENT 'Master code of the advisor',
	COMPANY_CODE VARCHAR(50) COMMENT 'Company code of the advisor',
	COMPANY_NAME VARCHAR(512) COMMENT 'Company name of the advisor',
	REGULATORY_ORGANIZATION_NAME VARCHAR(512) COMMENT 'REGULATORY ORGANIZATION NAME of the advisor',
	REGULATORY_ORGANIZATION_CODE VARCHAR(50) COMMENT 'REGULATORY ORGANIZATION CODE of the advisor',
	DEALER_CODE VARCHAR(50) COMMENT 'Dealer code',
	DEALER_NAME VARCHAR(512) COMMENT 'Dealer name',
	REGION_CODE VARCHAR(512) COMMENT 'Region code',
	REGION_NAME VARCHAR(512) COMMENT 'Region name',
	REGION_VP VARCHAR(16777216) COMMENT 'full name of the RVP',
	BRANCHCODE VARCHAR(50) COMMENT 'Code of the representative branch code',
	BRANCHNAME VARCHAR(512) COMMENT 'Name of the representative branch',
	TEAM_CODE NUMBER(38,0) COMMENT 'Representant Group ID',
	TEAM_NAME VARCHAR(512) COMMENT 'Advisor team description',
	ADVISOR_FULLNAME VARCHAR(512) COMMENT 'Representative name',
	FIRSTNAME VARCHAR(512) COMMENT 'Representative first name',
	LASTNAME VARCHAR(512) COMMENT 'Representative last name',
	ADVISOR_CORPORATION_NAME VARCHAR(512) COMMENT 'Representative corporation name',
	STATUS VARCHAR(512) COMMENT 'Active RR code indicator',
	GROUP_RSP_INDICATOR VARCHAR(512) COMMENT 'Group Retirement Savings Plan (RSP) indicator',
	PROVINCE_CODE VARCHAR(16777216) COMMENT 'province code',
	PROVINCE VARCHAR(16777216) COMMENT 'province name',
	ADVISOR_AUA_SEGMENT VARCHAR(512) COMMENT 'Advisor AUA Segment : 25k-100k',
	ADVISOR_AUA_SEGMENT_ORDER NUMBER(38,0) COMMENT 'Advisor AUA Segment ORDER',
	ADVISOR_START_DATE TIMESTAMP_NTZ(9) COMMENT 'the starting date of the advisor',
	NEW_ADVISOR NUMBER(38,0) COMMENT 'New advisor indicator (0 or 1)',
	ADVISOR_EFFECIVENESS_DT TIMESTAMP_NTZ(9) COMMENT 'Its the date after one year of advisor joining date , implemented as part of Organic growth',
	DEPARTED_ADVISOR_IND NUMBER(1,0) COMMENT 'DEPARTED ADVISOR INDICATOR',
	END_DATE TIMESTAMP_NTZ(9) COMMENT 'Departure date of the advisor (TBD)',
	REASON VARCHAR(1000) COMMENT 'Reason of departure',
	NEW_FIRM VARCHAR(1000) COMMENT 'Departure destination',
	NEW_FIRM_TYPE VARCHAR(1000) COMMENT 'Departure destination Type',
	NEW_FIRM_BACK_OFFICE VARCHAR(1000) COMMENT 'Departure destination Back-Office',
	PRESTIGE_STATUS VARCHAR(100) COMMENT 'Prestige Status',
	PRIMARY_ROLE VARCHAR(500) COMMENT 'PRIMARY ROLE',
	TRANSITION_PERIOD_END_DATE TIMESTAMP_NTZ(9) COMMENT 'Advisor transition end date',
	DEAL_ASSESTS NUMBER(11,0) COMMENT 'Deal assets',
	EXPECTED_ASSESTS NUMBER(11,0) COMMENT 'Expected assets',
	PREVIOUS_FIRM VARCHAR(100) COMMENT 'Previous Firm of the Advisor',
	PREVIOUS_FIRM_TYPE VARCHAR(100) COMMENT 'Previous Firm type of the Advisor',
	AGE_SEGMENT VARCHAR(50) COMMENT 'Advisor Age Segment : 25-34',
	AGE_SEGMENT_ORD NUMBER(2,0) COMMENT 'Advisor Age Segment ORDER',
	SUSPENDED_IND NUMBER(1,0) COMMENT 'suspended Flag, if an advisor is deleted in certs but still have AUA, will be considered as suspended',
	ADVISOR_AGE NUMBER(38,0) COMMENT 'Age of the dealer',
	REP_EMAIL VARCHAR(1000) COMMENT 'Advisor repemail',
	CBM VARCHAR(1000) COMMENT 'Advisor cbm',
	BRANCH_NRD VARCHAR(1000) COMMENT 'Advisor branch nrd',
	BRANCH_ADDRESS1 VARCHAR(1000) COMMENT 'Advisor branch ADDRESS1',
	BRANCH_ADDRESS2 VARCHAR(1000) COMMENT 'Advisor branch ADDRESS2',
	BRANCH_CITY VARCHAR(1000) COMMENT 'Advisor branch city',
	BRANCH_POSTAL_CODE VARCHAR(1000) COMMENT 'Advisor branch postal code'
);

create or replace TABLE DB_IAW_#env#_DM.SHARED.DIM_DATE (
	ID NUMBER(38,0) COMMENT 'Day identifier ex: 20210408',
	DATE DATE NOT NULL COMMENT 'Date ex: 2021-04-08',
	FULL_DATE_DESC VARCHAR(64) NOT NULL COMMENT 'Full date description ex: Thursday, Apr 08, 2021',
	DAY_NUM_IN_WEEK NUMBER(1,0) NOT NULL COMMENT 'Day number in a week (Monday=1, Sunday=7)',
	DAY_NUM_IN_MONTH NUMBER(2,0) NOT NULL COMMENT 'Day number in a month (1 to 31)',
	DAY_NUM_IN_YEAR NUMBER(3,0) NOT NULL COMMENT 'Day number in a year (1 to 366)',
	DAY_NAME VARCHAR(10) NOT NULL COMMENT 'Day name ex: Thursday',
	DAY_ABBREV VARCHAR(3) NOT NULL COMMENT 'Day abreviation ex: Thu',
	WEEKDAY_IND VARCHAR(64) NOT NULL COMMENT 'Weekday indicator (Weekday, Not a weekday)',
	US_HOLIDAY_IND VARCHAR(64) COMMENT 'United State holiday Indicator',
	_HOLIDAY_IND VARCHAR(64) COMMENT 'holiday indicator',
	MONTH_END_IND VARCHAR(64) NOT NULL COMMENT 'Month end indicator (Not-Month-end, Month-end)',
	WEEK_BEGIN_DATE_NKEY NUMBER(9,0) NOT NULL COMMENT 'Week begin date nkey ex: 20210405',
	WEEK_BEGIN_DATE DATE NOT NULL COMMENT 'Week begin date ex: 2021-04-05',
	WEEK_END_DATE_NKEY NUMBER(9,0) NOT NULL COMMENT 'Week end date nkey ex: 20210411',
	WEEK_END_DATE DATE NOT NULL COMMENT 'Week end date ex: 2021-04-11',
	WEEK_NUM_IN_YEAR NUMBER(9,0) NOT NULL COMMENT 'Week number in a year (1 to 53)',
	MONTH_NAME VARCHAR(10) NOT NULL COMMENT 'Month name ex: April',
	MONTH_ABBREV VARCHAR(3) NOT NULL COMMENT 'Month abreviation ex: Apr',
	MONTH_NUM_IN_YEAR NUMBER(2,0) NOT NULL COMMENT 'Month number in a year (1 to 12)',
	YEARMONTH VARCHAR(10) NOT NULL COMMENT 'Year and month ex: 2021-04',
	QUARTER NUMBER(1,0) NOT NULL COMMENT 'Quarter number (1 to 4)',
	YEARQUARTER VARCHAR(10) NOT NULL COMMENT 'Year and Quarter ex: 2021-02',
	YEAR NUMBER(5,0) NOT NULL COMMENT 'Year ex: 2021',
	FISCAL_WEEK_NUM NUMBER(2,0) NOT NULL COMMENT 'Fiscal week number (1 to 53)',
	FISCAL_MONTH_NUM NUMBER(2,0) NOT NULL COMMENT 'Fiscal month number (1 to 12)',
	FISCAL_YEARMONTH VARCHAR(10) NOT NULL COMMENT 'Fiscal year and month ex: 2021-04',
	FISCAL_QUARTER NUMBER(1,0) NOT NULL COMMENT 'Fiscal quarter number (1 to 4)',
	FISCAL_YEARQUARTER VARCHAR(10) NOT NULL COMMENT 'Fiscal year and quarter ex: 2021-02',
	FISCAL_HALFYEAR NUMBER(1,0) NOT NULL COMMENT 'Fiscal half year  (1 or 2)',
	FISCAL_YEAR NUMBER(5,0) NOT NULL COMMENT 'Fiscal year ex: 2021',
	SQL_TIMESTAMP TIMESTAMP_NTZ(9) COMMENT 'Day timestamp ex: 2021-04-08 00:00:00',
	CURRENT_ROW_IND VARCHAR(1) DEFAULT 'Y' COMMENT 'BI indicator, is it a current row or not (Y,N)',
	EFFECTIVE_DATE DATE DEFAULT CAST(CURRENT_TIMESTAMP() AS DATE) COMMENT 'BI date, day of creation ex: 2021-04-06',
	EXPIRATION_DATE DATE DEFAULT CAST('9999-12-31' AS DATE) COMMENT 'BI date, day of expiration, by default the vaue is: 9999-12-31',
	MONTH_NAME_YEAR VARCHAR(100) COMMENT 'Month name and year ex: April 2021',
	MONTH_NAME_YEAR_ORD NUMBER(38,0) COMMENT 'Month name and year order ex:202104'
)COMMENT='Type 0 Dimension Table Housing Calendar and Fiscal Year Date Attributes'
;

create or replace TABLE DB_IAW_#env#_DM.SHARED.DIM_FINANCIAL_INSTRUMENTS (
	ID NUMBER(38,0) autoincrement COMMENT 'Surrogate key of the dimension',
	HK_HUB VARCHAR(40) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_END_DT TIMESTAMP_NTZ(9) COMMENT 'End Date of the image/version',
	MD_HASH_NAT_KEYS VARCHAR(64) DEFAULT '0' COMMENT 'Represents the whole set of hashed natural keys to be historized for an occurrence',
	MD_HASHDIFF_TYPE1 VARCHAR(40) DEFAULT '0' COMMENT 'Represents the whole set of hashed type 1 attributes to be historized for an occurrence',
	MD_HASHDIFF_TYPE2 VARCHAR(40) DEFAULT '0' COMMENT 'Represents the whole set of hashed type 2 attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_MODIFY_DT TIMESTAMP_NTZ(9) COMMENT 'Modification Date Time of the occurrence',
	MD_MODIFY_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	INVESTMENT_PRODUCT_ID VARCHAR(16777216) COMMENT 'The product identifier',
	SYMBOL VARCHAR(512) COMMENT 'The product symbol (product code)',
	NAME VARCHAR(1000) COMMENT 'The product name',
	ASSET_CATEGORY VARCHAR(512) COMMENT 'The product asset category',
	CATEGORY VARCHAR(512) COMMENT 'The product category',
	PRODUCT_GROUP VARCHAR(512) COMMENT 'The product group name',
	ISSUER_COMPANY_CODE VARCHAR(4) COMMENT 'The issuer company code',
	ISSUER_COMPANY_NAME VARCHAR(1000) COMMENT 'The issuer company name'
);

create or replace TABLE DB_IAW_#env#_DM.SHARED.DIM_PLANS (
	ID NUMBER(38,0) autoincrement COMMENT 'Column description',
	HK_HUB VARCHAR(40) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_END_DT TIMESTAMP_NTZ(9) COMMENT 'End Date of the image/version',
	MD_HASH_NAT_KEYS VARCHAR(64) DEFAULT '0' COMMENT 'Represents the whole set of hashed natural keys to be historized for an occurrence',
	MD_HASHDIFF_TYPE1 VARCHAR(40) DEFAULT '0' COMMENT 'Represents the whole set of hashed type 1 attributes to be historized for an occurrence',
	MD_HASHDIFF_TYPE2 VARCHAR(40) DEFAULT '0' COMMENT 'Represents the whole set of hashed type 2 attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_MODIFY_DT TIMESTAMP_NTZ(9) COMMENT 'Modification Date Time of the occurrence',
	MD_MODIFY_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	PLAN_CODE VARCHAR(8000) COMMENT 'The Plan code',
	PLAN_LABEL VARCHAR(8000) COMMENT 'The Plan label',
	ACCOUNT_TYPE VARCHAR(16777216) COMMENT 'The account type',
	GROUP_TYPE_CODE VARCHAR(8000) COMMENT 'The group type code',
	ACCUMULATION_TYPE VARCHAR(8000) COMMENT 'Accumulation type'
);

create or replace TABLE DB_IAW_#env#_DM.SHARED.WT_DIM_ADVISOR (
	HK_HUB VARCHAR(40) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_END_DT TIMESTAMP_NTZ(9) COMMENT 'End Date of the image/version',
	MD_HASH_NAT_KEYS VARCHAR(64) COMMENT 'Represents the whole set of hashed natural keys to be historized for an occurrence',
	MD_HASHDIFF_TYPE1 VARCHAR(40) COMMENT 'Represents the whole set of hashed type 1 attributes to be historized for an occurrence',
	MD_HASHDIFF_TYPE2 VARCHAR(40) COMMENT 'Represents the whole set of hashed type 2 attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_MODIFY_DT TIMESTAMP_NTZ(9) COMMENT 'Modification Date Time of the occurrence',
	MD_MODIFY_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	ID VARCHAR(50) COMMENT 'Surrogate key of the dimension DIM_ADVISORS',
	MASTER_CODE VARCHAR(50) COMMENT 'Master code of the advisor',
	COMPANY_CODE VARCHAR(50) COMMENT 'Company code of the advisor',
	COMPANY_NAME VARCHAR(512) COMMENT 'Company name of the advisor',
	REGULATORY_ORGANIZATION_NAME VARCHAR(512) COMMENT 'REGULATORY ORGANIZATION NAME of the advisor',
	REGULATORY_ORGANIZATION_CODE VARCHAR(50) COMMENT 'REGULATORY ORGANIZATION CODE of the advisor',
	DEALER_CODE VARCHAR(50) COMMENT 'Dealer code',
	DEALER_NAME VARCHAR(512) COMMENT 'Dealer name',
	REGION_CODE VARCHAR(512) COMMENT 'Region code',
	REGION_NAME VARCHAR(512) COMMENT 'Region name',
	REGION_VP VARCHAR(16777216) COMMENT 'full name of the RVP',
	BRANCHCODE VARCHAR(50) COMMENT 'Code of the representative branch code',
	BRANCHNAME VARCHAR(512) COMMENT 'Name of the representative branch',
	TEAM_CODE NUMBER(38,0) COMMENT 'Representant Group ID',
	TEAM_NAME VARCHAR(512) COMMENT 'Advisor team description',
	ADVISOR_FULLNAME VARCHAR(512) COMMENT 'Representative name',
	FIRSTNAME VARCHAR(512) COMMENT 'Representative first name',
	LASTNAME VARCHAR(512) COMMENT 'Representative last name',
	ADVISOR_CORPORATION_NAME VARCHAR(512) COMMENT 'Representative corporation name',
	STATUS VARCHAR(512) COMMENT 'Active RR code indicator',
	GROUP_RSP_INDICATOR VARCHAR(512) COMMENT 'Group Retirement Savings Plan (RSP) indicator',
	PROVINCE_CODE VARCHAR(16777216) COMMENT 'province code',
	PROVINCE VARCHAR(16777216) COMMENT 'province name',
	ADVISOR_AUA_SEGMENT VARCHAR(512) COMMENT 'Advisor AUA Segment : 25k-100k',
	ADVISOR_AUA_SEGMENT_ORDER NUMBER(38,0) COMMENT 'Advisor AUA Segment ORDER',
	ADVISOR_START_DATE TIMESTAMP_NTZ(9) COMMENT 'the starting date of the advisor',
	NEW_ADVISOR NUMBER(38,0) COMMENT 'New advisor indicator (0 or 1)',
	ADVISOR_EFFECTIVENESS_DT TIMESTAMP_NTZ(9) COMMENT 'Its the date after one year of advisor joining date , implemented as part of Organic growth',
	DEPARTED_ADVISOR_IND NUMBER(1,0) COMMENT 'DEPARTED ADVISOR INDICATOR',
	END_DATE TIMESTAMP_NTZ(9) COMMENT 'Departure date of the advisor (TBD)',
	REASON VARCHAR(1000) COMMENT 'Reason of departure',
	NEW_FIRM VARCHAR(1000) COMMENT 'Departure destination',
	NEW_FIRM_TYPE VARCHAR(1000) COMMENT 'Departure destination Type',
	NEW_FIRM_BACK_OFFICE VARCHAR(1000) COMMENT 'Departure destination Back-Office',
	PRESTIGE_STATUS VARCHAR(100) COMMENT 'Prestige Status',
	PRIMARY_ROLE VARCHAR(500) COMMENT 'PRIMARY ROLE',
	TRANSITION_PERIOD_END_DATE TIMESTAMP_NTZ(9) COMMENT 'Advisor transition end date',
	DEAL_ASSESTS NUMBER(11,0) COMMENT 'Deal assets',
	EXPECTED_ASSESTS NUMBER(11,0) COMMENT 'Expected assets',
	PREVIOUS_FIRM VARCHAR(100) COMMENT 'Previous Firm of the Advisor',
	PREVIOUS_FIRM_TYPE VARCHAR(100) COMMENT 'Previous Firm type of the Advisor',
	AGE_SEGMENT VARCHAR(50) COMMENT 'Advisor Age Segment : 25-34',
	AGE_SEGMENT_ORD NUMBER(2,0) COMMENT 'Advisor Age Segment ORDER',
	SUSPENDED_IND NUMBER(1,0) COMMENT 'suspended Flag, if an advisor is deleted in certs but still have AUA, will be considered as suspended',
	ADVISOR_AGE NUMBER(38,0) COMMENT 'Age of the dealer',
	REP_EMAIL VARCHAR(1000) COMMENT 'Advisor repemail',
	CBM VARCHAR(1000) COMMENT 'Advisor cbm',
	BRANCH_NRD VARCHAR(1000) COMMENT 'Advisor branch nrd',
	BRANCH_ADDRESS1 VARCHAR(1000) COMMENT 'Advisor branch ADDRESS1',
	BRANCH_ADDRESS2 VARCHAR(1000) COMMENT 'Advisor branch ADDRESS2',
	BRANCH_CITY VARCHAR(1000) COMMENT 'Advisor branch city',
	BRANCH_POSTAL_CODE VARCHAR(1000) COMMENT 'Advisor branch postal code'

);

create or replace TABLE DB_IAW_#env#_DM.SHARED.WT_DIM_FINANCIAL_INSTRUMENTS (
	HK_HUB VARCHAR(40) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_END_DT TIMESTAMP_NTZ(9) COMMENT 'End Date of the image/version',
	MD_HASH_NAT_KEYS VARCHAR(64) COMMENT 'Represents the whole set of hashed natural keys to be historized for an occurrence',
	MD_HASHDIFF_TYPE1 VARCHAR(40) COMMENT 'Represents the whole set of hashed type 1 attributes to be historized for an occurrence',
	MD_HASHDIFF_TYPE2 VARCHAR(40) COMMENT 'Represents the whole set of hashed type 2 attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_MODIFY_DT TIMESTAMP_NTZ(9) COMMENT 'Modification Date Time of the occurrence',
	MD_MODIFY_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	INVESTMENT_PRODUCT_ID VARCHAR(16777216) COMMENT 'The product identifier',
	SYMBOL VARCHAR(512) COMMENT 'The product symbol (product code)',
	NAME VARCHAR(1000) COMMENT 'The product name',
	ASSET_CATEGORY VARCHAR(512) COMMENT 'The product asset category',
	CATEGORY VARCHAR(512) COMMENT 'The product category',
	PRODUCT_GROUP VARCHAR(512) COMMENT 'The product group',
	ISSUER_COMPANY_CODE VARCHAR(4) COMMENT 'The issuer company code',
	ISSUER_COMPANY_NAME VARCHAR(1000) COMMENT 'The issuer company name'
);

create or replace TABLE DB_IAW_#env#_DM.SHARED.WT_DIM_PLANS (
	HK_HUB VARCHAR(40) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_HASH_NAT_KEYS VARCHAR(64) COMMENT 'Represents the whole set of hashed natural keys to be historized for an occurrence',
	MD_HASHDIFF_TYPE2 VARCHAR(40) COMMENT 'Represents the whole set of hashed type 2 attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	PLAN_CODE VARCHAR(8000) COMMENT 'The Plan code',
	PLAN_LABEL VARCHAR(8000) COMMENT 'The Plan label',
	ACCOUNT_TYPE VARCHAR(16777216) COMMENT 'The account type',
	GROUP_TYPE_CODE VARCHAR(8000) COMMENT 'The group type code',
	ACCUMULATION_TYPE VARCHAR(8000) COMMENT 'Accumulation type'
);

CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DM.SHARED.SP_CONV_LOADDM_BDV_SHARED_TO_DM_WT_DIMADVISOR("ENV" VARCHAR(1000), "I_DATA_START_DATE" VARCHAR(1000))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
INS_PRE_DEL STRING;
INS_INSERT STRING;
INS_UPDATE STRING;
BEGIN
i_DATA_START_DATE :=CHAR(39)||i_DATA_START_DATE||CHAR(39);
INS_PRE_DEL := ''DELETE FROM DB_IAW_''||ENV||''_DM.SHARED.WT_DIM_ADVISOR WHERE 1=1 '';
INS_INSERT := ''
INSERT INTO DB_IAW_''||ENV||''_DM.SHARED.WT_DIM_ADVISOR (HK_HUB,MD_START_DT,MD_HASH_NAT_KEYS,MD_CREATION_DT,MD_CREATION_AUDIT_ID,MD_SOURCE,MD_SRC_SYSTEM,MD_EXTRACT_DT,MASTER_CODE,COMPANY_CODE,COMPANY_NAME,REGULATORY_ORGANIZATION_NAME,REGULATORY_ORGANIZATION_CODE,DEALER_CODE,DEALER_NAME,REGION_CODE,REGION_NAME,REGION_VP,BRANCHCODE,BRANCHNAME,TEAM_CODE,TEAM_NAME,ADVISOR_FULLNAME,FIRSTNAME,LASTNAME,ADVISOR_CORPORATION_NAME,STATUS,GROUP_RSP_INDICATOR,PROVINCE_CODE,PROVINCE,ADVISOR_AUA_SEGMENT,ADVISOR_AUA_SEGMENT_ORDER,ADVISOR_START_DATE,NEW_ADVISOR,ADVISOR_EFFECTIVENESS_DT,DEPARTED_ADVISOR_IND,PRIMARY_ROLE,END_DATE,REASON,NEW_FIRM,NEW_FIRM_TYPE,NEW_FIRM_BACK_OFFICE,PRESTIGE_STATUS,TRANSITION_PERIOD_END_DATE,DEAL_ASSESTS,EXPECTED_ASSESTS,PREVIOUS_FIRM,PREVIOUS_FIRM_TYPE,AGE_SEGMENT,AGE_SEGMENT_ORD,SUSPENDED_IND,ADVISOR_AGE,REP_EMAIL,CBM,BRANCH_ADDRESS1,BRANCH_ADDRESS2,BRANCH_CITY,BRANCH_POSTAL_CODE,BRANCH_NRD)
select rdv.HK_HUB,
TO_DATE(''||i_DATA_START_DATE||'', ''''YYYY-MM-DD''''),
rdv.HK_HUB,
CURRENT_TIMESTAMP,
''''-1'''',
rdv.MD_SOURCE,
rdv.MD_SRC_SYSTEM,
rdv.MD_EXTRACT_DT,
lv1.MASTER_CODE,
rdv.COMPANY_CODE,
rdv.COMPANY_NAME,
rdv.REGULATORY_ORGANIZATION_NAME,
rdv.REGULATORY_ORGANIZATION_CODE,
rdv.DEALER_CODE,
rdv.DEALER_NAME,
rdv.REGION_CODE,
rdv.REGION_NAME,
rdv.REGION_VP,
rdv.BRANCHCODE,
rdv.BRANCHNAME,
rdv.TEAM_CODE,
rdv.TEAM_NAME,
rdv.ADVISOR_FULLNAME,
rdv.FIRSTNAME,
rdv.LASTNAME,
rdv.ADVISOR_CORPORATION_NAME,
rdv.STATUS,
rdv.GROUP_RSP_INDICATOR,
rdv.PROVINCE_CODE,
rdv.PROVINCE,
lv3.ADVISOR_AUA_SEGMENT,
lv3.ADVISOR_AUA_SEGMENT_ORDER,
rdv.ADVISOR_START_DATE,
rdv.NEW_ADVISOR,
DATEADD(''''YY'''',1,rdv.ADVISOR_START_DATE),
rdv.DEPARTED_ADVISOR_IND,
rdv.PRIMARY_ROLE,
rdv.END_DATE,
rdv.REASON,
rdv.NEW_FIRM,
rdv.NEW_FIRM_TYPE,
rdv.NEW_FIRM_BACK_OFFICE,
rdv.PRESTIGE_STATUS,
rdv.TRANSITION_PERIOD_END_DATE,
rdv.DEAL_ASSESTS,
rdv.EXPECTED_ASSESTS,
rdv.PREVIOUS_FIRM,
rdv.PREVIOUS_FIRM_TYPE,
rdv.AGE_SEGMENT,
rdv.AGE_SEGMENT_ORD,
lv3.SUSPENDED_IND,
rdv.ADVISOR_AGE,
rdv.REP_EMAIL,
rdv.CBM,
rdv.BRANCH_ADDRESS1,
rdv.BRANCH_ADDRESS2,
rdv.BRANCH_CITY,
rdv.BRANCH_POSTAL_CODE,
rdv.BRANCH_NRD
	FROM (
		SELECT *
		FROM DB_IAW_''||ENV||''_DWH.SHARED_BDV.SAT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH
		) rdv
		JOIN (
		SELECT *
		FROM (
			SELECT *
				,ROW_NUMBER() OVER (
					PARTITION BY HK_HUB ORDER BY MD_START_DT DESC
					) RN
			FROM DB_IAW_''||ENV||''_DWH.SHARED_BDV.SAT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH lv
            WHERE lv.MD_START_DT <= TO_DATE(''||i_DATA_START_DATE||'', ''''YYYY-MM-DD'''')
			) SATHUB
		WHERE SATHUB.RN = 1
		) lv ON lv.HK_HUB = rdv.HK_HUB  AND lv.MD_ACTIVE =''''A'''' AND lv.MD_START_DT  = rdv.MD_START_DT 
	JOIN DB_IAW_''||ENV||''_DWH.SHARED_BDV.HUB_PARTY_ROLE_ADVISOR lv1 ON lv1.HK_HUB = rdv.HK_HUB
	LEFT JOIN (
		SELECT rdv2.*
		FROM (
			SELECT *
			FROM DB_IAW_''||ENV||''_DWH.SHARED_BDV.SAT_PARTY_ROLE_ADVISOR_AUA_SEG_COMPUTE
			) rdv2
			JOIN (
			SELECT *
			FROM (
				SELECT *
					,ROW_NUMBER() OVER (
						PARTITION BY HK_HUB ORDER BY MD_START_DT DESC
						) RN1
				FROM DB_IAW_''||ENV||''_DWH.SHARED_BDV.SAT_PARTY_ROLE_ADVISOR_AUA_SEG_COMPUTE lv2
				WHERE lv2.MD_START_DT <= TO_DATE(''||i_DATA_START_DATE||'', ''''YYYY-MM-DD'''')
				) SATHUB1
			WHERE SATHUB1.RN1 = 1
			) lv2 ON lv2.HK_HUB = rdv2.HK_HUB  AND rdv2.MD_ACTIVE =''''A'''' AND lv2.MD_START_DT = rdv2.MD_START_DT
		) lv3 ON lv3.HK_HUB = rdv.HK_HUB
		WHERE lv3.ADVISOR_AUA_SEGMENT != ''''0''''
		'';
INS_UPDATE :=''UPDATE DB_IAW_''||ENV||''_DM.SHARED.WT_DIM_ADVISOR
SET
	MD_HASHDIFF_TYPE2=SHA1(
				CONCAT(
				COALESCE(COMPANY_CODE,''''#NULL#''''), ''''|'''',
				COALESCE(COMPANY_NAME,''''#NULL#''''), ''''|'''',
				COALESCE(REGULATORY_ORGANIZATION_NAME,''''#NULL#'''') ,''''|'''',
				COALESCE(REGULATORY_ORGANIZATION_CODE,''''#NULL#''''), ''''|'''',
				COALESCE(DEALER_CODE,''''#NULL#''''), ''''|'''',
				COALESCE(DEALER_NAME,''''#NULL#''''), ''''|'''',
				COALESCE(REGION_CODE,''''#NULL#''''), ''''|'''',
				COALESCE(REGION_NAME,''''#NULL#'''') ,''''|'''',
				COALESCE(REGION_VP,''''#NULL#''''), ''''|'''',
				COALESCE(BRANCHCODE,''''#NULL#''''), ''''|'''',
				COALESCE(BRANCHNAME,''''#NULL#''''), ''''|'''',
				COALESCE(TO_VARCHAR(TEAM_CODE),''''#NULL#''''), ''''|'''',
				COALESCE(TEAM_NAME,''''#NULL#'''') ,''''|'''',
				COALESCE(ADVISOR_FULLNAME,''''#NULL#''''), ''''|'''',
				COALESCE(FIRSTNAME,''''#NULL#''''), ''''|'''',
				COALESCE(LASTNAME,''''#NULL#''''), ''''|'''',
				COALESCE(ADVISOR_CORPORATION_NAME,''''#NULL#''''), ''''|'''',
				COALESCE(TO_VARCHAR(STATUS),''''#NULL#'''') ,''''|'''',
				COALESCE(GROUP_RSP_INDICATOR,''''#NULL#''''), ''''|'''',
				COALESCE(PROVINCE_CODE,''''#NULL#''''), ''''|'''',
				COALESCE(PROVINCE,''''#NULL#''''), ''''|'''',
				COALESCE(ADVISOR_AUA_SEGMENT,''''#NULL#''''), ''''|'''',
				COALESCE(TO_VARCHAR(ADVISOR_AUA_SEGMENT_ORDER),''''#NULL#'''') ,''''|'''',
				COALESCE(TO_VARCHAR(ADVISOR_START_DATE),''''#NULL#''''), ''''|'''',
				COALESCE(TO_VARCHAR(NEW_ADVISOR),''''#NULL#''''), ''''|'''',
				COALESCE(TO_VARCHAR(DEPARTED_ADVISOR_IND),''''#NULL#''''), ''''|'''',
				COALESCE(PRIMARY_ROLE,''''#NULL#'''')
				,''''|'''',COALESCE(TRIM(AGE_SEGMENT),''''#NULL#'''')
				,''''|'''',COALESCE(TRIM(AGE_SEGMENT_ORD),''''#NULL#'''')
				,''''|'''',COALESCE(TO_VARCHAR(SUSPENDED_IND),''''#NULL#'''')
				,''''|'''',COALESCE(TO_VARCHAR(ADVISOR_AGE),''''#NULL#'''')
,''''|'''',COALESCE(REP_EMAIL,''''#NULL#'''')
,''''|'''',COALESCE(CBM,''''#NULL#'''')
,''''|'''',COALESCE(BRANCH_ADDRESS1,''''#NULL#'''')
,''''|'''',COALESCE(BRANCH_ADDRESS2,''''#NULL#'''')
,''''|'''',COALESCE(BRANCH_CITY,''''#NULL#'''')
,''''|'''',COALESCE(BRANCH_POSTAL_CODE,''''#NULL#'''')
,''''|'''',COALESCE(BRANCH_NRD,''''#NULL#'''')
				)),
	MD_HASHDIFF_TYPE1 = SHA1(
				CONCAT(COALESCE(TRIM(TO_VARCHAR(END_DATE)),''''#NULL#''''), ''''|''''
				,  COALESCE(to_varchar(REASON) , ''''#NULL#''''), ''''|''''
				,  COALESCE(to_varchar(NEW_FIRM) , ''''#NULL#''''), ''''|''''
				,  COALESCE(to_varchar(NEW_FIRM_TYPE) , ''''#NULL#''''), ''''|''''
				,  COALESCE(to_varchar(NEW_FIRM_BACK_OFFICE) , ''''#NULL#''''), ''''|''''
				,  COALESCE(to_varchar(PRESTIGE_STATUS) , ''''#NULL#''''), ''''|''''
				,  COALESCE(to_varchar(TRANSITION_PERIOD_END_DATE) , ''''#NULL#''''), ''''|''''
				,  COALESCE(to_varchar(DEAL_ASSESTS) , ''''#NULL#''''), ''''|''''
				,  COALESCE(to_varchar(EXPECTED_ASSESTS) , ''''#NULL#''''), ''''|''''
				,  COALESCE(PREVIOUS_FIRM , ''''#NULL#''''), ''''|''''
				,  COALESCE(PREVIOUS_FIRM_TYPE, ''''#NULL#'''')				
				))
Where HK_HUB <> ''''0'''';
	'';
EXECUTE IMMEDIATE :INS_PRE_DEL;
EXECUTE IMMEDIATE :INS_INSERT;
EXECUTE IMMEDIATE :INS_UPDATE;
END
';

create or replace TABLE DB_IAW_#env#_DM.TRANSACTIONS.FACT_TRANSACTIONS (
	ID NUMBER(38,0) autoincrement COMMENT 'Surrogate key of the dimension',
	HK_LINK VARCHAR(40) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_SECURITY_TYPE VARCHAR(1000) COMMENT 'Capabilities for RLS',
	SK_DIM_CLIENTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_CLIENTS',
	SK_DIM_ADVISORS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_ADVISORS',
	SK_DIM_PLANS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_PLANS',
	SK_DIM_MARKETPRODUCTS NUMBER(38,0) COMMENT 'Surrogate key of the dimension DIM_MARKETPRODUCTS',
	TRADE_DATE TIMESTAMP_NTZ(9) COMMENT 'Transaction Trade date',
	GROSS_AMOUNT NUMBER(38,12) COMMENT 'Gross amount value',
	CASH_FLOW VARCHAR(16777216) COMMENT 'CASH FLOW indicator (yes, no or Unknown)',
	CASH_FLOW_TYPE VARCHAR(8) COMMENT 'Cash flow type ex: INFLOW, OUTFLOW, etc..',
	ADMINISTRATORY_TYPE VARCHAR(8000) COMMENT 'ADMINISTRATORY TYPE',
	DEPARTED_ADVISOR_IND NUMBER(1,0) COMMENT 'DEPARTED ADVISOR INDICATOR ',
	DAYS_LAST_PRICED NUMBER(4,0),
	TRANSACTION_ID VARCHAR(100) COMMENT 'The ID of the transaction',
	SK_DEPARTED_ADVISOR NUMBER(38,0),
	SK_DIM_ACCOUNTS NUMBER(38,0),
	A_C_REPRESENTATIVE VARCHAR(50),
	DEPARTED_ADVISOR_12M_IND NUMBER(1,0) COMMENT 'Departed advisor''s indicator for the last 12 months'
);

create or replace view DB_IAW_#env#_DM.TRANSACTIONS.VW_FACT_TRANSACTIONS(
	ID,
	SK_DIM_CLIENTS,
	SK_DIM_ADVISORS,
	SK_DIM_PLANS,
	SK_DIM_MARKETPRODUCTS,
	"Trade date",
	"Gross amount",
	CASH_FLOW,
	CASH_FLOW_TYPE,
	"Administratory type",
	"Departed advisor indicator",
	MD_SRCSYSTEM,
	SK_DEPARTED_ADVISOR,
	"Rep code",
	"Advisor indicator 12 months"
) as 
SELECT  
    ID ,
    SK_DIM_CLIENTS ,
    SK_DIM_ADVISORS ,
    SK_DIM_PLANS ,
    SK_DIM_MARKETPRODUCTS ,
    TRADE_DATE  AS "Trade date",
    GROSS_AMOUNT AS "Gross amount",
    CASH_FLOW ,
    CASH_FLOW_TYPE ,
    ADMINISTRATORY_TYPE AS "Administratory type",
    DEPARTED_ADVISOR_IND  AS "Departed advisor indicator",
    MD_SRC_SYSTEM  AS MD_SRCSYSTEM,
    SK_DEPARTED_ADVISOR,
    A_C_REPRESENTATIVE AS "Rep code",
    DEPARTED_ADVISOR_12M_IND AS "Advisor indicator 12 months"
FROM DB_IAW_#env#_DM.TRANSACTIONS.FACT_TRANSACTIONS
WHERE DATE(TRADE_DATE) >= (SELECT DATE(DATEADD(YEAR, -2,MAX(TRADE_DATE) ))  FROM DB_IAW_#env#_DM.TRANSACTIONS.FACT_TRANSACTIONS)
order by SK_DIM_MARKETPRODUCTS,SK_DIM_ADVISORS,SK_DIM_CLIENTS,SK_DIM_PLANS, SK_DEPARTED_ADVISOR, A_C_REPRESENTATIVE;
create or replace view DB_IAW_#env#_DM.TRANSACTIONS.VW_INITIAL_LOADING_WT_FACT_TRANSACTIONS(
	MD_START_DT,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	MD_EXTRACT_DT,
	HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	HK_HUB_PARTY_ROLE_ADVISOR,
	HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
	HK_HUB_INVESTMENT_PRODUCT_TYPE,
	SK_DIM_CLIENTS,
	SK_DIM_ADVISORS,
	SK_DIM_PLANS,
	SK_DIM_MARKETPRODUCTS,
	TRADE_DATE,
	GROSS_AMOUNT,
	CASH_FLOW,
	CASH_FLOW_TYPE,
	ADMINISTRATORY_TYPE,
	DEPARTED_ADVISOR_IND,
	DAYS_LAST_PRICED,
	TRANSACTION_ID,
	SK_DEPARTED_ADVISOR,
	SK_DIM_ACCOUNTS,
	A_C_REPRESENTATIVE
) as
SELECT
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_SOURCE,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_SRC_SYSTEM,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_EXTRACT_DT,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.HK_HUB_PARTY_ROLE_ADVISOR,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.HK_HUB_INVESTMENT_PRODUCT_TYPE,
	CAST(CAST(
	(CASE WHEN SHARED.DIM_CLIENTS.ID IS NULL THEN -1
	ELSE SHARED.DIM_CLIENTS.ID
END) AS VARCHAR(252)) AS FLOAT) AS SK_DIM_CLIENTS,
	CAST(CAST(
	(CASE WHEN SHARED.DIM_ADVISOR.ID IS NULL THEN -1
	ELSE SHARED.DIM_ADVISOR.ID
END) AS VARCHAR(252)) AS FLOAT) AS SK_DIM_ADVISORS,
	CAST(CAST(
	(CASE WHEN SHARED.DIM_PLANS.ID IS NULL THEN -1
	ELSE SHARED.DIM_PLANS.ID
END) AS VARCHAR(251)) AS FLOAT) SK_DIM_PLANS,
	CAST(CAST(
	(CASE WHEN SHARED.DIM_FINANCIAL_INSTRUMENTS.ID IS NULL THEN -1
	ELSE SHARED.DIM_FINANCIAL_INSTRUMENTS.ID
END) AS VARCHAR(252)) AS FLOAT) SK_DIM_MARKETPRODUCTS,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.TRADE_DATE,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.GROSS_AMOUNT,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.CASH_FLOW,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.CASH_FLOW_TYPE,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.ADMINISTRATORY_TYPE,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.DEPARTED_ADVISOR_IND,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.DAYS_LAST_PRICED,
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.TRANSACTION_ID,
	CAST(CAST(
	(CASE WHEN DIM_DEPARTED_ADVISOR.ID IS NULL THEN -1
	ELSE DIM_DEPARTED_ADVISOR.ID
END) AS VARCHAR(252)) AS FLOAT),
	CAST(CAST(
	(CASE WHEN DB_IAW_#env#_DM.SHARED.DIM_ACCOUNTS.ID IS NULL THEN -1
	ELSE DB_IAW_#env#_DM.SHARED.DIM_ACCOUNTS.ID
END) AS VARCHAR(251)) AS FLOAT),
	DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.A_C_REPRESENTATIVE
FROM
	(--DB_IAW_#env#_DM.SHARED.DIM_ADVISOR DIM_DEPARTED_ADVISOR
	(SELECT MASTER_CODE, MAX(ID) AS ID FROM DB_IAW_#env#_DM.SHARED.DIM_ADVISOR WHERE MD_SRC_SYSTEM = 'IAS' GROUP BY MASTER_CODE ) DIM_DEPARTED_ADVISOR
RIGHT OUTER JOIN (DB_IAW_#env#_DM.SHARED.DIM_ACCOUNTS
RIGHT OUTER JOIN (DB_IAW_#env#_DM.SHARED.DIM_CLIENTS
RIGHT OUTER JOIN (DB_IAW_#env#_DM.SHARED.DIM_PLANS
RIGHT OUTER JOIN (DB_IAW_#env#_DM.SHARED.DIM_ADVISOR
RIGHT OUTER JOIN (DB_IAW_#env#_DM.SHARED.DIM_FINANCIAL_INSTRUMENTS
RIGHT OUTER JOIN DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION ON
	(DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.HK_HUB_INVESTMENT_PRODUCT_TYPE = DB_IAW_#env#_DM.SHARED.DIM_FINANCIAL_INSTRUMENTS.HK_HUB)
	AND ((DB_IAW_#env#_DM.SHARED.DIM_FINANCIAL_INSTRUMENTS.MD_START_DT <= DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
		AND ((DB_IAW_#env#_DM.SHARED.DIM_FINANCIAL_INSTRUMENTS.MD_END_DT > DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
			OR DB_IAW_#env#_DM.SHARED.DIM_FINANCIAL_INSTRUMENTS.MD_END_DT IS NULL))) ON
	(DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.HK_HUB_PARTY_ROLE_ADVISOR = DB_IAW_#env#_DM.SHARED.DIM_ADVISOR.HK_HUB)
	AND ((DB_IAW_#env#_DM.SHARED.DIM_ADVISOR.MD_START_DT <= DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
		AND ((DB_IAW_#env#_DM.SHARED.DIM_ADVISOR.MD_END_DT > DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
			OR DB_IAW_#env#_DM.SHARED.DIM_ADVISOR.MD_END_DT IS NULL))) ON
	(DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES = DB_IAW_#env#_DM.SHARED.DIM_PLANS.HK_HUB)
	AND ((DB_IAW_#env#_DM.SHARED.DIM_PLANS.MD_START_DT <= DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
		AND ((DB_IAW_#env#_DM.SHARED.DIM_PLANS.MD_END_DT > DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
			OR DB_IAW_#env#_DM.SHARED.DIM_PLANS.MD_END_DT IS NULL))) ON
	(DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER = DB_IAW_#env#_DM.SHARED.DIM_CLIENTS.HK_HUB)
	AND ((DB_IAW_#env#_DM.SHARED.DIM_CLIENTS.MD_START_DT <= DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
		AND ((DB_IAW_#env#_DM.SHARED.DIM_CLIENTS.MD_END_DT > DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
			OR DB_IAW_#env#_DM.SHARED.DIM_CLIENTS.MD_END_DT IS NULL))) ON
	(DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.HK_HUB_CONTRACT = DB_IAW_#env#_DM.SHARED.DIM_ACCOUNTS.HK_HUB)
	AND ((DB_IAW_#env#_DM.SHARED.DIM_ACCOUNTS.MD_START_DT <= DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
		AND ((DB_IAW_#env#_DM.SHARED.DIM_ACCOUNTS.MD_END_DT > DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.MD_START_DT)
			OR DB_IAW_#env#_DM.SHARED.DIM_ACCOUNTS.MD_END_DT IS NULL))) ON
	(DB_IAW_#env#_DWH.TRANSACTIONS_BDV.TRANSLINK_FINANCIAL_TRANSACTION.DEPARTED_ADVISOR_MASTER_CODE = DIM_DEPARTED_ADVISOR.MASTER_CODE)
	);

-- datawarehouse

create or replace TABLE DB_IAW_#env#_DWH.HOLDINGS_BDV.SAT_LINK_INVESTMENT (
	HK_LINK VARCHAR(40) COMMENT 'Hash key for the Link',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_HASHDIFF VARCHAR(64) COMMENT 'Represents the whole set of hashed attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_ACTIVE VARCHAR(1) COMMENT 'Active Flag, \"A\" row exists in the source, \"D\" row does not exist in the source',
	RR_CD VARCHAR(50) COMMENT 'Advisor RR code',
	PLN_SYSID VARCHAR(1000) COMMENT 'Its the plan system id',
	BALANCE_DATE TIMESTAMP_NTZ(9) COMMENT 'Holding balance date',
	HOLDING_VALUE NUMBER(38,9) COMMENT 'Holding amount',
	AUA NUMBER(38,12) COMMENT 'AUA ammount',
	AUM NUMBER(38,12) COMMENT 'Number of AUM',
	AUM_CLARINGTON NUMBER(38,12) COMMENT 'Clarington AUM',
	AUM_IA NUMBER(38,12) COMMENT 'IA AUM',
	CASH_POSITION NUMBER(38,12) COMMENT ' CASH value at that point of time',
	PROGRAM_TYPE VARCHAR(50) COMMENT 'Programe type',
	ACCOUNT_PROGRAM_TYPE VARCHAR(50) COMMENT 'Account of the Program',
	ADMINISTRATORY_TYPE VARCHAR(1000) COMMENT 'Type of Admistratory',
	AUA_ACCRUED_INTEREST NUMBER(38,2)
);


CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DWH.HOLDINGS_BDV.SP_CONV_LOADBDV_VW_INITIAL_LOADING_INVESTMENT_CASH_TO_WT_INVESTMENT_CASH("ENV" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS ' 
var trunc_query = "TRUNCATE table DB_IAW_<env>_DWH.HOLDINGS_BDV.WT_INVESTMENT_CASH_IAS_NBIN";
var trunc_query_ENV = trunc_query.replaceAll("_<env>_","_"+ ENV + "_");
var sql_statement1 = snowflake.createStatement({
  sqlText: trunc_query_ENV
});
var result1_scan = sql_statement1.execute(); 
INS_QUERY = "INSERT INTO  DB_IAW_<env>_DWH.HOLDINGS_BDV.WT_INVESTMENT_CASH_IAS_NBIN (HK_LINK, "+
"HK_HUB_CONTRACT, "+
"HK_HUB_INVESTMENT_PRODUCT_TYPE, "+
"HK_HUB_PARTY_ROLE_ADVISOR, "+
"HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, "+
"HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES, "+
"MD_SEQ, "+
"MD_START_DT, "+
"MD_CREATION_DT, "+
"MD_EXTRACT_DT, "+
"MD_SOURCE, "+
"MD_SRC_SYSTEM, "+
"A_C_SUMM_SD_NET_AMT, "+
"A_C_SUMM_TD_NET_AMT, "+
"A_C_SUMM_BALANCE_BUS_DATE, "+
"CONTRACT_ID, "+
"RR_CD, "+
"INVESTMENT_PRODUCT_ID, "+
"MASTER_CODE, "+
"A_C_CLIENT, "+
"ACCOUNT_RAP_CODE, "+
"ASC_1_RESP_PLAN_TYPES, "+
"RETAIL_PLAN, "+
"A_C_CURRENCY, "+
"COMMISSIONPCT, "+
"ISSUER_COMPANY_NAME, "+
"ASC_3_MANAGED_TYPE, "+
"ADMINISTRATOR_TYPE, "+
"EXCHANGERATE, "+
"A_C_ACCOUNT_CLASS, "+
"RETAIL_PLAN_RESP) (SELECT HK_LINK, "+
"HK_HUB_CONTRACT, "+
"HK_HUB_INVESTMENT_PRODUCT_TYPE, "+
"HK_HUB_PARTY_ROLE_ADVISOR, "+
"HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER, "+
"HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES, "+
"MD_SEQ, "+
"MD_START_DT, "+
"MD_CREATION_DT, "+
"MD_EXTRACT_DT, "+
"MD_SOURCE, "+
"MD_SRC_SYSTEM, "+
"A_C_SUMM_SD_NET_AMT, "+
"A_C_SUMM_TD_NET_AMT, "+
"A_C_SUMM_BALANCE_BUS_DATE, "+
"CONTRACT_ID, "+
"RR_CD, "+
"INVESTMENT_PRODUCT_ID, "+
"MASTER_CODE, "+
"A_C_CLIENT, "+
"ACCOUNT_RAP_CODE, "+
"ASC_1_RESP_PLAN_TYPES, "+
"RETAIL_PLAN, "+
"A_C_CURRENCY, "+
"COMMISSIONPCT, "+
"ISSUE_COMPANY_NAME, "+
"ASC_3_MANAGED_TYPE, "+
"ADMINISTRATOR_TYPE, "+
"EXCHANGERATE, "+
"A_C_ACCOUNT_CLASS, "+
"RETAIL_PLAN_RESP FROM DB_IAW_<env>_DWH.HOLDINGS_BDV.VW_INITIAL_LOADING_INVESTMENT_CASH_IAS_NBIN) "
;
var INS_QUERY_ENV = INS_QUERY.replaceAll("_<env>_","_"+ ENV + "_");
var sql_statement2 = snowflake.createStatement({
  sqlText: INS_QUERY_ENV
});
 var result2_scan = sql_statement2.execute(); 
';
CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DWH.HOLDINGS_BDV.SP_CONV_LOADBDV_VW_INITIAL_LOADING_INVESTMENT_TO_WT_INVESTMENT("ENV" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS ' 
var delete_query = "DELETE FROM DB_IAW_<env>_DWH.HOLDINGS_BDV.WT_INVESTMENT_INVESTIA_UNIVERIS WHERE 1=1";
var delete_query_ENV = delete_query.replaceAll("_<env>_","_"+ ENV + "_");
var sql_statement1 = snowflake.createStatement({
  sqlText: delete_query_ENV
});
var result1_scan = sql_statement1.execute(); 
INS_QUERY = "INSERT INTO DB_IAW_<env>_DWH.HOLDINGS_BDV.WT_INVESTMENT_INVESTIA_UNIVERIS(HK_HUB_CONTRACT, " +
"HK_HUB_INVESTMENT_PRODUCT_TYPE , " +
"HK_HUB_PARTY_ROLE_ADVISOR	,  " +
"HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER	, " + 
"HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES	 , " +
"MD_SEQ	, " +
"MD_START_DT	, " +
"MD_EXTRACT_DT	, " +
"MD_SOURCE	, " +
"MD_SRC_SYSTEM	, " +
"CONTRACT_ID	, " +
"INVESTMENT_PRODUCT_ID	, " +
"MASTER_CODE	, " +
"RR_CD	, " +
" CLIENT_ID	, " +
"PLN_MNEM	, " +
"COMMISSIONPCT	, " +
"ISSUER_COMPANY_NAME	, " +
" ADMINISTRATORY_TYPE, " +
"BAL_DATE	, " +
"MV	, " +
"AUA	, " +
"UNIVERIS_PLAN_ID	, " +
"IVD_LOAD_FLAG	,  " +
"WF_IND	 ) " +
"(select " +
"HK_HUB_CONTRACT, " +
"HK_HUB_INVESTMENT_PRODUCT_TYPE , " +
"HK_HUB_PARTY_ROLE_ADVISOR	,  " +
"HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER	,  " +
"HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES	 , " +
"MD_SEQ	, " +
"MD_START_DT	, " +
"MD_EXTRACT_DT	, " +
"MD_SOURCE	, " +
"MD_SRC_SYSTEM	, " +
"CONTRACT_ID	, " +
"INVESTMENT_PRODUCT_ID	, " +
"MASTER_CODE	, " +
"RR_CD	, " +
"UNIVERIS_CLIENT_ID 	, " +
"PLN_MNEM	, " +
"COMMISSIONPCT	, " +
"ISSUER_COMPANY_NAME	, " +
"ADMINISTRATOR_TYPE, " +
"BAL_DATE	, " +
"MV	, " +
"AUA	, " +
"UNIVERIS_PLAN_ID	, " +
"IVD_LOAD_FLAG	, " +
"WF_IND	 " +
"FROM DB_IAW_<env>_DWH.HOLDINGS_BDV.VW_INITIAL_LOADING_INVESTMENT_INVESTIA_UNIVERIS);" 
var INS_QUERY_ENV = INS_QUERY.replaceAll("_<env>_","_"+ ENV + "_");
var sql_statement2 = snowflake.createStatement({
  sqlText: INS_QUERY_ENV
});
 var result2_scan = sql_statement2.execute(); 
 var update_query = "UPDATE DB_IAW_<env>_DWH.HOLDINGS_BDV.WT_INVESTMENT_INVESTIA_UNIVERIS "+
"SET "+
"HK_LINK = SHA1(UPPER(CONCAT( "+
"      COALESCE(TRIM(MD_SEQ), ''#NULL#''), ''|'' "+
"    , COALESCE(TRIM(MD_SOURCE), ''#NULL#''), ''|'' "+
"    , COALESCE(TRIM(MD_SRC_SYSTEM), ''#NULL#''), ''|'' "+
"    , COALESCE(TRIM(MD_EXTRACT_DT), ''#NULL#''), ''|'' "+
"    , ''#NULL#'', ''|''   "+
"    , COALESCE(TRIM(MASTER_CODE), ''#NULL#''), ''|'' "+
"    , COALESCE(TRIM(INVESTMENT_PRODUCT_ID), ''#NULL#''), ''|'' "+
"    , COALESCE(TRIM(CLIENT_ID), ''#NULL#''), ''|'' "+
"    , COALESCE(TRIM(PLN_MNEM), ''#NULL#''), ''|'' "+
"    , ''#NULL#'', ''|'' "+
"    , ''#NULL#'', ''|'' "+
"    , ''#NULL#'', ''|'' "+
 "   , COALESCE(TRIM(UNIVERIS_PLAN_ID), ''#NULL#'')"+
 "   ))),"+
"HK_HUB_PARTY_ROLE_ADVISOR= COALESCE(HK_HUB_PARTY_ROLE_ADVISOR,''0''),"+
"HK_HUB_INVESTMENT_PRODUCT_TYPE= COALESCE(HK_HUB_INVESTMENT_PRODUCT_TYPE,''0''),"+
"HK_HUB_CONTRACT= COALESCE(HK_HUB_CONTRACT,''0''),"+
"HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER = COALESCE(HK_HUB_PARTY_ROLE_ACCOUNT_HOLDER,''0''),"+
"HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES = COALESCE(HK_HUB_INVESTMENT_SAVING_PROGRAM_TYPES,''0''),"+
"MD_CREATION_DT = SYSTIMESTAMP() "+
"Where 1=1";
var update_query_ENV = update_query.replaceAll("_<env>_","_" + ENV + "_");
var sql_statement3 = snowflake.createStatement({ 
  sqlText: update_query_ENV
});
 var result3_scan = sql_statement3.execute(); 
';
CREATE OR REPLACE PROCEDURE DB_IAW_#env#_DWH.HOLDINGS_BDV.SP_CONV_LOADSTG_STG_IAS_COMMISSION_TO_DM_EXPLORATION_REVENUES("ENV" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS ' 
var delete_query = "DELETE FROM DB_IAW_<env>_DM.EXPOLORATION.IAS_COMMISSION_REVENUES WHERE 1=1";
var delete_query_ENV = delete_query.replaceAll("_<env>_","_"+ ENV + "_");
var sql_statement1 = snowflake.createStatement({
  sqlText: delete_query_ENV
});
var result1_scan = sql_statement1.execute(); 
INS_QUERY = "INSERT INTO DB_IAW_<env>_DM.EXPOLORATION.IAS_COMMISSION_REVENUES("HK_LINK , " +
"HK_HUB_CONTRACT	, " +
"HK_HUB_PARTY_ROLE_ADVISOR	, " +	
"MD_CREATION_DT	, " +
"MD_START_DT	, " +
"MD_SOURCE	, " +
"MD_SRC_SYSTEM	, " +
"MD_EXTRACT_DT	, " +	
"REPID	, " +
"ADVISOR_ID	, " +	
"PROGRAM_TYPE	, " +
"ACCOUNTID	, " +
"PROCESSDATE	, " +	
"SOURCECODE		, " +
"QUANTITY	, " +	
"TRANSTYPE	, " +	
"REVENUE	, " +	
"COMMISSION		, " +
"NETCOMMISSION	, " +	
"TRANSFEE) " +
"(select " +
"HK_LINK , " +
"HK_HUB_CONTRACT	, " +
"HK_HUB_PARTY_ROLE_ADVISOR	, " +	
"MD_CREATION_DT	, " +
"MD_START_DT	, " +
"MD_SOURCE	, " +
"MD_SRC_SYSTEM	, " +
"MD_EXTRACT_DT	, " +	
"REPID	, " +
"ADVISOR_ID	, " +	
"PROGRAM_TYPE	, " +
"ACCOUNTID	, " +
"PROCESSDATE	, " +	
"SOURCECODE		, " +
"QUANTITY	, " +	
"TRANSTYPE	, " +	
"REVENUE	, " +	
"COMMISSION		, " +
"NETCOMMISSION	, " +	
"TRANSFEE " +
"FROM DB_IAW_<env>_STG.IAS_COMMISSION.REVENUES);" 
var INS_QUERY_ENV = INS_QUERY.replaceAll("_<env>_","_"+ ENV + "_");
var sql_statement2 = snowflake.createStatement({
  sqlText: INS_QUERY_ENV
});
 var result2_scan = sql_statement2.execute(); 
 
';

-- missing PROC_DT TIMESTAMP_NTZ(9)
create or replace TABLE DB_IAW_#env#_DWH.REVENUES_RDV.SAT_LINK_REVENUE_PAYABLE_RR_IAS_UNIVERIS (
	HK_LINK VARCHAR(40) COMMENT 'Hash key for the Link',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_HASHDIFF VARCHAR(64) COMMENT 'Represents the whole set of hashed attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_ACTIVE VARCHAR(1) COMMENT 'Active Flag, \"A\" row exists in the source, \"D\" row does not exist in the source',
	PYBL_STATUS VARCHAR(3) COMMENT 'Payable Status',
	EVENT_PROC_SYSID NUMBER(38,0) COMMENT 'Event Procedure ID',
	EVENT_RPT_SYSID NUMBER(38,0) COMMENT 'Event Report ID',
	BEN_SYSID NUMBER(38,0) COMMENT 'Beneficiary ID (related to REP table)',
	REP_SYSID NUMBER(38,0) COMMENT 'Advisor ID (related to REP table)',
	DEAL_SYSID NUMBER(38,0) COMMENT 'Deal ID (related to REP_DEAL link with parent REP table)',
	COM_SYSID NUMBER(38,0) COMMENT 'Comm ID (Related to REP_COM link with parents REP_DEAL, REP)',
	DIST_SYSID NUMBER(38,0) COMMENT 'Payroll Distribution ID (related to REP_PAY_DIST)',
	TRX_SYSID NUMBER(38,0) COMMENT 'Transaction ID (related to TRX)',
	ACT_SYSID NUMBER(38,0) COMMENT 'Account (Position) ID (related to ACT)',
	MGT_CD VARCHAR(5) COMMENT 'Managemet Cie ID (related to MGT)',
	TRX_CD NUMBER(38,0) COMMENT 'Transaction Code id (related to S_TRX_CD)',
	PAY_PERIOD VARCHAR(5) COMMENT 'Pay Period',
	TAX_YEAR VARCHAR(4) COMMENT 'Pay Fiscal Year',
	TRADE_DT TIMESTAMP_NTZ(9) COMMENT 'Transaction Trade date (related to TRX)',
	GRSS_AMT FLOAT COMMENT 'Transaction Gross Amount (related to TRX)',
	COM_DLR FLOAT COMMENT 'Commission Dealer Amount',
	COM_PYBL FLOAT COMMENT 'Commission Amount',
	COM_BEN_PYBL FLOAT COMMENT 'Commission Pay to the Beneficiary',
	TICKET_CHG FLOAT COMMENT 'Ticket Charge',
	PAY_CD VARCHAR(3) COMMENT 'Pay Code',
	COM_PRODUCTION_CD VARCHAR(2) COMMENT 'Commission Type Code (related to S_COM_PROD)',
	AMOUNT FLOAT COMMENT 'Amount (related to Payroll Distribution)',
	USR_SYSID NUMBER(38,0) COMMENT 'User ID (related to SYS_USER_CD)',
	OTX_SYSID NUMBER(38,0) COMMENT 'Order ID (related to OTX)',
	DISPLAY_FLAG NUMBER(38,0) COMMENT 'Display Flag',
	DLR_MINIMUM VARCHAR(1) COMMENT 'Dealer Minimum',
	ORIG_PAY_PER VARCHAR(18) COMMENT 'Original Pay Period',
	IVT_TYPE VARCHAR(4) COMMENT 'Type of Product',
	COM_PAY_SYSID NUMBER(38,0) COMMENT 'Commission Pay ID',
	INTERNAL_COMM BOOLEAN COMMENT 'Internal Commission',
	WRHS_IND BOOLEAN COMMENT 'WRHS IND'
);


--table does not exist
create or replace TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_IAS_NBIN_REF_INVESTMENT_SAVING_PROGRAM_TYPES_COMPUTE (
	HK_HUB VARCHAR(40) COMMENT 'Hash key for the Sat',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_HASHDIFF VARCHAR(64) COMMENT 'Represents the whole set of hashed attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_ACTIVE VARCHAR(1) COMMENT 'Active Flag, \"A\" row exists in the source, \"D\" row does not exist in the source',
	PLAN_CODE VARCHAR(8000) COMMENT 'Plan Code',
	PLAN_LABEL VARCHAR(8000) COMMENT 'Plan label',
	ACCOUNT_TYPE VARCHAR(16777216) COMMENT 'Account type',
	GROUP_TYPE_CODE VARCHAR(8000) COMMENT 'Group type code',
	ACCUMULATION_TYPE VARCHAR(8000) COMMENT 'Type of Accumulation'
);

-- missing comments
create or replace TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_INVESTMENT_PRODUCT_TYPE_COMPUTE (
	HK_HUB VARCHAR(64) COMMENT 'Hash key for the Sat',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_HASHDIFF VARCHAR(64) COMMENT 'Represents the whole set of hashed attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_ACTIVE VARCHAR(1) COMMENT 'Active Flag, \"A\" row exists in the source, \"D\" row does not exist in the source',
	SYMBOL VARCHAR(512) COMMENT 'Security Symbol',
	NAME VARCHAR(1000) ,
	ASSET_CATEGORY VARCHAR(512) COMMENT 'Under what category the asset belongs to',
	CATEGORY VARCHAR(512) COMMENT 'Type of Category',
	PRODUCT_GROUP VARCHAR(512) COMMENT 'The group the product belong to',
	ISSUER_COMPANY_CODE VARCHAR(4) COMMENT 'Code of the issuer Company',
	ISSUER_COMPANY_NAME VARCHAR(1000) COMMENT 'Name of the issuer Company'
);

-- missing comments
alter table TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_SHARE
alter
	COM_TYPE VARCHAR(50) COMMENT 'Commission Type',
	COMMISSIONPCT NUMBER(6,3) COMMENT 'Commission Sharing Percentage',
	IS_RESHARED NUMBER(7,3) COMMENT 'Indicator to identify IsReshared or not',
	PHYSICAL NUMBER(7,3) COMMENT 'PHYSICAL number',
	TOREPID VARCHAR(50) COMMENT 'Advisor id'

--reorder column

create or replace TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH (
	HK_HUB VARCHAR(64) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_HASHDIFF VARCHAR(64) COMMENT 'Represents the whole set of hashed attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_ACTIVE VARCHAR(1) COMMENT 'Active Flag, \"A\" row exists in the source, \"D\" row does not exist in the source',
	COMPANY_CODE VARCHAR(50) COMMENT 'Code of the company',
	COMPANY_NAME VARCHAR(512) COMMENT 'Name of the company',
	REGULATORY_ORGANIZATION_NAME VARCHAR(512) COMMENT 'Name of the regulatory organisation company',
	REGULATORY_ORGANIZATION_CODE VARCHAR(50) COMMENT 'Code of the regulatory organisation company',
	DEALER_CODE VARCHAR(50) COMMENT 'Code of the dealer',
	DEALER_NAME VARCHAR(512) COMMENT 'Name of the dealer',
	REGION_CODE VARCHAR(512) COMMENT 'Code of the region',
	REGION_NAME VARCHAR(512) COMMENT 'Nmae of the region',
	REGION_VP VARCHAR(16777216) COMMENT 'full name of the RVP',
	BRANCHCODE VARCHAR(50) COMMENT 'Code of the representative branch code',
	BRANCHNAME VARCHAR(512) COMMENT 'Name of the representative branch',
	TEAM_CODE NUMBER(38,0) COMMENT 'Representant Group ID',
	TEAM_NAME VARCHAR(512) COMMENT 'Advisor team description',
	ADVISOR_FULLNAME VARCHAR(512) COMMENT 'Representative name',
	FIRSTNAME VARCHAR(512) COMMENT 'Representative first name',
	LASTNAME VARCHAR(512) COMMENT 'Representative last name',
	ADVISOR_CORPORATION_NAME VARCHAR(512) COMMENT 'Representative corporation name',
	STATUS VARCHAR(512) COMMENT 'Active RR code indicator',
	GROUP_RSP_INDICATOR VARCHAR(512) COMMENT 'Group retirement saving Plans indicator',
	PROVINCE_CODE VARCHAR(16777216) COMMENT 'province code',
	PROVINCE VARCHAR(16777216) COMMENT 'province name',
	ADVISOR_START_DATE TIMESTAMP_NTZ(9) COMMENT 'Advisor Start date',
	NEW_ADVISOR NUMBER(38,0) COMMENT 'Flag to identify the advisor',
	DEPARTED_ADVISOR_IND NUMBER(1,0) COMMENT 'DEPARTED ADVISOR INDICATOR',
	END_DATE TIMESTAMP_NTZ(9) COMMENT 'Departure date of the advisor (TBD)',
	REASON VARCHAR(1000) COMMENT 'Reason of departure',
	NEW_FIRM VARCHAR(1000) COMMENT 'Departure destination',
	NEW_FIRM_TYPE VARCHAR(1000) COMMENT 'Departure destination Type',
	NEW_FIRM_BACK_OFFICE VARCHAR(1000) COMMENT 'Departure destination Back-Office',
	PRESTIGE_STATUS VARCHAR(100) COMMENT 'Prestige Status',
	PRIMARY_ROLE VARCHAR(500) COMMENT 'PRIMARY ROLE',
	TRANSITION_PERIOD_END_DATE TIMESTAMP_NTZ(9) COMMENT 'Advisor transition end date',
	DEAL_ASSESTS NUMBER(11,0) COMMENT 'Deal assets',
	EXPECTED_ASSESTS NUMBER(11,0) COMMENT 'Expected assets',
	PREVIOUS_FIRM VARCHAR(100) COMMENT 'Previous Firm of the Advisor',
	PREVIOUS_FIRM_TYPE VARCHAR(100) COMMENT 'Previous Firm type of the Advisor',
	AGE_SEGMENT VARCHAR(50) COMMENT 'Advisor Age Segment : 25-34',
	AGE_SEGMENT_ORD NUMBER(2,0) COMMENT 'Advisor Age Segment ORDER',
	MD_ACTIVE_CERTS VARCHAR(1) COMMENT 'Active Flag, \"A\" row exists in the source, \"D\" row does not exist in the certs source',
	ADVISOR_AGE NUMBER(38,0) COMMENT 'Age of the dealer',
	REP_EMAIL VARCHAR(1000) COMMENT 'Advisor repemail',
	CBM VARCHAR(1000) COMMENT 'Advisor cbm',
	BRANCH_NRD VARCHAR(1000) COMMENT 'Advisor branch nrd',
	BRANCH_ADDRESS1 VARCHAR(1000) COMMENT 'Advisor branch ADDRESS1',
	BRANCH_ADDRESS2 VARCHAR(1000) COMMENT 'Advisor branch ADDRESS2',
	BRANCH_CITY VARCHAR(1000) COMMENT 'Advisor branch city',
	BRANCH_POSTAL_CODE VARCHAR(1000) COMMENT 'Advisor branch postal code'
);

alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_REF_INVESTMENT_SAVING_PROGRAM_TYPES_COMPUTE
alter column
	PLAN_CODE VARCHAR(8000) COMMENT 'The plan code',
	PLAN_LABEL VARCHAR(8000) COMMENT 'The plan label',
	ACCOUNT_TYPE VARCHAR(8000) COMMENT 'The account type',
	GROUP_TYPE_CODE VARCHAR(8000) COMMENT 'The group type code',
	ACCUMULATION_TYPE VARCHAR(8000) COMMENT 'The accumulation type';

alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_ADVISOR_IAS_CERTS
alter column 
	CID VARCHAR(500) COMMENT 'Source account id  exp: #100002 ',
	FIRST_NAME VARCHAR(500)  COMMENT 'First name of the advisor',
	LAST_NAME VARCHAR(500)  COMMENT 'last name of the advisor',
	FULL_NAME VARCHAR(1000)  COMMENT 'Full name of the advisor',
	PRIMARY_ROLE VARCHAR(500) COMMENT 'Primary role of the advisor',
	RVP VARCHAR(500) COMMENT 'RVP of the advisor',
	BRANCH_NRD VARCHAR(500) COMMENT 'Code of the Branch',
	BRANCH_NAME VARCHAR(500)  COMMENT 'Name of the Branch',
	PROVINCE VARCHAR(500) COMMENT 'Province of the advisor',
	IS_ACTIVE NUMBER(1,0) COMMENT 'Flag to identify the whether the advisor is active or not',
	TRADE_NAME VARCHAR(2000)  COMMENT 'Trade of the advisor',
	PORTAL_IDS VARCHAR(2000) COMMENT 'Portal identifier exp: PortalIds_#118048',
	RR_CD VARCHAR(2000) COMMENT 'Registered representative code';

-- table does not exist
create or replace TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_IAS_NBIN_SAT_REF_INVESTMENT_SAVING_PROGRAM_TYPES_COMPUTE (
	HK_HUB VARCHAR(40) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_HASHDIFF VARCHAR(64) DEFAULT '0' COMMENT 'Represents the whole set of hashed attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	RETAIL_PLAN VARCHAR(50) COMMENT 'Retail plan code : RS, LF, ...',
	ACCOUNT_RAP_CODE VARCHAR(10) COMMENT 'To be defined : Last letter of an account ID',
	PLAN_CODE VARCHAR(8000) COMMENT 'Plan Code',
	PLAN_LABEL VARCHAR(8000) COMMENT 'Plan label',
	ACCOUNT_TYPE VARCHAR(16777216) COMMENT 'Type of Account',
	GROUP_TYPE_CODE VARCHAR(8000) COMMENT 'Group code',
	ACCUMULATION_TYPE VARCHAR(8000) COMMENT 'Accumulation Type',
	ASC_1_RESP_PLAN_TYPES VARCHAR(100) COMMENT 'If Account rap code is the same, ASC_1_RESP_PLAN_TYPES is used to identify the plan'
);

alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE_MC
alter column
	NETCOMMISSIONPCT NUMBER(6,3) COMMENT 'Net Commission Sharing Percentage';
-- reorder columns and add comments

create or replace TABLE DB_IAW_ACCP_DWH.SHARED_BDV.WT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH (
	HK_HUB VARCHAR(64) COMMENT 'Hash key for the Hub',
	MD_START_DT TIMESTAMP_NTZ(9) COMMENT 'Start Date of the image/version',
	MD_EXTRACT_DT TIMESTAMP_NTZ(9) COMMENT 'Source extraction date',
	MD_HASHDIFF VARCHAR(64) COMMENT 'Represents the whole set of hashed attributes to be historized for an occurrence',
	MD_CREATION_DT TIMESTAMP_NTZ(9) COMMENT 'Creation Date Time of the occurrence',
	MD_SOURCE VARCHAR(1000) COMMENT 'Represents the source system, file, etc. of the instance',
	MD_SRC_SYSTEM VARCHAR(100) COMMENT 'Source system',
	MD_CREATION_AUDIT_ID VARCHAR(1000) COMMENT 'Task execution ID',
	MASTER_CODE VARCHAR(50) COMMENT 'Master code of the Advisor',
	COMPANY_CODE VARCHAR(50) COMMENT 'ADVISOR COMPANY CODE ',
	COMPANY_NAME VARCHAR(512) COMMENT 'ADVISOR COMPANY NAME ',
	REGULATORY_ORGANIZATION_NAME VARCHAR(512) COMMENT 'Regulatory Organisation NAME ',
	REGULATORY_ORGANIZATION_CODE VARCHAR(50) COMMENT 'Regulatory Organisation Code ',
	DEALER_CODE VARCHAR(50) COMMENT 'Dealer code',
	DEALER_NAME VARCHAR(512) COMMENT 'Dealer Name',
	REGION_CODE VARCHAR(512) COMMENT 'Region Code',
	REGION_NAME VARCHAR(512) COMMENT 'Region Name',
	REGION_VP VARCHAR(16777216) COMMENT 'Regional VP',
	BRANCHCODE VARCHAR(50) COMMENT 'Branch Code',
	BRANCHNAME VARCHAR(512) COMMENT 'Branch name',
	TEAM_CODE NUMBER(38,0) COMMENT 'Team Code',
	TEAM_NAME VARCHAR(512) COMMENT 'Team name',
	ADVISOR_FULLNAME VARCHAR(512) COMMENT 'Advisor Full name',
	FIRSTNAME VARCHAR(512) COMMENT 'Advisor First name',
	LASTNAME VARCHAR(512) COMMENT 'Advisor Last name',
	ADVISOR_CORPORATION_NAME VARCHAR(512) COMMENT 'Advisor corporation name',
	STATUS VARCHAR(512) COMMENT 'Advisor status',
	GROUP_RSP_INDICATOR VARCHAR(512) COMMENT 'Indiactor to show its Group RSp or not',
	PROVINCE_CODE VARCHAR(16777216) COMMENT 'Code of Province',
	PROVINCE VARCHAR(16777216) COMMENT 'Province',
	ADVISOR_START_DATE TIMESTAMP_NTZ(9) COMMENT 'Start date of the advisor',
	NEW_ADVISOR NUMBER(38,0) COMMENT 'Flag to identify new advisor',
	DEPARTED_ADVISOR_IND NUMBER(1,0) COMMENT 'DEPARTED ADVISOR INDICATOR',
	END_DATE TIMESTAMP_NTZ(9) COMMENT 'Departure date of the advisor (TBD)',
	REASON VARCHAR(1000) COMMENT 'Reason of departure',
	NEW_FIRM VARCHAR(1000) COMMENT 'Departure destination',
	NEW_FIRM_TYPE VARCHAR(1000) COMMENT 'Departure destination Type',
	NEW_FIRM_BACK_OFFICE VARCHAR(1000) COMMENT 'Departure destination Back-Office',
	PRESTIGE_STATUS VARCHAR(100) COMMENT 'Prestige Status',
	PRIMARY_ROLE VARCHAR(500) COMMENT 'Primary role',
	TRANSITION_PERIOD_END_DATE TIMESTAMP_NTZ(9) COMMENT 'Advisor transition end date',
	DEAL_ASSESTS NUMBER(11,0) COMMENT 'Deal assets',
	EXPECTED_ASSESTS NUMBER(11,0) COMMENT 'Expected assets',
	PREVIOUS_FIRM VARCHAR(100) COMMENT 'Previous Firm of the Advisor',
	PREVIOUS_FIRM_TYPE VARCHAR(100) COMMENT 'Previous Firm type of the Advisor',
	AGE_SEGMENT VARCHAR(50) COMMENT 'Advisor Age Segment : 25-34',
	AGE_SEGMENT_ORD NUMBER(2,0) COMMENT 'Advisor Age Segment ORDER',
	MD_ACTIVE_CERTS VARCHAR(1) COMMENT 'Active Flag, \"A\" row exists in the source, \"D\" row does not exist in the certs source',
	ADVISOR_AGE NUMBER(38,0) COMMENT 'Age of the dealer',
	REP_EMAIL VARCHAR(1000) COMMENT 'Advisor repemail',
	CBM VARCHAR(1000) COMMENT 'Advisor cbm',
	BRANCH_NRD VARCHAR(1000) COMMENT 'Advisor branch nrd',
	BRANCH_ADDRESS1 VARCHAR(1000) COMMENT 'Advisor branch ADDRESS1',
	BRANCH_ADDRESS2 VARCHAR(1000) COMMENT 'Advisor branch ADDRESS2',
	BRANCH_CITY VARCHAR(1000) COMMENT 'Advisor branch city',
	BRANCH_POSTAL_CODE VARCHAR(1000) COMMENT 'Advisor branch postal code'
);

alter table DB_IAW_#env#_DWH.SHARED_BDV.WT_REGISTERED_REPRESENTATIVE_IAS_CERTS
alter column
	CID VARCHAR(500) COMMENT 'Source account id exp: #100002',
	FIRST_NAME VARCHAR(500) MASKING POLICY COMMENT 'Advisor First name',
	LAST_NAME VARCHAR(500) MASKING POLICY COMMENT 'Advisor Last name',
	FULL_NAME VARCHAR(1000) MASKING POLICY COMMENT 'Advisor Full name',
	PRIMARY_ROLE VARCHAR(500) COMMENT 'Advisor Primary role',
	RVP VARCHAR(500) COMMENT 'Reginal VP of advisor',
	BRANCH_NRD VARCHAR(500) COMMENT 'Branch code of the Advisor',
	BRANCH_NAME VARCHAR(500) MASKING POLICY COMMENT 'Branch Name of the Advisor',
	PROVINCE VARCHAR(500) COMMENT 'PROVINCE of the advisor',
	IS_ACTIVE NUMBER(1,0) COMMENT 'Indicator to show the advisor is active or not',
	TRADE_NAME VARCHAR(2000) MASKING POLICY COMMENT 'Trade name',
	PORTAL_IDS VARCHAR(2000) COMMENT 'Portal id exp- PortalIds_#118048 ';

alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_SAT_INVESTMENT_PRODUCT_TYPE_COMPUTE
alter column
	HK_HUB VARCHAR(64) COMMENT 'Hash key for the Hub',
	MD_HASHDIFF VARCHAR(64) DEFAULT '0' COMMENT 'Represents the whole set of hashed attributes to be historized for an occurrence',
	SYMBOL VARCHAR(1000) COMMENT 'Product Symbol',
	NAME VARCHAR(1000) COMMENT 'Product name',
	ASSET_CATEGORY VARCHAR(1000) COMMENT 'Category of the Product exp: common stock, debentures etc',
	CATEGORY VARCHAR(1000) COMMENT 'Catogory of the product',
	PRODUCT_GROUP VARCHAR(1000) COMMENT 'Group of the product',
	ISSUER_COMPANY_CODE VARCHAR(1000) COMMENT 'Issuer Company code',
	ISSUER_COMPANY_NAME VARCHAR(1000) COMMENT 'Issuer Company Name'
;
-- 
alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_SAT_PARTY_ROLE_ACCOUNT_HOLDER_COMPUTE
add column
	CLIENT_AUA_SEGMENT VARCHAR(50) COMMENT 'Client AUA Segment : 25k-100k',
	CLIENT_AUA_SEGMENT_ORD NUMBER(2,0) COMMENT 'Client AUA Segment ORDER'
;

alter TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_SAT_REF_INVESTMENT_SAVING_PROGRAM_TYPES_COMPUTE
alter column
	PLAN_CODE VARCHAR(8000) COMMENT 'The plan code',
	PLAN_LABEL VARCHAR(8000) COMMENT 'The plan label',
	ACCOUNT_TYPE VARCHAR(16777216) COMMENT 'The account type',
	GROUP_TYPE_CODE VARCHAR(8000) COMMENT 'The group type code',
	ACCUMULATION_TYPE VARCHAR(8000) COMMENT 'The accumulation type',
	ASC_1_RESP_PLAN_TYPES VARCHAR(100) COMMENT 'subtype of the RESP plans'
;

-- to be deleted
drop table TABLE DB_IAW_#env#_DM.HOLDINGS.FACT_HOLDINGS_NOEXCL;
drop table TABLE DB_IAW_#env#_DM.HOLDINGS_BKP;
drop table TABLE DB_IAW_#env#_DM.HOLDINGS_BKP.FUND2;
drop table TABLE DB_IAW_#env#_DM.HOLDINGS_BKP.VW_FACT_HOLDINGS;
drop table TABLE DB_IAW_#env#_DM.PUBLIC.D;
drop TABLE DB_IAW_#env#_DM.REVENUES.FACT_REVENUE_DELTA;
drop view DB_IAW_#env#_DM.REVENUES.VW_INITIAL_LOADING_WT_FACT_REVENUES_BAK;
drop schema  DB_IAW_#env#_DM.REVENUES_BKP;
drop TABLE DB_IAW_#env#_DM.SHARED.DIM_ACCOUNTS_BKP;
drop TABLE DB_IAW_#env#_DM.SHARED.DIM_ADVISOR_CLONE;
drop TABLE DB_IAW_#env#_DM.SHARED.DIM_ACCOUNTS_SV;
drop TABLE DB_IAW_#env#_DM.SHARED.WT_DIM_ACCOUNTS_BKP;
drop TABLE DB_IAW_#env#_DM.SHARED.WT_DIM_ACCOUNTS_SV;
drop TABLE DB_IAW_#env#_DM.TRANSACTIONS.FACT_TRANSACTIONS_B4;
drop TABLE DB_IAW_#env#_DM.TRANSACTIONS.FACT_TRANSACTIONS_BKUP;
drop TABLE DB_IAW_#env#_DM.TRANSACTIONS.FACT_TRANSACTIONS_IL;
drop TABLE DB_IAW_#env#_DM.TRANSACTIONS.FACT_TRANSACTIONS_NOEXCL;
drop TABLE DB_IAW_#env#_DM.TRANSACTIONS.FACT_TRANSACTIONS_TEST;
drop schema DB_IAW_#env#_DM.TRANSACTIONS_BKP;
drop view DB_IAW_#env#_DWH.REVENUES_BDV.VW_INITIAL_LOADING_WT_LINK_REVENUE_BAK;
drop view DB_IAW_#env#_DWH.REVENUES_BDV.VW_INITIAL_LOADING_UNIVERIS_REVENUE_PAYABLE_WT_LINK_REVENUE_IHEB;
drop view DB_IAW_#env#_DWH.REVENUES_BDV.VW_INITIAL_LOADING_WT_LINK_REVENUE_BAK;
drop TABLE DB_IAW_#env#_DWH.SHARED_BDV.CLONE_ADF1_WT_SAT_PARTY_ROLE_ACCOUNT_AUA_SEG_COMPUTE;
drop TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE_NOEXCL;
drop table DB_IAW_#env#_DWH.SHARED_BDV.WT_SAT_PARTY_ROLE_ACCOUNT_AUA_SEG_COMPUTE;
drop table DB_IAW_#env#_DWH.SHARED_BDV.SAT_PARTY_ROLE_ACCOUNT_AUA_SEG_COMPUTE;
drop table TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_PARTY_ROLE_ACCOUNT_HOLDER_COMPUTE_BKP;
drop table TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_PARTY_ROLE_ADVISOR_AUA_SEG_COMPUTE_CLONE;
drop table TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH_B4UPD;
drop table TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH_CLONE;
drop table TABLE DB_IAW_#env#_DWH.SHARED_BDV.SAT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH_NOEXCL;
drop TABLE DB_IAW_#env#_DWH.SHARED_BDV.WT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH_BKP;
--drop table DB_IAW_#env#_DWH.SHARED_BDV.BVW_ORGANIC_GROWTH_EXCEPTION_SHR;