SELECT exchangeDate, exchangeRate, revNo,
	CURDATE() AS MD_LOADDATE,
	'IAS_IAVM' AS MD_SRCSYSTEM FROM IAVM.exchangeRate
#INTO OUTFILE 'C:\\BW_IAS_EXPORT_ACCP\\EXCHANGERATE.bcp' FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';

