

CREATE OR REPLACE PROCEDURE DB_IAWT_DEV_DWH.SHARED_BDV.SP_CONV_LOADBDV_RDV_IAS_COMMISSION_SHARE_SAT_TO_BDV_WT_REGISTERED_REPRESENTATIVE("ENV" VARCHAR(1000), "DATA_START_DATE" VARCHAR(20))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
TRUNC_QUERY STRING;
INS_QUERY STRING;
BEGIN
DATA_START_DATE :=CHAR(39)||DATA_START_DATE||CHAR(39);
TRUNC_QUERY := ''TRUNCATE TABLE DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_REGISTERED_REPRESENTATIVE'';

INS_QUERY:= ''INSERT INTO DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_REGISTERED_REPRESENTATIVE
(
HK_HUB,
HK_SAT,
MD_START_DT,
MD_HASHDIFF,
MD_CREATION_DT,
MD_SOURCE,
MD_CREATION_AUDIT_ID,
MD_SRC_SYSTEM,
MD_EXTRACT_DT,
MD_ACTIVE,
RR_CD,
REPNAME,
FIRSTNAME,
LASTNAME,
BRANCHCODE,
BRANCHNAME,
GROUPID,
GROUPDESCRIPTION,
FIXEDFEEIND,
MANAGEDIND,
REFIND,
ACTIVEIND,
SEGFUNDIND,
REVNO,
STAMP,
USERID,
ACTIVE,
ADVISOR_ID,
COMMRATEPCT,
SHAREGROSSCOMMIND,
STARTDATE,
MAINREPCODE,
RGN_MGR,
BRN_CD,
BRN_NAME,
REP_LNAME,
REP_FNAME
)
(
WITH
  LV AS (
  SELECT
	HK_HUB AS LV_HK_HUB,
	HK_SAT AS LV_HK_SAT,
	MAX(MD_START_DT) AS O_DATA_START_DATE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_REGISTERED_REPRESENTATIVE_COMMISSION
	WHERE MD_START_DT <= TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''')
	GROUP BY HK_HUB, HK_SAT
  ),
  FLTR_ACTV AS (
  SELECT
	A.LV_HK_HUB 				AS LV_HK_HUB,
	A.LV_HK_SAT 				AS LV_HK_SAT,
	A.O_DATA_START_DATE 		AS O_DATA_START_DATE,
	B.HK_HUB 					AS HK_HUB,
	B.HK_SAT 					AS HK_SAT,
	B.MD_START_DT 				AS MD_START_DT,
	B.MD_HASHDIFF 				AS MD_HASHDIFF,
	B.MD_CREATION_DT 			AS MD_CREATION_DT,
	B.MD_CREATION_AUDIT_ID 		AS MD_CREATION_AUDIT_ID,
	B.MD_SOURCE 				AS MD_SOURCE,
	B.MD_SRC_SYSTEM 			AS MD_SRC_SYSTEM,
	B.MD_EXTRACT_DT 			AS MD_EXTRACT_DT,
	B.MD_ACTIVE 				AS MD_ACTIVE,
	B.REPNAME 					AS REPNAME,
	B.FIRSTNAME 				AS FIRSTNAME,
	B.LASTNAME 					AS LASTNAME,
	B.BRANCHCODE 				AS BRANCHCODE,
	B.BRANCHNAME 				AS BRANCHNAME,
	B.GROUPID 					AS GROUPID,
	B.GROUPDESCRIPTION 			AS GROUPDESCRIPTION, 
	B.FIXEDFEEIND 				AS FIXEDFEEIND,
	B.MANAGEDIND 				AS MANAGEDIND,
	B.REFIND 					AS REFIND,
	B.ACTIVEIND 				AS ACTIVEIND,
	B.SEGFUNDIND 				AS SEGFUNDIND,
	B.REVNO 					AS REVNO,
	B.STAMP 					AS STAMP,
	B.USERID 					AS USERID,
	B.ACTIVE 					AS ACTIVE,
	B.ADVISOR_ID 				AS ADVISOR_ID,
	B.COMMRATEPCT 				AS COMMRATEPCT,
	B.SHAREGROSSCOMMIND 		AS SHAREGROSSCOMMIND,
	B.STARTDATE 				AS STARTDATE,
	B.MAINREPCODE 				AS MAINREPCODE
	FROM 
	DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_REGISTERED_REPRESENTATIVE_COMMISSION B
	JOIN LV A
	ON  B.HK_HUB = A.LV_HK_HUB
	AND B.HK_SAT = A.LV_HK_SAT
	AND B.MD_START_DT = A.O_DATA_START_DATE
	WHERE 
	B.MD_ACTIVE = ''''A''''
	),
	JNR_SAT_HUB AS (
	SELECT
	B.HK_HUB AS HUB_HK_HUB,
	B.MD_EXTRACT_DT AS HUB_MD_EXTRACT_DT,
	B.MD_SRC_SYSTEM AS HUB_MD_SRC_SYSTEM,
	B.RR_CD AS HUB_RR_CD,
	A.LV_HK_HUB AS 	LV_HK_HUB,
	A.LV_HK_SAT AS 	LV_HK_SAT,
	A.O_DATA_START_DATE AS 	O_DATA_START_DATE,
	A.HK_HUB AS 	HK_HUB,
	A.HK_SAT AS 	HK_SAT,
	A.MD_START_DT AS 	MD_START_DT,
	A.MD_HASHDIFF AS 	MD_HASHDIFF,
	A.MD_CREATION_DT AS 	MD_CREATION_DT,
	A.MD_CREATION_AUDIT_ID AS 	MD_CREATION_AUDIT_ID,
	A.MD_SOURCE AS 	MD_SOURCE,
	A.MD_SRC_SYSTEM AS 	MD_SRC_SYSTEM,
	A.MD_EXTRACT_DT AS 	MD_EXTRACT_DT,
	A.MD_ACTIVE AS 	MD_ACTIVE,
	A.REPNAME AS 	REPNAME,
	A.FIRSTNAME AS 	FIRSTNAME,
	A.LASTNAME AS 	LASTNAME,
	A.BRANCHCODE AS 	BRANCHCODE,
	A.BRANCHNAME AS 	BRANCHNAME,
	A.GROUPID AS 	GROUPID,
	A.GROUPDESCRIPTION AS  	GROUPDESCRIPTION, 
	A.FIXEDFEEIND AS 	FIXEDFEEIND,
	A.MANAGEDIND AS 	MANAGEDIND,
	A.REFIND AS 	REFIND,
	A.ACTIVEIND AS 	ACTIVEIND,
	A.SEGFUNDIND AS 	SEGFUNDIND,
	A.REVNO AS 	REVNO,
	A.STAMP AS 	STAMP,
	A.USERID AS 	USERID,
	A.ACTIVE AS 	ACTIVE,
	A.ADVISOR_ID AS 	ADVISOR_ID,
	A.COMMRATEPCT AS 	COMMRATEPCT,
	A.SHAREGROSSCOMMIND AS 	SHAREGROSSCOMMIND,
	A.STARTDATE AS 	STARTDATE,
	A.MAINREPCODE AS 	MAINREPCODE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.HUB_REGISTERED_REPRESENTATIVE B
	JOIN FLTR_ACTV A
	ON A.HK_HUB = B.HK_HUB
	),
	LV_UNIVERIS AS (
	SELECT 
	HK_HUB AS LV_UNIVERIS_HK_HUB,
	MD_START_DT AS LV_UNIVERIS_MD_START_DT,
	MAX(MD_START_DT) AS O_DATA_START_DATE_UNIVERIS
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_REGISTERED_REPRESENTATIVE_IAS_UNIVERIS
	WHERE MD_START_DT <= TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''')
	GROUP BY HK_HUB, MD_START_DT
	),
	JNR_SAT_UNIVERIS AS (
	SELECT
	A.LV_UNIVERIS_HK_HUB AS LV_UNIVERIS_HK_HUB,
	A.LV_UNIVERIS_MD_START_DT AS LV_UNIVERIS_MD_START_DT,
	A.O_DATA_START_DATE_UNIVERIS AS O_DATA_START_DATE_UNIVERIS,
	B.HK_HUB AS 	SAT_UNIVERIS_HK_HUB,
	B.MD_START_DT AS 	SAT_UNIVERIS_MD_START_DT,
	B.MD_HASHDIFF AS 	SAT_UNIVERIS_MD_HASHDIFF,
	B.MD_CREATION_DT AS 	SAT_UNIVERIS_MD_CREATION_DT,
	B.MD_CREATION_AUDIT_ID AS 	SAT_UNIVERIS_MD_CREATION_AUDIT_ID,
	B.MD_SOURCE AS 	SAT_UNIVERIS_MD_SOURCE,
	B.MD_SRC_SYSTEM AS 	SAT_UNIVERIS_MD_SRC_SYSTEM,
	B.MD_EXTRACT_DT AS 	SAT_UNIVERIS_MD_EXTRACT_DT,
	B.MD_ACTIVE AS 	SAT_UNIVERIS_MD_ACTIVE,
	B.COMPANY_CD AS 	SAT_UNIVERIS_COMPANY_CD,
	B.COMPANY_NAME AS 	SAT_UNIVERIS_COMPANY_NAME,
	B.REGULATORY_ORG_CD AS 	SAT_UNIVERIS_REGULATORY_ORG_CD,
	B.REGULATORY_ORG_NAME AS 	SAT_UNIVERIS_REGULATORY_ORG_NAME,
	B.DLR_SYSID AS 	SAT_UNIVERIS_DLR_SYSID,
	B.DLR_CD AS 	SAT_UNIVERIS_DLR_CD,
	B.DLR_NAME_ENG AS 	SAT_UNIVERIS_DLR_NAME_ENG,
	B.RGN_SYSID AS 	SAT_UNIVERIS_RGN_SYSID,
	B.RGN_CD AS 	SAT_UNIVERIS_RGN_CD,
	B.RGN_NAME AS 	SAT_UNIVERIS_RGN_NAME,
	B.RGN_MGR AS 	SAT_UNIVERIS_RGN_MGR,
	B.BRN_SYSID AS 	SAT_UNIVERIS_BRN_SYSID,
	B.BRN_CD AS 	SAT_UNIVERIS_BRN_CD,
	B.BRN_NAME AS 	SAT_UNIVERIS_BRN_NAME,
	B.REP_TEAM_CD AS 	SAT_UNIVERIS_REP_TEAM_CD,
	B.REP_TEAM_NAME AS 	SAT_UNIVERIS_REP_TEAM_NAME,
	B.REP_SYSID AS 	SAT_UNIVERIS_REP_SYSID,
	B.NK_REP_CORP_NAME AS 	SAT_UNIVERIS_NK_REP_CORP_NAME,
	B.REP_LNAME AS 	SAT_UNIVERIS_REP_LNAME,
	B.REP_FNAME AS 	SAT_UNIVERIS_REP_FNAME,
	B.REP_ST_NAME AS 	SAT_UNIVERIS_REP_ST_NAME,
	B.REP_GRP_RSP AS 	SAT_UNIVERIS_REP_GRP_RSP
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_REGISTERED_REPRESENTATIVE_IAS_UNIVERIS B
	JOIN LV_UNIVERIS A
	ON B.HK_HUB = A.LV_UNIVERIS_HK_HUB
	AND B.MD_START_DT = A.O_DATA_START_DATE_UNIVERIS
	),
	 Jnr_SAT_IAS_lett_join_SAT_UNIVERIS AS (
	 SELECT 
	  B.HUB_HK_HUB AS 	HUB_HK_HUB,
	  B.HUB_MD_EXTRACT_DT AS 	HUB_MD_EXTRACT_DT,
	  B.HUB_MD_SRC_SYSTEM AS 	HUB_MD_SRC_SYSTEM,
	  B.HUB_RR_CD AS 	HUB_RR_CD,
	  B.LV_HK_HUB AS 	LV_HK_HUB,
	  B.LV_HK_SAT AS 	LV_HK_SAT,
	  B.O_DATA_START_DATE AS 	O_DATA_START_DATE,
	  B.HK_HUB AS 	HK_HUB,
	  B.HK_SAT AS 	HK_SAT,
	  B.MD_START_DT AS 	MD_START_DT,
	  B.MD_HASHDIFF AS 	MD_HASHDIFF,
	  B.MD_CREATION_DT AS 	MD_CREATION_DT,
	  B.MD_CREATION_AUDIT_ID AS 	MD_CREATION_AUDIT_ID,
	  B.MD_SOURCE AS 	MD_SOURCE,
	  B.MD_SRC_SYSTEM AS 	MD_SRC_SYSTEM,
	  B.MD_EXTRACT_DT AS 	MD_EXTRACT_DT,
	  B.MD_ACTIVE AS 	MD_ACTIVE,
	  B.REPNAME AS 	REPNAME,
	  B.FIRSTNAME AS 	FIRSTNAME,
	  B.LASTNAME AS 	LASTNAME,
	  B.BRANCHCODE AS 	BRANCHCODE,
	  B.BRANCHNAME AS 	BRANCHNAME,
	  B.GROUPID AS 	GROUPID,
	  B.GROUPDESCRIPTION AS  	GROUPDESCRIPTION, 
	  B.FIXEDFEEIND AS 	FIXEDFEEIND,
	  B.MANAGEDIND AS 	MANAGEDIND,
	  B.REFIND AS 	REFIND,
	  B.ACTIVEIND AS 	ACTIVEIND,
	  B.SEGFUNDIND AS 	SEGFUNDIND,
	  B.REVNO AS 	REVNO,
	  B.STAMP AS 	STAMP,
	  B.USERID AS 	USERID,
	  B.ACTIVE AS 	ACTIVE,
	  B.ADVISOR_ID AS 	ADVISOR_ID,
	  B.COMMRATEPCT AS 	COMMRATEPCT,
	  B.SHAREGROSSCOMMIND AS 	SHAREGROSSCOMMIND,
	  B.STARTDATE AS 	STARTDATE,
	  B.MAINREPCODE AS 	MAINREPCODE,
	  A.LV_UNIVERIS_HK_HUB AS 	LV_UNIVERIS_HK_HUB,
	  A.LV_UNIVERIS_MD_START_DT AS 	LV_UNIVERIS_MD_START_DT,
	  A.O_DATA_START_DATE_UNIVERIS AS 	O_DATA_START_DATE_UNIVERIS,
	  A.SAT_UNIVERIS_HK_HUB AS 	SAT_UNIVERIS_HK_HUB,
	  A.SAT_UNIVERIS_MD_START_DT AS 	SAT_UNIVERIS_MD_START_DT,
	  A.SAT_UNIVERIS_MD_HASHDIFF AS 	SAT_UNIVERIS_MD_HASHDIFF,
	  A.SAT_UNIVERIS_MD_CREATION_DT AS 	SAT_UNIVERIS_MD_CREATION_DT,
	  A.SAT_UNIVERIS_MD_CREATION_AUDIT_ID AS 	SAT_UNIVERIS_MD_CREATION_AUDIT_ID,
	  A.SAT_UNIVERIS_MD_SOURCE AS 	SAT_UNIVERIS_MD_SOURCE,
	  A.SAT_UNIVERIS_MD_SRC_SYSTEM AS 	SAT_UNIVERIS_MD_SRC_SYSTEM,
	  A.SAT_UNIVERIS_MD_EXTRACT_DT AS 	SAT_UNIVERIS_MD_EXTRACT_DT,
	  A.SAT_UNIVERIS_MD_ACTIVE AS 	SAT_UNIVERIS_MD_ACTIVE,
	  A.SAT_UNIVERIS_COMPANY_CD AS 	SAT_UNIVERIS_COMPANY_CD,
	  A.SAT_UNIVERIS_COMPANY_NAME AS 	SAT_UNIVERIS_COMPANY_NAME,
	  A.SAT_UNIVERIS_REGULATORY_ORG_CD AS 	SAT_UNIVERIS_REGULATORY_ORG_CD,
	  A.SAT_UNIVERIS_REGULATORY_ORG_NAME AS 	SAT_UNIVERIS_REGULATORY_ORG_NAME,
	  A.SAT_UNIVERIS_DLR_SYSID AS 	SAT_UNIVERIS_DLR_SYSID,
	  A.SAT_UNIVERIS_DLR_CD AS 	SAT_UNIVERIS_DLR_CD,
	  A.SAT_UNIVERIS_DLR_NAME_ENG AS 	SAT_UNIVERIS_DLR_NAME_ENG,
	  A.SAT_UNIVERIS_RGN_SYSID AS 	SAT_UNIVERIS_RGN_SYSID,
	  A.SAT_UNIVERIS_RGN_CD AS 	SAT_UNIVERIS_RGN_CD,
	  A.SAT_UNIVERIS_RGN_NAME AS 	SAT_UNIVERIS_RGN_NAME,
	  A.SAT_UNIVERIS_RGN_MGR AS 	SAT_UNIVERIS_RGN_MGR,
	  A.SAT_UNIVERIS_BRN_SYSID AS 	SAT_UNIVERIS_BRN_SYSID,
	  A.SAT_UNIVERIS_BRN_CD AS 	SAT_UNIVERIS_BRN_CD,
	  A.SAT_UNIVERIS_BRN_NAME AS 	SAT_UNIVERIS_BRN_NAME,
	  A.SAT_UNIVERIS_REP_TEAM_CD AS 	SAT_UNIVERIS_REP_TEAM_CD,
	  A.SAT_UNIVERIS_REP_TEAM_NAME AS 	SAT_UNIVERIS_REP_TEAM_NAME,
	  A.SAT_UNIVERIS_REP_SYSID AS 	SAT_UNIVERIS_REP_SYSID,
	  A.SAT_UNIVERIS_NK_REP_CORP_NAME AS 	SAT_UNIVERIS_NK_REP_CORP_NAME,
	  A.SAT_UNIVERIS_REP_LNAME AS 	SAT_UNIVERIS_REP_LNAME,
	  A.SAT_UNIVERIS_REP_FNAME AS 	SAT_UNIVERIS_REP_FNAME,
	  A.SAT_UNIVERIS_REP_ST_NAME AS 	SAT_UNIVERIS_REP_ST_NAME,
	  A.SAT_UNIVERIS_REP_GRP_RSP	SAT_UNIVERIS_REP_GRP_RSP
	  FROM JNR_SAT_HUB B
	  LEFT JOIN JNR_SAT_UNIVERIS A 
	  ON B.HK_HUB = A.SAT_UNIVERIS_HK_HUB
	  )
	  SELECT 
	  HK_HUB,
	  HK_SAT,
	  MD_START_DT,
	  MD_HASHDIFF,
	  MD_CREATION_DT,
	  MD_SOURCE,
	  MD_CREATION_AUDIT_ID,
	  MD_SRC_SYSTEM,
	  MD_EXTRACT_DT,
	  MD_ACTIVE,
	  HUB_RR_CD,
	  REPNAME,
	  FIRSTNAME,
	  LASTNAME,
	  BRANCHCODE,
	  BRANCHNAME,
	  GROUPID,
	  GROUPDESCRIPTION,
	  FIXEDFEEIND,
	  MANAGEDIND,
	  REFIND,
	  ACTIVEIND,
	  SEGFUNDIND,
	  REVNO,
	  STAMP,
	  USERID,
	  ACTIVE,
	  ADVISOR_ID,
	  COMMRATEPCT,
	  SHAREGROSSCOMMIND,
	  STARTDATE,
	  MAINREPCODE,
	  SAT_UNIVERIS_RGN_MGR,
	  SAT_UNIVERIS_BRN_CD,
	  SAT_UNIVERIS_BRN_NAME,
	  SAT_UNIVERIS_REP_LNAME,
	  SAT_UNIVERIS_REP_FNAME
	  FROM Jnr_SAT_IAS_lett_join_SAT_UNIVERIS)'';
  

EXECUTE IMMEDIATE :TRUNC_QUERY;
EXECUTE IMMEDIATE :INS_QUERY;
END


';

CREATE OR REPLACE PROCEDURE DB_IAWT_DEV_DWH.SHARED_BDV.SP_CONV_LOADBDV_RDV_IAS_COMMISSION_SHARE_TO_BDV_WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE_MC("ENV" VARCHAR(1000), "DATA_START_DATE" VARCHAR(20))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
TRUNC_QUERY STRING;
INS_QUERY STRING;
BEGIN
DATA_START_DATE :=CHAR(39)||DATA_START_DATE||CHAR(39);
TRUNC_QUERY := ''TRUNCATE TABLE DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE_MC'';

INS_QUERY:= ''INSERT INTO DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE_MC (
HK_LINK,
HK_HUB_REGISTERED_REPRESENTATIVE,
HK_HUB_ADVISOR,
MD_SOURCE,
MD_HASHDIFF,
MD_CREATION_DT,
MD_SRC_SYSTEM,
MD_EXTRACT_DT,
MD_CREATION_AUDIT_ID,
FROMREPID,
TOREPID,
SHARETYPE,
SOURCECODE,
PRODUCTCODE,
REVENUEPCT,
COMMISSIONPCT,
NETCOMMISSIONPCT,
FEEPCT,
REVNO,
STAMP,
MD_START_DT
)
(
WITH
  LV AS (
  SELECT
	HK_LINK AS LV_HK_LINK,
	MAX(MD_START_DT) AS O_START_DATE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_LINK_COMMISSION_SHARE_RR
	WHERE MD_START_DT <= TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''')
	GROUP BY HK_LINK
  ),
  FLTR_ACTIVE AS (
  SELECT
	A.LV_HK_LINK 				AS LV_HK_LINK,
	A.O_START_DATE 				AS O_START_DATE,
	B.COMMISSIONPCT 			AS COMMISSIONPCT,
	B.FEEPCT 					AS FEEPCT,
	B.HK_LINK 					AS HK_LINK,
	B.MD_ACTIVE 				AS MD_ACTIVE,
	B.MD_CREATION_AUDIT_ID 		AS MD_CREATION_AUDIT_ID,
	B.MD_CREATION_DT 			AS MD_CREATION_DT,
	B.MD_EXTRACT_DT 			AS MD_EXTRACT_DT,
	B.MD_HASHDIFF 				AS MD_HASHDIFF,
	B.MD_SOURCE 				AS MD_SOURCE,
	B.MD_SRC_SYSTEM 			AS MD_SRC_SYSTEM,
	B.MD_START_DT 				AS MD_START_DT,
	B.NETCOMMISSIONPCT 			AS NETCOMMISSIONPCT,
	NULL 						AS PRODUCTCODE,
	B.REVENUEPCT 				AS REVENUEPCT,
	B.REVNO 					AS REVNO,
	NULL  						AS SHARETYPE,
	NULL  						AS SOURCECODE,
	B.STAMP 					AS STAMP
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_LINK_COMMISSION_SHARE_RR B
	JOIN LV A
	ON B.HK_LINK = A.LV_HK_LINK
	AND B.MD_START_DT = A.O_START_DATE
	WHERE B.MD_ACTIVE = ''''A''''
	),
  Joiner_IAS_Commission_Share AS (
  SELECT 
	A.COMMISSIONPCT AS COMMISSIONPCT,
	A.FEEPCT AS FEEPCT,
	A.HK_LINK AS HK_LINK,
	A.MD_CREATION_AUDIT_ID AS MD_CREATION_AUDIT_ID,
	A.MD_CREATION_DT AS MD_CREATION_DT,
	A.MD_EXTRACT_DT AS MD_EXTRACT_DT,
	A.MD_HASHDIFF AS MD_HASHDIFF,
	A.MD_SOURCE AS MD_SOURCE,
	A.MD_SRC_SYSTEM AS MD_SRC_SYSTEM,
	A.MD_START_DT AS MD_START_DT,
	A.NETCOMMISSIONPCT AS NETCOMMISSIONPCT,
	A.REVENUEPCT AS REVENUEPCT,
	A.REVNO AS REVNO,
	A.STAMP AS STAMP,
	B.FROMREPID AS HUB_FROMREPID,
	B.HK_HUB_FROM AS HUB_HK_HUB_FROM,
	B.HK_HUB_TO AS HUB_HK_HUB_TO,
	B.HK_LINK AS HUB_HK_LINK,
	B.PRODUCTCODE AS HUB_PRODUCTCODE,
	B.SHARETYPE AS HUB_SHARETYPE,
	B.SOURCECODE AS HUB_SOURCECODE,
	B.TOREPID AS HUB_TOREPID
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.LINK_COMMISSION_SHARE_RR B
	JOIN FLTR_ACTIVE A
	ON B.HK_LINK = A.HK_LINK
	WHERE HUB_SHARETYPE!=''''noreference'''' AND HUB_SHARETYPE!=''''option''''
	AND HUB_SHARETYPE!=''''override'''' OR HUB_FROMREPID!=''''SBEP''''
	AND COMMISSIONPCT > 0)
	SELECT 
	HK_LINK,
	HUB_HK_HUB_FROM,
	HUB_HK_HUB_TO,
	MD_SOURCE,
	MD_HASHDIFF,
	MD_CREATION_DT,
	MD_SRC_SYSTEM,
	MD_EXTRACT_DT,
	MD_CREATION_AUDIT_ID,
	HUB_FROMREPID,
	HUB_TOREPID,
	HUB_SHARETYPE,
	HUB_SOURCECODE,
	HUB_PRODUCTCODE,
	REVENUEPCT,
	COMMISSIONPCT,
	NETCOMMISSIONPCT,
	FEEPCT,
	REVNO,
	STAMP,
	TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''') 
	FROM Joiner_IAS_Commission_Share)'';
  

EXECUTE IMMEDIATE :TRUNC_QUERY;
EXECUTE IMMEDIATE :INS_QUERY;
END


';

-- CERTS

CREATE OR REPLACE PROCEDURE DB_IAWT_DEV_DWH.SHARED_BDV.SP_CONV_LOADBDV_RDV_IAS_CERTS_HUB_SAT_TO_BDV_WT_ADVISOR_IAS_CERTS("ENV" VARCHAR(1000), "DATA_START_DATE" VARCHAR(20))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
TRUNC_QUERY STRING;
INS_QUERY STRING;
BEGIN
DATA_START_DATE :=CHAR(39)||DATA_START_DATE||CHAR(39);
TRUNC_QUERY := ''TRUNCATE TABLE DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_ADVISOR_IAS_CERTS'';

INS_QUERY:= ''INSERT INTO DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_ADVISOR_IAS_CERTS (
HK_HUB,
MD_HASHDIFF,
MD_CREATION_DT,
MD_CREATION_AUDIT_ID,
MD_SOURCE,
MD_SRC_SYSTEM,
MD_EXTRACT_DT,
MD_ACTIVE,
CID,
FIRST_NAME,
LAST_NAME,
FULL_NAME,
PRIMARY_ROLE,
RVP,
BRANCH_NRD,
BRANCH_NAME,
PROVINCE,
IS_ACTIVE,
TRADE_NAME,
PORTAL_IDS,
BEGIN_DT,
END_DT,
RR_CD,
ADVISOR_BIRTH_DATE,
MD_START_DT
)
(
WITH
  LV AS (
  SELECT
	HK_HUB AS LV_HK_HUB,
	MAX(MD_START_DT) AS O_DATA_START_DATE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_ADVISOR_IAS_CERTS
	WHERE MD_START_DT <= TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''')
	GROUP BY HK_HUB
  ),
  Jnr_SAT AS (
  SELECT
  A.LV_HK_HUB 					AS  LV_HK_HUB,
  A.O_DATA_START_DATE 			AS  O_DATA_START_DATE,
  B.HK_HUB 						AS 	HK_HUB,
  B.MD_START_DT 				AS 	MD_START_DT,
  B.MD_HASHDIFF 				AS 	MD_HASHDIFF,
  B.MD_CREATION_DT 				AS 	MD_CREATION_DT,
  B.MD_CREATION_AUDIT_ID 		AS 	MD_CREATION_AUDIT_ID,
  B.MD_SOURCE 					AS 	MD_SOURCE,
  B.MD_SRC_SYSTEM 				AS 	MD_SRC_SYSTEM,
  B.MD_EXTRACT_DT 				AS 	MD_EXTRACT_DT,
  B.MD_ACTIVE 					AS 	MD_ACTIVE,
  B.FIRST_NAME 					AS 	FIRST_NAME,
  B.LAST_NAME 					AS 	LAST_NAME,
  B.FULL_NAME 					AS 	FULL_NAME,
  B.PRIMARY_ROLE 				AS 	PRIMARY_ROLE,
  B.RVP 						AS 	RVP,
  B.BRANCH_NRD 					AS 	BRANCH_NRD,
  B.BRANCH_NAME 				AS 	BRANCH_NAME,
  B.PROVINCE 					AS 	PROVINCE,
  B.IS_ACTIVE 					AS 	IS_ACTIVE,
  B.TRADE_NAME 					AS 	TRADE_NAME,
  B.PORTAL_IDS 					AS 	PORTAL_IDS,
  B.BEGIN_DT 					AS 	BEGIN_DT,
  B.END_DT 						AS 	END_DT,
  B.ADVISOR_BIRTH_DATE 			AS 	ADVISOR_BIRTH_DATE
  FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_ADVISOR_IAS_CERTS B
  JOIN LV A
  ON B.HK_HUB = A.LV_HK_HUB
  AND B.MD_START_DT = A.O_DATA_START_DATE
  WHERE B.MD_ACTIVE = ''''A''''
  ),
  JNR_SAT_HUB AS (
  SELECT
	B.CID AS HUB_CID,
	B.HK_HUB AS HUB_HK_HUB,
	B.MD_EXTRACT_DT AS HUB_MD_EXTRACT_DT,
	B.MD_SRC_SYSTEM AS HUB_MD_SRC_SYSTEM,
	B.RR_CD AS HUB_RR_CD,
	A.LV_HK_HUB 				AS 	LV_HK_HUB,
	A.O_DATA_START_DATE 		AS 	O_DATA_START_DATE,
	A.HK_HUB 					AS 	HK_HUB,
	A.MD_START_DT 				AS 	MD_START_DT,
	A.MD_HASHDIFF 				AS 	MD_HASHDIFF,
	A.MD_CREATION_DT 			AS 	MD_CREATION_DT,
	A.MD_CREATION_AUDIT_ID 		AS 	MD_CREATION_AUDIT_ID,
	A.MD_SOURCE 				AS 	MD_SOURCE,
	A.MD_SRC_SYSTEM 			AS 	MD_SRC_SYSTEM,
	A.MD_EXTRACT_DT 			AS 	MD_EXTRACT_DT,
	A.MD_ACTIVE 				AS 	MD_ACTIVE,
	A.FIRST_NAME 				AS 	FIRST_NAME,
	A.LAST_NAME 				AS 	LAST_NAME,
	A.FULL_NAME 				AS 	FULL_NAME,
	A.PRIMARY_ROLE 				AS 	PRIMARY_ROLE,
	A.RVP 						AS 	RVP,
	A.BRANCH_NRD 				AS 	BRANCH_NRD,
	A.BRANCH_NAME 				AS 	BRANCH_NAME,
	A.PROVINCE 					AS 	PROVINCE,
	A.IS_ACTIVE 				AS 	IS_ACTIVE,
	A.TRADE_NAME 				AS 	TRADE_NAME,
	A.PORTAL_IDS 				AS 	PORTAL_IDS,
	A.BEGIN_DT 					AS 	BEGIN_DT,
	A.END_DT 					AS 	END_DT,
	A.ADVISOR_BIRTH_DATE 		AS 	ADVISOR_BIRTH_DATE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.HUB_ADVISOR_IAS_CERTS B
	JOIN Jnr_SAT A
	ON B.HK_HUB = A.HK_HUB	
  )
  SELECT 
	HK_HUB,
	MD_HASHDIFF,
	MD_CREATION_DT,
	MD_CREATION_AUDIT_ID,
	MD_SOURCE,
	MD_SRC_SYSTEM,
	MD_EXTRACT_DT,
	MD_ACTIVE,
	HUB_CID,
	FIRST_NAME,
	LAST_NAME,
	FULL_NAME,
	PRIMARY_ROLE,
	RVP,
	BRANCH_NRD,
	BRANCH_NAME,
	PROVINCE,
	IS_ACTIVE,
	TRADE_NAME,
	PORTAL_IDS,
	BEGIN_DT,
	END_DT,
	HUB_RR_CD,
	ADVISOR_BIRTH_DATE,
	TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''')
	FROM JNR_SAT_HUB)'';
  

EXECUTE IMMEDIATE :TRUNC_QUERY;
EXECUTE IMMEDIATE :INS_QUERY;
END


';

CREATE OR REPLACE PROCEDURE DB_IAWT_DEV_DWH.SHARED_BDV.SP_CONV_LOADBDV_RDV_IAS_CERTS_REGISTERED_REPRESENTATIVE_TO_BDV_WT_REGISTERED_REPRESENTATIVE_IAS_CERTS("ENV" VARCHAR(1000), "DATA_START_DATE" VARCHAR(20))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
TRUNC_QUERY STRING;
INS_QUERY STRING;
BEGIN
DATA_START_DATE :=CHAR(39)||DATA_START_DATE||CHAR(39);
TRUNC_QUERY := ''TRUNCATE TABLE DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_REGISTERED_REPRESENTATIVE_IAS_CERTS'';

INS_QUERY:= ''INSERT INTO DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_REGISTERED_REPRESENTATIVE_IAS_CERTS (
MD_START_DT,
MD_CREATION_DT,
MD_ACTIVE,
RR_CD,
FIRST_NAME,
LAST_NAME,
FULL_NAME,
PRIMARY_ROLE,
RVP,
BRANCH_NRD,
BRANCH_NAME,
PROVINCE,
IS_ACTIVE,
TRADE_NAME,
PORTAL_IDS,
BEGIN_DT,
END_DT,
ADVISOR_BIRTH_DATE,
RDV_RR_IAS_CERTS_MD_START_DT
)
(
WITH
  LV AS (
  SELECT
	HK_HUB AS LV_HK_HUB,
	HK_SAT AS LV_HK_SAT,
	MAX(MD_START_DT) AS O_DATA_START_DATE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_REGISTERED_REPRESENTATIVE_IAS_CERTS
	WHERE MD_START_DT <= TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''')
	GROUP BY HK_HUB,HK_SAT
  ),
  JNR_SAT AS (
  SELECT
	A.LV_HK_HUB 			AS 	LV_HK_HUB,
	A.LV_HK_SAT 			AS 	LV_HK_SAT,
	A.O_DATA_START_DATE 	AS 	O_DATA_START_DATE,
	B.HK_HUB 				AS 	HK_HUB,
	B.HK_SAT			 	AS 	HK_SAT,
	B.MD_START_DT 			AS 	MD_START_DT,
	B.MD_HASHDIFF 			AS 	MD_HASHDIFF,
	B.MD_CREATION_DT 		AS 	MD_CREATION_DT,
	B.MD_CREATION_AUDIT_ID 	AS 	MD_CREATION_AUDIT_ID,
	B.MD_SOURCE 			AS 	MD_SOURCE,
	B.MD_SRC_SYSTEM 		AS 	MD_SRC_SYSTEM,
	B.MD_EXTRACT_DT 		AS 	MD_EXTRACT_DT,
	B.MD_ACTIVE 			AS 	MD_ACTIVE,
	B.CID 					AS 	CID,
	B.FIRST_NAME 			AS 	FIRST_NAME,
	B.LAST_NAME 			AS 	LAST_NAME,
	B.FULL_NAME 			AS 	FULL_NAME,
	B.PRIMARY_ROLE 			AS 	PRIMARY_ROLE,
	B.RVP 					AS 	RVP,
	B.BRANCH_NRD 			AS 	BRANCH_NRD,
	B.BRANCH_NAME		 	AS 	BRANCH_NAME,
	B.PROVINCE 				AS 	PROVINCE,
	B.IS_ACTIVE 			AS 	IS_ACTIVE,
	B.TRADE_NAME 			AS 	TRADE_NAME,
	B.PORTAL_IDS 			AS 	PORTAL_IDS,
	B.BEGIN_DT 				AS 	BEGIN_DT,
	B.END_DT 				AS 	END_DT,
	B.ADVISOR_BIRTH_DATE 	AS 	ADVISOR_BIRTH_DATE   
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_REGISTERED_REPRESENTATIVE_IAS_CERTS B
	JOIN LV A
	ON B.HK_HUB = A.LV_HK_HUB
	AND B.HK_SAT = A.LV_HK_SAT
	AND B.MD_START_DT = A.O_DATA_START_DATE
	WHERE B.MD_ACTIVE=''''A'''' OR B.MD_ACTIVE=''''D''''
  ),
  JNR_SAT_HUB AS (
  SELECT 
	B.HK_HUB AS HUB_HK_HUB,
	B.MD_EXTRACT_DT AS HUB_MD_EXTRACT_DT,
	B.MD_SRC_SYSTEM AS HUB_MD_SRC_SYSTEM,
	B.RR_CD AS HUB_RR_CD,
	A.LV_HK_HUB 					AS 	LV_HK_HUB,
	A.LV_HK_SAT 					AS 	LV_HK_SAT,
	A.O_DATA_START_DATE 			AS 	O_DATA_START_DATE,
	A.HK_HUB 						AS 	HK_HUB,
	A.HK_SAT 						AS 	HK_SAT,
	A.MD_START_DT 					AS 	MD_START_DT,
	A.MD_HASHDIFF 					AS 	MD_HASHDIFF,
	A.MD_CREATION_DT 				AS 	MD_CREATION_DT,
	A.MD_CREATION_AUDIT_ID 			AS 	MD_CREATION_AUDIT_ID,
	A.MD_SOURCE 					AS 	MD_SOURCE,
	A.MD_SRC_SYSTEM 				AS 	MD_SRC_SYSTEM,
	A.MD_EXTRACT_DT 				AS 	MD_EXTRACT_DT,
	A.MD_ACTIVE 					AS 	MD_ACTIVE,
	A.CID 							AS 	CID,
	A.FIRST_NAME 					AS 	FIRST_NAME,
	A.LAST_NAME 					AS 	LAST_NAME,
	A.FULL_NAME 					AS 	FULL_NAME,
	A.PRIMARY_ROLE 					AS 	PRIMARY_ROLE,
	A.RVP 							AS 	RVP,
	A.BRANCH_NRD 					AS 	BRANCH_NRD,
	A.BRANCH_NAME 					AS 	BRANCH_NAME,
	A.PROVINCE 						AS 	PROVINCE,
	A.IS_ACTIVE 					AS 	IS_ACTIVE,
	A.TRADE_NAME 					AS 	TRADE_NAME,
	A.PORTAL_IDS 					AS 	PORTAL_IDS,
	A.BEGIN_DT 						AS 	BEGIN_DT,
	A.END_DT 						AS 	END_DT,
	A.ADVISOR_BIRTH_DATE   			AS 	ADVISOR_BIRTH_DATE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.HUB_REGISTERED_REPRESENTATIVE B 
	JOIN JNR_SAT A
	ON B.HK_HUB = A.HK_HUB
  )
  SELECT
	TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD''''),
	CURRENT_DATE,
	MD_ACTIVE,
	HUB_RR_CD,
	FIRST_NAME,
	LAST_NAME,
	FULL_NAME,
	PRIMARY_ROLE,
	RVP,
	BRANCH_NRD,
	BRANCH_NAME,
	PROVINCE,
	IS_ACTIVE,
	TRADE_NAME,
	PORTAL_IDS,
	BEGIN_DT,
	END_DT,
	ADVISOR_BIRTH_DATE,
	MD_START_DT
	FROM JNR_SAT_HUB)'';
  

EXECUTE IMMEDIATE :TRUNC_QUERY;
EXECUTE IMMEDIATE :INS_QUERY;
END


';

CREATE OR REPLACE PROCEDURE DB_IAWT_DEV_DWH.SHARED_BDV.SP_CONV_LOADBDV_VIEW_SHARE_TO_BDV_WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE("ENV" VARCHAR(1000), "I_DATA_START_DATE" VARCHAR(1000))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
INS_PRE_DEL STRING;
INS_INSERT STRING;
INS_UPDATE STRING;

BEGIN
i_DATA_START_DATE :=CHAR(39)||i_DATA_START_DATE||CHAR(39);
INS_PRE_DEL := ''DELETE FROM DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE WHERE MD_SRC_SYSTEM = ''''IAS'''';  '';
INS_INSERT := ''
INSERT INTO DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE
(
MD_START_DT
,MD_SOURCE
,MD_CREATION_DT
,MD_SRC_SYSTEM
,MD_EXTRACT_DT
,A_C_REPRESENTATIVE
,COM_TYPE
,COMMISSIONPCT
,IS_RESHARED
,MASTER_CODE
,PHYSICAL
,TOREPID
)
SELECT
TRANS.MD_START_DT
,CASE WHEN ORG.SOURCE_MASTER_CODE IS NULL THEN TRANS.MD_SOURCE ELSE ORG.SOURCE_MASTER_CODE END
,CURRENT_TIMESTAMP
,TRANS.MD_SRC_SYSTEM
,TRANS.MD_EXTRACT_DT
,TRANS.A_C_REPRESENTATIVE
,TRANS.COM_TYPE
,CASE WHEN ORG.SOURCE_MASTER_CODE IS NULL THEN TRANS.COMMISSIONPCT ELSE (CASE WHEN ORG.DESTINATION_MASTER_CODE = RTRIM(LTRIM(TRANS.TOREPID)) THEN 100 ELSE 0 END) END
,TRANS.IS_RESHARED
,TRANS.MASTER_CODE
,TRANS.PHYSICAL
,TRANS.TOREPID
 FROM DB_IAWT_''||ENV||''_DWH.SHARED_BDV.VW_IAS_RRCODE_MASTERCODE_TRANS TRANS
LEFT JOIN
(SELECT * FROM DB_IAWT_''||ENV||''_DWH.STEWARDSHIP_RDV.VW_ORGANIC_GROWTH_EXCEPTIONS_IAPW 
        WHERE MD_START_DT <= TO_DATE(''||i_DATA_START_DATE||'',''''YYYY-MM-DD'''') AND START_DATE <= TO_DATE(''||i_DATA_START_DATE||'',''''YYYY-MM-DD'''') AND END_DATE <= TO_DATE(''||i_DATA_START_DATE||'',''''YYYY-MM-DD'''')) ORG
ON ORG.SOURCE_MASTER_CODE = TRANS.A_C_REPRESENTATIVE
			
              '';
INS_UPDATE :='' UPDATE DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE
SET
	HK_LINK=SHA1(CONCAT(COALESCE(MD_SRC_SYSTEM,''''#NULL#''''),''''|'''', COALESCE(A_C_REPRESENTATIVE, ''''#NULL#''''), ''''|'''' , COALESCE(TOREPID,''''#NULL#''''))),
	HK_HUB_REGISTERED_REPRESENTATIVE= SHA1(CONCAT(COALESCE(MD_SRC_SYSTEM,''''#NULL#''''),''''|'''', COALESCE(A_C_REPRESENTATIVE, ''''#NULL#''''))),
	HK_HUB_ADVISOR= SHA1(CONCAT(COALESCE(MD_SRC_SYSTEM,''''#NULL#''''),''''|'''', COALESCE(MASTER_CODE, ''''#NULL#''''))),
	MD_HASHDIFF=SHA1(CONCAT(COALESCE(COM_TYPE, ''''#NULL#''''), ''''|'''' , COALESCE(TO_VARCHAR(COMMISSIONPCT),''''#NULL#''''), ''''|'''', COALESCE(TO_VARCHAR(IS_RESHARED),''''#NULL#''''),''''|'''', COALESCE(TO_VARCHAR(PHYSICAL),''''#NULL#''''),''''|'''',COALESCE(TOREPID, ''''#NULL#'''')))
Where 1=1;
'';
EXECUTE IMMEDIATE :INS_PRE_DEL;
EXECUTE IMMEDIATE :INS_INSERT;
EXECUTE IMMEDIATE :INS_UPDATE;

END
';



CREATE OR REPLACE PROCEDURE DB_IAWT_DEV_DWH.SHARED_BDV.SP_CONV_LOADBDV_RDV_SAT_REGISTERED_REPRESENTATIVE_TO_BDV_WT_PARTY_ROLE_ADVISOR_COMPUTE_INVESTIA_UNIVERIS("ENV" VARCHAR(1000), "DATA_START_DATE" VARCHAR(20))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
DEL_QUERY STRING;
INS_QUERY STRING;
UPD_QUERY STRING;
BEGIN
DATA_START_DATE :=CHAR(39)||DATA_START_DATE||CHAR(39);
DEL_QUERY := ''DELETE FROM DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH WHERE MD_SRC_SYSTEM = ''''INVESTIA-UNIVERIS'''''';
INS_QUERY := ''INSERT INTO DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH
(MD_START_DT,
MD_EXTRACT_DT,
MD_CREATION_DT,
MD_SOURCE,
MD_SRC_SYSTEM,
MASTER_CODE,
COMPANY_CODE,
COMPANY_NAME,
REGULATORY_ORGANIZATION_NAME,
REGULATORY_ORGANIZATION_CODE,
DEALER_CODE,
DEALER_NAME,
REGION_CODE,
REGION_NAME,
REGION_VP,
BRANCHCODE,
BRANCHNAME,
TEAM_CODE,
TEAM_NAME,
ADVISOR_FULLNAME,
FIRSTNAME,
LASTNAME,
ADVISOR_CORPORATION_NAME,
STATUS,
GROUP_RSP_INDICATOR,
PROVINCE_CODE,
PROVINCE,
ADVISOR_START_DATE,
NEW_ADVISOR,
HK_HUB	)
(
WITH
  LV1 AS (
  SELECT
	HK_LINK AS LV1_HK_LINK,
	MAX(MD_START_DT) AS LV1_O_DATA_START_DATE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE
	WHERE MD_START_DT <= TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''')
	GROUP BY HK_LINK
  ),
  JNR_LinkShare AS (
  SELECT
	B.COM_TYPE 					AS 	COM_TYPE,
	B.COMMISSIONPCT 			AS 	COMMISSIONPCT,
	B.HK_LINK 					AS 	HK_LINK,
	B.IS_RESHARED 				AS 	IS_RESHARED,
	B.MD_ACTIVE 				AS 	MD_ACTIVE,
	B.MD_CREATION_AUDIT_ID 		AS 	MD_CREATION_AUDIT_ID,
	B.MD_CREATION_DT 			AS 	MD_CREATION_DT,
	B.MD_EXTRACT_DT 			AS 	MD_EXTRACT_DT,
	B.MD_HASHDIFF 				AS 	MD_HASHDIFF,
	B.MD_SOURCE 				AS 	MD_SOURCE,
	B.MD_SRC_SYSTEM 			AS 	MD_SRC_SYSTEM,
	B.MD_START_DT 				AS 	MD_START_DT,
	B.PHYSICAL 					AS 	PHYSICAL,
	B.TOREPID 					AS 	TOREPID,
	A.LV1_HK_LINK 				AS 	LV1_HK_LINK,
	A.LV1_O_DATA_START_DATE 	AS 	LV1_O_START_DATE,
	D.HK_HUB_PARTY_ROLE_ADVISOR AS 	share_HK_HUB_PARTY_ROLE_ADVISOR,
	D.HK_LINK 					AS 	share_HK_LINK,
	D.MASTER_CODE 				AS 	share_MASTER_CODE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_BDV.SAT_LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE B
	JOIN LV1 A 
	ON B.HK_LINK = A.LV1_HK_LINK
	AND B.MD_START_DT = A.LV1_O_DATA_START_DATE
	JOIN
	DB_IAWT_''||ENV||''_DWH.SHARED_BDV.LINK_PARTY_RELATIONSHIP_COMMISSION_SHARE D
	ON B.HK_LINK = D.HK_LINK
	WHERE 
	B.MD_ACTIVE=''''A'''' AND B.MD_SRC_SYSTEM=''''INVESTIA-UNIVERIS''''
  ),
  AGG_LINK_PARTY_RELATIONSHIP_COMM AS (
  SELECT 
	max(MD_EXTRACT_DT)							AS SAT_SHARE_MD_EXTRACT_DT,
	max(MD_SOURCE) 								AS SAT_SHARE_MD_SOURCE,
	SHARE_HK_HUB_PARTY_ROLE_ADVISOR 			AS SAT_SHARE_SHARE_HK_HUB_PARTY_ROLE_ADVISOR,
	SHARE_MASTER_CODE 							AS SAT_SHARE_SHARE_MASTER_CODE
	FROM JNR_LinkShare
	GROUP BY Sat_share_share_MASTER_CODE, Sat_share_share_HK_HUB_PARTY_ROLE_ADVISOR
  ),
  LV2 AS (
  SELECT
	HK_HUB AS LV2_HK_HUB,
	MAX(MD_START_DT) AS LV2_O_DATA_START_DATE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_REGISTERED_REPRESENTATIVE_INVESTIA_UNIVERIS
	WHERE MD_START_DT <= TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''')
	GROUP BY HK_HUB
  ),
  JNR_SAT_MaxRecord_WITH_SAT_All AS (
   SELECT 
	B.BRN_CD 					AS 	SAT_BRN_CD,
	B.BRN_NAME 					AS 	SAT_BRN_NAME,
	B.BRN_SYSID 				AS 	SAT_BRN_SYSID,
	B.COMPANY_CD 				AS 	SAT_COMPANY_CD,
	B.COMPANY_NAME 				AS 	SAT_COMPANY_NAME,
	B.CREATE_DT 				AS 	SAT_CREATE_DT,
	B.DLR_CD 					AS 	SAT_DLR_CD,
	B.DLR_NAME_ENG 				AS 	SAT_DLR_NAME_ENG,
	B.DLR_SYSID 				AS 	SAT_DLR_SYSID,
	B.HK_HUB 					AS 	SAT_HK_HUB,
	B.MD_ACTIVE 				AS 	SAT_MD_ACTIVE,
	B.MD_CREATION_AUDIT_ID 		AS 	SAT_MD_CREATION_AUDIT_ID,
	B.MD_CREATION_DT 			AS 	SAT_MD_CREATION_DT,
	B.MD_EXTRACT_DT 			AS 	SAT_MD_EXTRACT_DT,
	B.MD_HASHDIFF 				AS 	SAT_MD_HASHDIFF,
	B.MD_SOURCE 				AS 	SAT_MD_SOURCE,
	B.MD_SRC_SYSTEM 			AS 	SAT_MD_SRC_SYSTEM,
	B.MD_START_DT 				AS 	SAT_MD_START_DT,
	B.PROV_CD 					AS 	SAT_PROV_CD,
	B.REGULATORY_ORG_CD 		AS 	SAT_REGULATORY_ORG_CD,
	B.REGULATORY_ORG_NAME 		AS 	SAT_REGULATORY_ORG_NAME,
	B.REP_CORP_NAME 			AS 	SAT_REP_CORP_NAME,
	B.REP_FNAME 				AS 	SAT_REP_FNAME,
	B.REP_GRP_RSP 				AS 	SAT_REP_GRP_RSP,
	B.REP_LNAME 				AS 	SAT_REP_LNAME,
	B.REP_ST_NAME 				AS 	SAT_REP_ST_NAME,
	B.REP_SYSID 				AS 	SAT_REP_SYSID,
	B.REP_TEAM_CD 				AS 	SAT_REP_TEAM_CD,
	B.REP_TEAM_NAME 			AS 	SAT_REP_TEAM_NAME,
	B.REP_TITLE_DESC 			AS 	SAT_REP_TITLE_DESC,
	B.RGN_CD 					AS 	SAT_RGN_CD,
	B.RGN_MGR 					AS 	SAT_RGN_MGR,
	B.RGN_NAME 					AS 	SAT_RGN_NAME,
	B.RGN_SYSID 				AS 	SAT_RGN_SYSID,
	B.TERMINATE_DT 				AS 	SAT_TERMINATE_DT,
	A.LV2_HK_HUB 				AS 	SAT_LV2_HK_HUB,
	A.LV2_O_DATA_START_DATE 	AS 	SAT_LV2_O_DATA_START_DATE
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.SAT_REGISTERED_REPRESENTATIVE_INVESTIA_UNIVERIS B
	JOIN LV2 A
	ON B.HK_HUB = A.LV2_HK_HUB
	AND B.MD_START_DT = A.LV2_O_DATA_START_DATE
	WHERE B.MD_ACTIVE = ''''A''''
   ),
   JNR_HubWithSat AS (
   SELECT
	A.SAT_BRN_CD 					AS 	SAT_BRN_CD,
	A.SAT_BRN_NAME 					AS 	SAT_BRN_NAME,
	A.SAT_BRN_SYSID 				AS 	SAT_BRN_SYSID,
	A.SAT_COMPANY_CD 				AS 	SAT_COMPANY_CD,
	A.SAT_COMPANY_NAME 				AS 	SAT_COMPANY_NAME,
	A.SAT_CREATE_DT 				AS 	SAT_CREATE_DT,
	A.SAT_DLR_CD 					AS 	SAT_DLR_CD,
	A.SAT_DLR_NAME_ENG 				AS 	SAT_DLR_NAME_ENG,
	A.SAT_DLR_SYSID 				AS 	SAT_DLR_SYSID,
	A.SAT_HK_HUB 					AS 	SAT_HK_HUB,
	A.SAT_LV2_HK_HUB 				AS 	SAT_LV2_HK_HUB,
	A.SAT_MD_ACTIVE 				AS 	SAT_MD_ACTIVE,
	A.SAT_MD_CREATION_AUDIT_ID 		AS 	SAT_MD_CREATION_AUDIT_ID,
	A.SAT_MD_CREATION_DT 			AS 	SAT_MD_CREATION_DT,
	A.SAT_MD_EXTRACT_DT 			AS 	SAT_MD_EXTRACT_DT,
	A.SAT_MD_HASHDIFF 				AS 	SAT_MD_HASHDIFF,
	A.SAT_MD_SOURCE 				AS 	SAT_MD_SOURCE,
	A.SAT_MD_SRC_SYSTEM 			AS 	SAT_MD_SRC_SYSTEM,
	A.SAT_MD_START_DT 				AS 	SAT_MD_START_DT,
	A.SAT_LV2_O_DATA_START_DATE 	AS 	SAT_LV2_O_DATA_START_DATE,
	A.SAT_PROV_CD 					AS 	SAT_PROV_CD,
	A.SAT_REGULATORY_ORG_CD 		AS 	SAT_REGULATORY_ORG_CD,
	A.SAT_REGULATORY_ORG_NAME 		AS 	SAT_REGULATORY_ORG_NAME,
	A.SAT_REP_CORP_NAME 			AS 	SAT_REP_CORP_NAME,
	A.SAT_REP_FNAME 				AS 	SAT_REP_FNAME,
	A.SAT_REP_GRP_RSP 				AS 	SAT_REP_GRP_RSP,
	A.SAT_REP_LNAME 				AS 	SAT_REP_LNAME,
	A.SAT_REP_ST_NAME 				AS 	SAT_REP_ST_NAME,
	A.SAT_REP_SYSID 				AS 	SAT_REP_SYSID,
	A.SAT_REP_TEAM_CD 				AS 	SAT_REP_TEAM_CD,
	A.SAT_REP_TEAM_NAME 			AS 	SAT_REP_TEAM_NAME,
	A.SAT_REP_TITLE_DESC 			AS 	SAT_REP_TITLE_DESC,
	A.SAT_RGN_CD 					AS 	SAT_RGN_CD,
	A.SAT_RGN_MGR 					AS 	SAT_RGN_MGR,
	A.SAT_RGN_NAME 					AS 	SAT_RGN_NAME,
	A.SAT_RGN_SYSID 				AS 	SAT_RGN_SYSID,
	A.SAT_TERMINATE_DT 				AS 	SAT_TERMINATE_DT,
	B.HK_HUB 						AS 	HUB_HK_HUB,
	B.MD_CREATION_AUDIT_ID 			AS 	HUB_MD_CREATION_AUDIT_ID,
	B.MD_CREATION_DT 				AS 	HUB_MD_CREATION_DT,
	B.MD_EXTRACT_DT 				AS 	HUB_MD_EXTRACT_DT,
	B.MD_SOURCE 					AS 	HUB_MD_SOURCE,
	B.MD_SRC_SYSTEM 				AS 	HUB_MD_SRC_SYSTEM,
	B.RR_CD 						AS 	HUB_RR_CD
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.HUB_REGISTERED_REPRESENTATIVE B
	JOIN JNR_SAT_MAXRECORD_WITH_SAT_ALL A
	ON B.HK_HUB = A.SAT_HK_HUB
	WHERE B.MD_SRC_SYSTEM = ''''INVESTIA-UNIVERIS''''
	AND A.sat_REP_LNAME IS NOT NULL
	AND A.sat_REP_FNAME IS NOT NULL
	AND A.sat_MD_ACTIVE = ''''A''''
   ),
   JNR_LINKPARTYWITHRR AS (
   SELECT
	B.HUB_HK_HUB 							AS 	HUB_HK_HUB,
	B.HUB_MD_CREATION_AUDIT_ID AS 	HUB_MD_CREATION_AUDIT_ID,
	B.HUB_MD_CREATION_DT AS 	HUB_MD_CREATION_DT,
	B.HUB_MD_EXTRACT_DT AS 	HUB_MD_EXTRACT_DT,
	B.HUB_MD_SOURCE AS 	HUB_MD_SOURCE,
	B.HUB_MD_SRC_SYSTEM AS 	HUB_MD_SRC_SYSTEM,
	B.HUB_RR_CD AS 	HUB_RR_CD,
	B.SAT_BRN_CD AS 	SAT_BRN_CD,
	B.SAT_BRN_NAME AS 	SAT_BRN_NAME,
	B.SAT_BRN_SYSID AS 	SAT_BRN_SYSID,
	B.SAT_COMPANY_CD AS 	SAT_COMPANY_CD,
	B.SAT_COMPANY_NAME AS 	SAT_COMPANY_NAME,
	B.SAT_CREATE_DT AS 	SAT_CREATE_DT,
	B.SAT_DLR_CD AS 	SAT_DLR_CD,
	B.SAT_DLR_NAME_ENG AS 	SAT_DLR_NAME_ENG,
	B.SAT_DLR_SYSID AS 	SAT_DLR_SYSID,
	B.SAT_HK_HUB AS 	SAT_HK_HUB,
	B.SAT_LV2_HK_HUB AS 	SAT_LV2_HK_HUB,
	B.SAT_MD_ACTIVE AS 	SAT_MD_ACTIVE,
	B.SAT_MD_CREATION_AUDIT_ID AS 	SAT_MD_CREATION_AUDIT_ID,
	B.SAT_MD_CREATION_DT AS 	SAT_MD_CREATION_DT,
	B.SAT_MD_EXTRACT_DT AS 	SAT_MD_EXTRACT_DT,
	B.SAT_MD_HASHDIFF AS 	SAT_MD_HASHDIFF,
	B.SAT_MD_SOURCE AS 	SAT_MD_SOURCE,
	B.SAT_MD_SRC_SYSTEM AS 	SAT_MD_SRC_SYSTEM,
	B.SAT_MD_START_DT AS 	SAT_MD_START_DT,
	B.SAT_LV2_O_DATA_START_DATE AS 	SAT_LV2_O_DATA_START_DATE,
	B.SAT_PROV_CD AS 	SAT_PROV_CD,
	B.SAT_REGULATORY_ORG_CD AS 	SAT_REGULATORY_ORG_CD,
	B.SAT_REGULATORY_ORG_NAME AS 	SAT_REGULATORY_ORG_NAME,
	B.SAT_REP_CORP_NAME AS 	SAT_REP_CORP_NAME,
	B.SAT_REP_FNAME AS 	SAT_REP_FNAME,
	B.SAT_REP_GRP_RSP AS 	SAT_REP_GRP_RSP,
	B.SAT_REP_LNAME AS 	SAT_REP_LNAME,
	B.SAT_REP_ST_NAME AS 	SAT_REP_ST_NAME,
	B.SAT_REP_SYSID AS 	SAT_REP_SYSID,
	B.SAT_REP_TEAM_CD AS 	SAT_REP_TEAM_CD,
	B.SAT_REP_TEAM_NAME AS 	SAT_REP_TEAM_NAME,
	B.SAT_REP_TITLE_DESC AS 	SAT_REP_TITLE_DESC,
	B.SAT_RGN_CD AS 	SAT_RGN_CD,
	B.SAT_RGN_MGR AS 	SAT_RGN_MGR,
	B.SAT_RGN_NAME AS 	SAT_RGN_NAME,
	B.SAT_RGN_SYSID 								AS 	SAT_RGN_SYSID,
	B.SAT_TERMINATE_DT 									AS 	SAT_TERMINATE_DT,
	A.SAT_SHARE_MD_EXTRACT_DT 							AS 	SAT_SHARE_MD_EXTRACT_DT,
	A.SAT_SHARE_MD_SOURCE 								AS 	SAT_SHARE_MD_SOURCE,
	A.SAT_SHARE_SHARE_HK_HUB_PARTY_ROLE_ADVISOR 		AS 	SAT_SHARE_SHARE_HK_HUB_PARTY_ROLE_ADVISOR,
	A.SAT_SHARE_SHARE_MASTER_CODE 						AS 	SAT_SHARE_SHARE_MASTER_CODE
	FROM JNR_HubWithSat B
	JOIN AGG_LINK_PARTY_RELATIONSHIP_COMM A
	ON A.SAT_SHARE_SHARE_MASTER_CODE = B.HUB_RR_CD
   ),
   LV3 AS (
  SELECT
	HK_HUB AS LV3_HK_HUB,
	MAX(MD_START_DT) AS LV3_O_PROV_MAX_START_DT
	FROM DB_IAWT_DEV_DWH.SHARED_RDV.SAT_REF_PROVINCE
	WHERE MD_START_DT <= TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''')
	GROUP BY HK_HUB
  ),
  JNR_SATPROVREGWITHDATEEXTRACT AS (
  SELECT
	B.HK_HUB AS sat_HK_HUB,
	B.MD_ACTIVE AS sat_MD_ACTIVE,
	B.MD_CREATION_AUDIT_ID AS sat_MD_CREATION_AUDIT_ID,
	B.MD_CREATION_DT AS sat_MD_CREATION_DT,
	B.MD_EXTRACT_DT AS sat_MD_EXTRACT_DT,
	B.MD_HASHDIFF AS sat_MD_HASHDIFF,
	B.MD_SOURCE AS sat_MD_SOURCE,
	B.MD_SRC_SYSTEM AS sat_MD_SRC_SYSTEM,
	B.MD_START_DT AS sat_MD_START_DT,
	B.PROV_DESC AS sat_PROV_DESC,
	A.LV3_HK_HUB AS LV3_HK_HUB,
	A.LV3_O_PROV_MAX_START_DT	 AS LV3_O_PROV_MAX_START_DT
	FROM DB_IAWT_DEV_DWH.SHARED_RDV.SAT_REF_PROVINCE B
	JOIN LV3 A
	ON B.MD_START_DT = A.LV3_O_PROV_MAX_START_DT
	AND B.HK_HUB = A.LV3_HK_HUB
  ),
  JNR_HUBWITHSATFORPROVINCE AS (
  SELECT 
	LV3_HK_HUB AS SATPRV_HK_HUB,
	LV3_O_PROV_MAX_START_DT AS satprv_o_PROV_MAX_START_DT,
	SAT_HK_HUB AS SATPRV_SAT_HK_HUB,
	SAT_MD_ACTIVE AS SATPRV_SAT_MD_ACTIVE,
	SAT_MD_CREATION_AUDIT_ID AS SATPRV_SAT_MD_CREATION_AUDIT_ID,
	SAT_MD_CREATION_DT AS SATPRV_SAT_MD_CREATION_DT,
	SAT_MD_EXTRACT_DT AS SATPRV_SAT_MD_EXTRACT_DT,
	SAT_MD_HASHDIFF AS SATPRV_SAT_MD_HASHDIFF,
	SAT_MD_SOURCE AS SATPRV_SAT_MD_SOURCE,
	SAT_MD_SRC_SYSTEM AS SATPRV_SAT_MD_SRC_SYSTEM,
	SAT_MD_START_DT AS SATPRV_SAT_MD_START_DT,
	SAT_PROV_DESC AS SATPRV_SAT_PROV_DESC,
	HK_HUB AS HUBPRV_HK_HUB,
	PROV_CD AS HUBPRV_PROV_CD
	FROM DB_IAWT_''||ENV||''_DWH.SHARED_RDV.REF_PROVINCE B
	JOIN JNR_SATPROVREGWITHDATEEXTRACT A 
	ON B.HK_HUB = A.LV3_HK_HUB
  ),
  JNR_PRV_WITH_MAINLINE AS (
   SELECT 
	TO_DATE(''||DATA_START_DATE||'',''''YYYY-MM-DD'''') AS O_MD_START_DT,
	TO_DATE(TO_CHAR(SAT_SHARE_MD_EXTRACT_DT,''''YYYY-MM-DD''''),''''YYYY-MM-DD'''')  AS o_MD_EXTRACT_DT,
	CURRENT_TIMESTAMP AS o_MD_CREATION_DT,
	B.SAT_SHARE_MD_SOURCE AS O_MAX_MD_SOURCE,
	''''INVESTIA-UNIVERIS'''' as o_MD_SRC_SYSTEM,
	B.SAT_SHARE_SHARE_MASTER_CODE AS SAT_SHARE_SHARE_MASTER_CODE,
	B.SAT_COMPANY_CD AS SAT_COMPANY_CD,
	B.SAT_REGULATORY_ORG_NAME AS SAT_REGULATORY_ORG_NAME,
	B.SAT_REGULATORY_ORG_CD AS SAT_REGULATORY_ORG_CD,
	B.SAT_DLR_CD AS SAT_DLR_CD,
	B.SAT_DLR_NAME_ENG AS SAT_DLR_NAME_ENG,
	B.SAT_RGN_CD AS SAT_RGN_CD,
	B.SAT_RGN_NAME AS SAT_RGN_NAME,
	CASE WHEN B.SAT_RGN_MGR IS NULL THEN ''''Non affiliated to RVPs'''' ELSE B.SAT_RGN_MGR END AS o_RVP,
	B.SAT_BRN_CD AS SAT_BRN_CD,
	B.SAT_BRN_NAME AS SAT_BRN_NAME,
	B.SAT_REP_TEAM_CD AS SAT_REP_TEAM_CD,
	B.SAT_REP_TEAM_NAME AS SAT_REP_TEAM_NAME,
	CONCAT(CASE WHEN B.SAT_REP_LNAME IS NULL THEN '''''''' ELSE B.SAT_REP_LNAME END , '''','''',CASE WHEN B.SAT_REP_FNAME IS NULL THEN '''''''' ELSE B.SAT_REP_FNAME END, ''''('''',B.SAT_SHARE_SHARE_MASTER_CODE, '''')'''') AS ADVISORFULLNAME,
	B.SAT_REP_FNAME AS SAT_REP_FNAME,
	B.SAT_REP_LNAME AS SAT_REP_LNAME,
	B.SAT_COMPANY_NAME AS SAT_COMPANY_NAME,
	B.SAT_REP_ST_NAME AS SAT_REP_ST_NAME,
	B.SAT_REP_GRP_RSP AS SAT_REP_GRP_RSP,
	CASE WHEN B.SAT_PROV_CD IS NULL THEN ''''N/A'''' ELSE CASE WHEN B.SAT_PROV_CD = ''''#N/A'''' THEN ''''N/A'''' ELSE B.SAT_PROV_CD END END AS O_PROVINCE_CODE,
	A.SATPRV_SAT_PROV_DESC AS SATPRV_SAT_PROV_DESC,
	TO_DATE(TO_CHAR(B.sat_CREATE_DT,''''YYYY-MM-DD''''),''''YYYY-MM-DD'''') AS O_CREATE_DT,
	B.SAT_SHARE_SHARE_HK_HUB_PARTY_ROLE_ADVISOR AS HK_HUB
	FROM JNR_LINKPARTYWITHRR B 
	LEFT JOIN JNR_HUBWITHSATFORPROVINCE A
	ON B.SAT_PROV_CD = A.HUBPRV_PROV_CD
	)
	SELECT
	O_MD_START_DT 							AS 	MD_START_DT,
	O_MD_EXTRACT_DT 						AS 	MD_EXTRACT_DT,
	O_MD_CREATION_DT 						AS 	MD_CREATION_DT,
	O_MAX_MD_SOURCE 						AS 	MD_SOURCE,
	O_MD_SRC_SYSTEM 						AS 	MD_SRC_SYSTEM,
	SAT_SHARE_SHARE_MASTER_CODE 			AS 	MASTER_CODE,
	SAT_COMPANY_CD 							AS 	COMPANY_CODE,
	SAT_COMPANY_NAME 						AS 	COMPANY_NAME,
	SAT_REGULATORY_ORG_NAME 				AS 	REGULATORY_ORGANIZATION_NAME,
	SAT_REGULATORY_ORG_CD 					AS 	REGULATORY_ORGANIZATION_CODE,
	SAT_DLR_CD 								AS 	DEALER_CODE,
	SAT_DLR_NAME_ENG 						AS 	DEALER_NAME,
	SAT_RGN_CD 								AS 	REGION_CODE,
	SAT_RGN_NAME 							AS 	REGION_NAME,
	O_RVP 									AS 	REGION_VP,
	SAT_BRN_CD 								AS 	BRANCHCODE,
	SAT_BRN_NAME 							AS 	BRANCHNAME,
	SAT_REP_TEAM_CD 						AS 	TEAM_CODE,
	SAT_REP_TEAM_NAME 						AS 	TEAM_NAME,
	ADVISORFULLNAME 						AS 	ADVISOR_FULLNAME,
	SAT_REP_FNAME 							AS 	FIRSTNAME,
	SAT_REP_LNAME 							AS 	LASTNAME,
	SAT_COMPANY_NAME 						AS 	ADVISOR_CORPORATION_NAME,
	SAT_REP_ST_NAME 						AS 	STATUS,
	SAT_REP_GRP_RSP 						AS 	GROUP_RSP_INDICATOR,
	O_PROVINCE_CODE 						AS 	PROVINCE_CODE,
	SATPRV_SAT_PROV_DESC 					AS 	PROVINCE,
	O_CREATE_DT 							AS 	CADVISOR_START_DATE,
	BUSINESS_RULES.UDF_CONV_BR_ALL_ADVISOR_001(o_CREATE_DT,O_MD_START_DT) AS NEW_ADVISOR_IND,
	HK_HUB
	FROM JNR_PRV_WITH_MAINLINE)'';
UPD_QUERY := ''UPDATE DB_IAWT_''||ENV||''_DWH.SHARED_BDV.WT_PARTY_ROLE_ADVISOR_COMPUTE_IAS_WEALTH
SET
MD_HASHDIFF=SHA1(UPPER(CONCAT(COALESCE(TRIM(COMPANY_CODE),''''NULL'''') ,''''|'''',COALESCE(TRIM(COMPANY_NAME),''''NULL''''), ''''|'''',  COALESCE(TRIM(REGULATORY_ORGANIZATION_NAME),''''NULL''''),
''''|'''',  COALESCE(TRIM(REGULATORY_ORGANIZATION_CODE),''''NULL''''),''''|'''',COALESCE(TRIM(DEALER_CODE),''''NULL''''),''''|'''',COALESCE(TRIM(DEALER_NAME),''''NULL''''),
''''|'''',COALESCE(TRIM(REGION_CODE),''''NULL''''),''''|'''',COALESCE(TRIM(REGION_NAME),''''NULL''''),''''|'''',COALESCE(TRIM(REGION_VP),''''NULL'''')
,''''|'''',COALESCE(TRIM(BRANCHCODE),''''NULL''''),''''|'''',COALESCE(TRIM(BRANCHNAME),''''NULL''''),''''|'''',COALESCE(TRIM(to_varchar(TEAM_CODE)),''''NULL'''')
,''''|'''',COALESCE(TRIM(TEAM_NAME),''''NULL''''),''''|'''',COALESCE(TRIM(ADVISOR_FULLNAME),''''NULL''''),''''|'''',COALESCE(TRIM(FIRSTNAME),''''NULL'''')
,''''|'''',COALESCE(TRIM(LASTNAME),''''NULL''''),''''|'''',COALESCE(TRIM(ADVISOR_CORPORATION_NAME),''''NULL''''),''''|'''',COALESCE(TRIM(STATUS),''''NULL'''')
,''''|'''',COALESCE(TRIM(GROUP_RSP_INDICATOR),''''NULL''''),''''|'''',COALESCE(TRIM(PROVINCE_CODE),''''NULL''''),''''|'''',COALESCE(TRIM(PROVINCE),''''NULL'''')
,''''|'''',COALESCE(TRIM(to_varchar(ADVISOR_START_DATE)),''''NULL''''),''''|'''',COALESCE(TRIM(to_varchar(NEW_ADVISOR)),''''NULL'''')
)))
Where MD_SRC_SYSTEM = ''''INVESTIA-UNIVERIS'''''';
EXECUTE IMMEDIATE :DEL_QUERY;
EXECUTE IMMEDIATE :INS_QUERY;
EXECUTE IMMEDIATE :UPD_QUERY;
END

';