SELECT 
	A.[ACT_SYSID] AS [ACT_SYSID],
	A.[IVD_SYSID] AS [IVD_SYSID],
	COALESCE(X.[MASTER_CD],X.[REP_CD_ORIGINAL]) AS [MASTER_CD],
	A.[REP_SYSID] AS [REP_SYSID],
	A.[IVR_SYSID] AS [IVR_SYSID],
	A.[PLN_SYSID] AS [PLN_SYSID],
	A.[FISCAL_SYSID] AS [FISCAL_SYSID],
	A.[BAL_DATE] AS  [BAL_DATE],
	A.[MV]*ISNULL(X.[COMM_RATE],1) AS [MV] ,
	NULLIF(REPLACE(REPLACE(A.[CURRENCY_CD], CHAR(13), ''), CHAR(10), ''),'') AS [CURRENCY_CD] ,
	A.[EXCH_DT] ,
	A.[EXCH_RATE] ,
	A.[MV_CNV]*ISNULL(X.[COMM_RATE],1) AS [AUA] ,
	A.[PRICE] ,
	A.[UNITS]*ISNULL(X.[COMM_RATE],1) AS [UNITS],
	A.[BV]*ISNULL(X.[COMM_RATE],1) AS [BV] ,
	A.[ACB]*ISNULL(X.[COMM_RATE],1) AS [ACB],
	A.[NI_T]*ISNULL(X.[COMM_RATE],1) AS [NI_T],
	A.[NI_P]*ISNULL(X.[COMM_RATE],1) AS [NI_P],
	NULLIF(REPLACE(REPLACE(A.[FREQ_CD], CHAR(13), ''), CHAR(10), ''),'') AS [FREQ_CD] ,
	A.[UNITS_TRD_DT] ,
	A.[FISCAL_TD_UNITS],
	IVD.IVD_LOAD_FLAG, 
	IVD.WF_IND,
	CONVERT(DATE, GETDATE()) AS MD_LOADDATE,
	'FUNDEX-UNIVERIS' AS MD_SRCSYSTEM
FROM
	[dbo].[ACT_BAL] A (nolock)
LEFT OUTER JOIN [dbo].[x_DBB_MASTER_REP] X (nolock)
ON A.[REP_SYSID]=X.[REP_SYSID]
LEFT JOIN [dbo].IVD IVD (nolock)
ON A.IVD_SYSID=IVD.IVD_SYSID
WHERE
     /* As per Eric it should be done on Thrusday night as Monday they do the calculation */
    BAL_DATE = (SELECT MAX([BAL_DATE]) from [dbo].[ACT_BAL] (nolock) WHERE [BAL_DATE]<=(DATEADD(WEEK,-1,GETDATE())) AND DATEPART(WEEKDAY,GETDATE())=6) 
ORDER BY A.[ACT_SYSID] , A.[PLN_SYSID] , A.[IVR_SYSID] , A.[IVD_SYSID] , A.[REP_SYSID] , X.[MASTER_CD]
;