SELECT
	PLN_SRF_SYSID,
	PLN_SYSID,
	NULLIF(REPLACE(REPLACE(FAS_FILE_NAME,CHAR(13), ''), CHAR(10), ''),'') AS FAS_FILE_NAME,
	FROM_DT,
	TO_DT,
	NULLIF(REPLACE(REPLACE(MGT_CD,CHAR(13), ''), CHAR(10), ''),'') AS MGT_CD,
	NULLIF(REPLACE(REPLACE(CURRENCY_CD,CHAR(13), ''), CHAR(10), ''),'') AS CURRENCY_CD,
	NULLIF(REPLACE(REPLACE(INCOME_TYPE,CHAR(13), ''), CHAR(10), ''),'') AS INCOME_TYPE,
	NULLIF(REPLACE(REPLACE(REP_CODE,CHAR(13), ''), CHAR(10), ''),'') AS  REP_CODE,
	COM_PYBL ,
	EXCH_DT ,
	EXCH_RATE ,
	LAST_UPD_DT ,
	USR_SYSID ,
	FISCAL_SYSID ,
	NULLIF(REPLACE(REPLACE(JUR_CD,CHAR(13), ''), CHAR(10), ''),'') AS  JUR_CD,
	NULLIF(REPLACE(REPLACE(ACT_TAX_COLLCTD,CHAR(13), ''), CHAR(10), ''),'') AS  ACT_TAX_COLLCTD,
	DLR_SYSID ,
	RGN_SYSID ,
	BRN_SYSID ,
	REP_SYSID,
	CONVERT(DATE, GETDATE()) AS MD_LOADDATE,
	'FUNDEX-UNIVERIS' AS MD_SRCSYSTEM
FROM
	dbo.PLN_SRF (nolock)
WHERE 
	YEAR(TO_DT)= YEAR(GETDATE()) AND MONTH(TO_DT)= MONTH(GETDATE())-1 ;