/*SELECT 
	A.[ACT_SYSID] AS [ACT_SYSID],
	A.[IVD_SYSID] AS [IVD_SYSID],
	A.[REP_SYSID] AS [REP_SYSID],
	A.[IVR_SYSID] AS [IVR_SYSID],
	A.[PLN_SYSID] AS [PLN_SYSID],
	A.[FISCAL_SYSID] AS [FISCAL_SYSID],
	A.[BAL_DATE] AS  [BAL_DATE],
	A.[MV] ,
	NULLIF(REPLACE(REPLACE(A.[CURRENCY_CD], CHAR(13), ''), CHAR(10), ''),'') AS [CURRENCY_CD] ,
	A.[EXCH_DT] ,
	A.[EXCH_RATE] ,
	A.[MV_CNV] AS [AUA] ,
	A.[PRICE] ,
	A.[UNITS],
	A.[BV] ,
	A.[ACB],
	A.[NI_T],
	A.[NI_P],
	NULLIF(REPLACE(REPLACE(A.[FREQ_CD], CHAR(13), ''), CHAR(10), ''),'') AS [FREQ_CD] ,
	A.[UNITS_TRD_DT] ,
	A.[FISCAL_TD_UNITS],
	IVD.IVD_LOAD_FLAG, 
	IVD.WF_IND,
	CONVERT(DATE, GETDATE()) AS MD_LOADDATE,
	'IAS-UNIVERIS' AS MD_SRCSYSTEM
FROM
	[dbo].[ACT_BAL] A (nolock)
LEFT JOIN [dbo].IVD IVD (nolock)
ON A.IVD_SYSID=IVD.IVD_SYSID
WHERE
    -- As per Eric it should be done on 5th of the month for Univeris System 
	BAL_DATE = (SELECT MAX([BAL_DATE]) from [dbo].[ACT_BAL] (nolock) WHERE [BAL_DATE]<=EOMONTH(DATEADD(MONTH,-1,GETDATE())))
ORDER BY A.[ACT_SYSID] , A.[PLN_SYSID] , A.[IVR_SYSID] , A.[IVD_SYSID] , A.[REP_SYSID]
;*/
SELECT 
	A.[ACT_SYSID] AS [ACT_SYSID],
	A.[IVD_SYSID] AS [IVD_SYSID],
	A.[REP_SYSID] AS [REP_SYSID],
	A.[IVR_SYSID] AS [IVR_SYSID],
	A.[PLN_SYSID] AS [PLN_SYSID],
	A.[FISCAL_SYSID] AS [FISCAL_SYSID],
	A.[BAL_DATE] AS  [BAL_DATE],
	CAST(A.[MV] as VARCHAR) as [MV],
	NULLIF(REPLACE(REPLACE(A.[CURRENCY_CD], CHAR(13), ''), CHAR(10), ''),'') AS [CURRENCY_CD] ,
	A.[EXCH_DT] ,
	CAST(A.[EXCH_RATE] as VARCHAR) as [EXCH_RATE] ,
	CAST(A.[MV_CNV] as VARCHAR) as [AUA],
	CAST(A.[PRICE] as VARCHAR) as [PRICE],
	CAST(A.[UNITS] as VARCHAR) as [UNITS],
	CAST(A.[BV] as VARCHAR) as [BV],
	A.[ACB],
	A.[NI_T],
	A.[NI_P],
	NULLIF(REPLACE(REPLACE(A.[FREQ_CD], CHAR(13), ''), CHAR(10), ''),'') AS [FREQ_CD] ,
	CAST(A.[UNITS_TRD_DT] as VARCHAR) as UNITS_TRD_DT,
	CAST(A.[FISCAL_TD_UNITS] as VARCHAR) as FISCAL_TD_UNITS,
	IVD.IVD_LOAD_FLAG, 
	IVD.WF_IND,
	CONVERT(DATE, GETDATE()) AS MD_LOADDATE,
	'IAS-UNIVERIS' AS MD_SRCSYSTEM
FROM
	[dbo].[ACT_BAL] A (nolock)
LEFT JOIN [dbo].IVD IVD (nolock)
ON A.IVD_SYSID=IVD.IVD_SYSID
WHERE
    /* As per Eric it should be done on 5th of the month for Univeris System */
	BAL_DATE = (SELECT MAX([BAL_DATE]) from [dbo].[ACT_BAL] (nolock) WHERE [BAL_DATE]<=EOMONTH(DATEADD(MONTH,-1,GETDATE())))
ORDER BY A.[ACT_SYSID] , A.[PLN_SYSID] , A.[IVR_SYSID] , A.[IVD_SYSID] , A.[REP_SYSID]