SELECT
	S.PLN_SRF_SYSID,
	S.PLN_SYSID,
	NULLIF(REPLACE(REPLACE(S.FAS_FILE_NAME,CHAR(13), ''), CHAR(10), ''),'') AS FAS_FILE_NAME,
	S.FROM_DT,
	S.TO_DT,
	NULLIF(REPLACE(REPLACE(S.MGT_CD,CHAR(13), ''), CHAR(10), ''),'') AS MGT_CD,
	NULLIF(REPLACE(REPLACE(S.CURRENCY_CD,CHAR(13), ''), CHAR(10), ''),'') AS CURRENCY_CD,
	NULLIF(REPLACE(REPLACE(S.INCOME_TYPE,CHAR(13), ''), CHAR(10), ''),'') AS INCOME_TYPE,
	NULLIF(REPLACE(REPLACE(S.REP_CODE,CHAR(13), ''), CHAR(10), ''),'') AS  REP_CODE,
	CAST(S.COM_PYBL as VARCHAR) as COM_PYBL,
	S.EXCH_DT ,
	S.EXCH_RATE ,
	S.LAST_UPD_DT ,
	S.USR_SYSID ,
	S.FISCAL_SYSID ,
	NULLIF(REPLACE(REPLACE(S.JUR_CD,CHAR(13), ''), CHAR(10), ''),'') AS  JUR_CD,
	NULLIF(REPLACE(REPLACE(S.ACT_TAX_COLLCTD,CHAR(13), ''), CHAR(10), ''),'') AS  ACT_TAX_COLLCTD,
	S.DLR_SYSID ,
	S.RGN_SYSID ,
	S.BRN_SYSID ,
	S.REP_SYSID,
    PLN.IVR_SYSID,
	CS.IVD_SYSID,
    CONVERT(DATE, GETDATE()) AS MD_LOADDATE,
	'IAS-UNIVERIS' AS MD_SRCSYSTEM
	
FROM
	dbo.PLN_SRF S (nolock)
	LEFT JOIN [dbo].[PLN] PLN (nolock)
	ON PLN.PLN_SYSID = S.PLN_SYSID
	LEFT JOIN [dbo].[COM_SRF] CS (nolock)
	ON CS.PLN_SRF_SYSID = S.PLN_SRF_SYSID
WHERE 
	YEAR(S.TO_DT)= YEAR(GETDATE()) AND MONTH(S.TO_DT)= MONTH(GETDATE())-1;