SELECT	'Wealth' AS COMPANY_CD,
		'iA Wealth Management' AS COMPANY_NAME,
		'IIROC' AS REGULATORY_ORG_CD,  
		'Investment Industry Regulatory Organization of Canada' AS REGULATORY_ORG_NAME,  
		  R.[DLR_SYSID]
		  ,NULLIF(REPLACE(REPLACE(R.[DLR_CD], CHAR(13), ''), CHAR(10), ''),'') AS DLR_CD
		  ,'Industrial Alliance Securities Inc.' AS DLR_NAME_ENG
		  ,R.[RGN_SYSID]
		  ,NULLIF(REPLACE(REPLACE(R.[RGN_CD], CHAR(13), ''), CHAR(10), ''),'') AS RGN_CD
		  ,NULLIF(REPLACE(REPLACE(RGN.RGN_NAME, CHAR(13), ''), CHAR(10), ''),'') AS RGN_NAME
		  ,'All' AS RGN_MGR
		  ,R.[BRN_SYSID]
		  ,NULLIF(REPLACE(REPLACE(R.[BRN_CD], CHAR(13), ''), CHAR(10), ''),'') AS BRN_CD
		  ,NULLIF(REPLACE(REPLACE(BRN.BRN_NAME, CHAR(13), ''), CHAR(10), ''),'') AS BRN_NAME
		  ,NULLIF('','') AS REP_TEAM_CD
		  ,NULLIF('','') AS REP_TEAM_NAME
		  ,R.REP_SYSID
		  ,NULLIF(REPLACE(REPLACE(R.[REP_CD], CHAR(13), ''), CHAR(10), ''),'') AS NK_REP_CD
		  /*,CONVERT(VARCHAR(64),HASHBYTES('SHA2_256', CONVERT(VARCHAR(11), COALESCE(R.[SIN],'')) + '|' + 'iA Wealth'),2) AS NK_SIN_HASH*/
		  ,NULLIF(REPLACE(REPLACE(REP_CORP_NAME, CHAR(13), ''), CHAR(10), ''),'') AS [NK_REP_CORP_NAME]
		  ,NULLIF(REPLACE(REPLACE(R.[REP_LNAME], CHAR(13), ''), CHAR(10), ''),'') AS [REP_LNAME]
		  ,NULLIF(REPLACE(REPLACE(R.[REP_FNAME], CHAR(13), ''), CHAR(10), ''),'') AS [REP_FNAME]
		  /*,R.[REP_BIRTH_DT]*/
		  ,NULLIF(REPLACE(REPLACE(ST.REP_ST_NAME, CHAR(13), ''), CHAR(10), ''),'') AS [REP_ST_NAME]
		  ,NULLIF(REPLACE(REPLACE(R.[REP_GRP_RSP], CHAR(13), ''), CHAR(10), ''),'') AS [REP_GRP_RSP]		  
		  ,CONVERT(DATE, GETDATE()) AS MD_LOADDATE
		  ,'IAS-UNIVERIS' AS MD_SRCSYSTEM
  FROM [dbo].[REP] R (nolock)
  LEFT JOIN dbo.BRN (nolock)
  ON R.BRN_SYSID = BRN.BRN_SYSID
  LEFT JOIN dbo.DLR (nolock)
  ON BRN.DLR_SYSID = DLR.DLR_SYSID
  LEFT JOIN dbo.RGN (nolock)
  ON R.RGN_SYSID = RGN.RGN_SYSID
  LEFT JOIN dbo.S_REP_STATUS ST (nolock)
  ON R.REP_STATUS = ST.REP_STATUS
  ORDER BY REP_SYSID,NK_REP_CD