SELECT
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_CD, CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_CD ,
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_MNEM,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_MNEM ,
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_DESC,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_DESC ,
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_LONG_DESC,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_LONG_DESC ,
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_MNEM_ENG,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_MNEM_ENG ,
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_MNEM_FRE,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_MNEM_FRE ,
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_DESC_ENG,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_DESC_ENG ,
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_DESC_FRE,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_DESC_FRE ,
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_LONG_DESC_ENG,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_LONG_DESC_ENG ,
	NULLIF(REPLACE(REPLACE(REPLACE(COM_PROD_LONG_DESC_FRE,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS COM_PROD_LONG_DESC_FRE ,
	NULLIF(REPLACE(REPLACE(REPLACE(CRC_TRND_RPT_CAT,CHAR(13), ''), CHAR(10), ''),'|','\|'), '') AS CRC_TRND_RPT_CAT ,
	COMMISSION_LEVEL,
	CAC_TYPE_CD,
	ACC_REPORT_IND,
	CONVERT(DATE, GETDATE()) AS MD_LOADDATE,
	'IAS-UNIVERIS' AS MD_SRCSYSTEM
FROM
	dbo.S_COM_PROD