SELECT DISTINCT
	REPLACE(REPLACE(B.FMSL_ACCOUNT_NUMBER, CHAR(13), ''), CHAR(10), '') AS A_C_ID,
	REPLACE(REPLACE(B.RR_NUMBER, CHAR(13), ''), CHAR(10), '') AS A_C_Representative, 
	REPLACE(REPLACE(B.SECURITY_NUMBER, CHAR(13), ''), CHAR(10), '') AS TI_Alternate_ID, 
	REPLACE(REPLACE(B.SECURITY_TYPE_CODE, CHAR(13), ''), CHAR(10), '') AS TI_Alternate_TI_Type,
	REPLACE(REPLACE(B.BUY_SELL_INDICATOR, CHAR(13), ''), CHAR(10), '') AS Tran_Entry_Description,
	#REPLACE(REPLACE(B.Tran_User_Description, CHAR(13), ''), CHAR(10), '') AS Tran_User_Description,
	#REPLACE(REPLACE(B.Tran_Type, CHAR(13), ''), CHAR(10), '') AS Tran_Trading_Type,
	B.TRANSACTION_NUMBER,
	B.TRADE_GROUP_GROSS_AMOUNT AS Tran_Trading_Gross_Amt, # to check
	REPLACE(REPLACE(B.TRAN_TRADING_NET_CURRENCY, CHAR(13), ''), CHAR(10), '') AS Tran_Trading_Currency,
	B.TRADE_DATE,
	B.SETTLEMENT_DATE,
	
	B.PROCESS_DATE,
	B.SECURITY_SYMBOL,
	B.TRADE_GROUP_QUANTITY,
	
	'CMSDT' AS MD_Src,
	CURDATE() AS MD_LOADDATE,
	'IAS' AS MD_SRCSYSTEM
FROM CMSDT B
WHERE B.TRADE_DATE = SUBDATE(CURDATE(), 1)
ORDER BY B.FMSL_ACCOUNT_NUMBER,B.RR_NUMBER,B.SECURITY_NUMBER;