SELECT DISTINCT 
REPLACE(REPLACE(AC.A_C_Account_Class, CHAR(13), ''), CHAR(10), '') AS A_C_Account_Class
,REPLACE(REPLACE(AC.Retail_Plan, CHAR(13), ''), CHAR(10), '') AS Retail_Plan
, REPLACE(REPLACE(AC.Retail_Plan_RESP, CHAR(13), ''), CHAR(10), '') AS Retail_Plan_RESP
, REPLACE(REPLACE(AC.Account_Rap_Code, CHAR(13), ''), CHAR(10), '') AS Account_Rap_Code,
	CURDATE() AS MD_LOADDATE,
	'IAS' AS MD_SRCSYSTEM
FROM IAVMACT AC
ORDER BY A_C_Account_Class 
#INTO OUTFILE 'C:\\BW_IAS_EXPORT_ACCP\\PLANS.bcp' FIELDS TERMINATED BY '|' LINES TERMINATED BY '\r\n';